### ISSUE TITLE
[BUG] Interfering with steam market auto agree scripts and extensions

### ISSUE THREAD

**Issue by pacopepepipo** [IsThereAnyDeal/AugmentedSteam#1038]
### Expected Behavior
To not interfere with other 

### Actual Behavior
When AS is enabled, the other extensions to check the box of I agree on the market automatically, don't work

### Steps to Reproduce the Problem

  1. Enable AS
  2. Install https://chrome.google.com/webstore/detail/steam-market-auto-agree/hdommeagcldeibnepgadkfbhiofkndgf?hl=en
  3. wont work

### Specifications

  - Augmented Steam Version: latest
  - Browser Version : chrome latest

**Comment by candela97** [comment]
There may very well be conflicts if 2 extensions try to manipulate the state of the same checkbox. Since you're here, I suggest you rely on Augmented Steam for this funtionality 😄.

**Comment by MxtOUT** [comment]
wdym not work? It works for me

**Comment by Revadike** [comment]
> wdym not work? It works for me

I think he wants you to add compatibility for other third party addons. I don't know if that's in your scope...

**Comment by pacopepepipo** [comment]
> There may very well be conflicts if 2 extensions try to manipulate the state of the same checkbox. Since you're here, I suggest you rely on Augmented Steam for this funtionality 😄.

does it have it?

Maybe I'm blind, it's the first thing I looked on options but I didn't see it

**Comment by MxtOUT** [comment]
What is "not working"?
The checkbox isn't checked?

**Comment by candela97** [comment]
This feature is enabled by default without an option. Closing for now since we can't seem to reproduce this. Feel free to comment if there're still problems.
