### ISSUE TITLE
Suggestion: add current nickname to input box

### ISSUE THREAD

**Issue by bottleblue** [IsThereAnyDeal/AugmentedSteam#1052]
If you're not friends with a steam user the Add Nickname function doesn't save the text. This used to work in Enhanced Steam.

Also, after you saved the nickname if you click Add Nickname again it should show the name in the textbox instead of being blank.  This is helpful if you have a long nickname or description since it gets cut off on the page. You'd be able to see the whole thing and if you need to make a quick edit you don't have to type the entire thing again.

**Comment by Revadike** [comment]
The nickname feature still works for me, but I like your suggestion of adding the current nickname to the input box.

**Comment by bottleblue** [comment]
I tested it again and nickname is working now so maybe it was just a glitch with the browser. I'll edit the subject to suggest adding nickname to textbox. Thx for replying.
