### ISSUE TITLE
[FEATURE REQUEST] Preview background for item shop

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#1063]
### Current Behavior (if any)
Item shop is lacking the preview background feature

### Desired Behavior
Add a button to preview background for (animated) background available in the steam item shop

### Motivation / Use Case for Changing the Behavior
More convenient and consistent with market feature.

**Comment by candela97** [comment]
There's a mockup preview in the purchase modal, but it does seem useful to provide a link to user profiles like on the market. We can check if the selected item is a background with `'[class^="redeempointsmodal_BackgroundPreviewContainer]'`.

**Comment by candela97** [comment]
Steam began providing previews for game profiles, e.g. https://steamcommunity.com/my/?previewprofile=1&appid=730&itemtype=35, hopefully they'll expand it to backgrounds as well.
