### ISSUE TITLE
[FEATURE REQUEST] Add a games library

### ISSUE THREAD

**Issue by TristanDelcourt** [IsThereAnyDeal/AugmentedSteam#1066]
So I reacently asked this on dicord and was asked to put it here so here you go:
I would like to be able to click a "play" button that would lead to a link to open the selected game, for example for CSGO:  steam://rungame/730/USERID/ (I have no idea why the user ID needs to be there but when testing it wouldn't work without)
This could be placed in the Games tab on my profile or add an entire library for this specifically.

This would be amazing because it is quite tedious having to either: find the game on the market and find the "open in library" or having to open the Steam Client as well as the web version to open my games.

Thx for reading!

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/107965039-4fddee00-6faa-11eb-821b-f43881c516df.png)
This is not what you mean?

**Comment by TristanDelcourt** [comment]
Yes but it is quite tedious to go to the store, find the game, then launch... It would be better if there was a play button next to installed games in the "Games" tab on my profile that automatically links to the right URL to launch the game.

**Comment by TristanDelcourt** [comment]
![AS](https://user-images.githubusercontent.com/58972497/107985039-998a0100-6fc9-11eb-86ef-459be9275f37.png)
Like this if you will

**Comment by MxtOUT** [comment]
Why not use the Steam client library if you already know you want to launch a certain game?
The only benefit I could see here are the sorting options that the web version has.
Otherwise this page takes very long to load and filtering can be laggy too for big libraries

**Comment by Revadike** [comment]
I haven't been able to use that page for years. I pretty much don't even know how it looks like :P
