### ISSUE TITLE
[BUG] Request Failed

### ISSUE THREAD

**Issue by SpyderZT** [IsThereAnyDeal/AugmentedSteam#1069]
### Expected Behavior
No Red Exclamation

### Actual Behavior
Red Exclamation

### Steps to Reproduce the Problem

  1. Load Steam Website
  2. See Red Exclamation
  3. View Error Console
  4. See this:

![image](https://user-images.githubusercontent.com/14990202/108047736-606e8280-7003-11eb-93e3-b25dced08abe.png)

  5. Go to game page, get this:

![image](https://user-images.githubusercontent.com/14990202/108047475-16859c80-7003-11eb-99b4-0f7e00e26397.png)

I can provide more logs and etc. if necessary.

### Specifications

  - Augmented Steam Version: 2.0.0
  - Browser Version :  Chrome 88.0.4324.150 (Official Build) (64-bit)

**Comment by MxtOUT** [comment]
Is this reproducible for you?

**Comment by Revadike** [comment]
I think the first error is fine, but for the 2nd error it would help to see where in the code is originates from.

**Comment by MxtOUT** [comment]
What are the two errors here for you?

**Comment by MxtOUT** [comment]
On the first screenshot it just can't load the source map (that's a Chrome problem) and on the second the warning is not related to AS

**Comment by Revadike** [comment]
If the errors are unrelated to AS, why even leave the issue open? 🤔
