### ISSUE TITLE
[FEATURE REQUEST] Redirect if app is region locked

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#1093]
### Current Behavior (if any)
When you visit an app page in the Steam Store, that is region locked, it will give you an error message.

### Desired Behavior
Since just this error message is useless, I propose to add links or redirect to SteamDB and/or the steam community page.

### Example
https://store.steampowered.com/app/239140/Dying_Light/ for german users
![image](https://user-images.githubusercontent.com/4411977/109526786-3dd47300-7ab3-11eb-95b5-6ead31a41b68.png)

### Additional Info
https://github.com/tfedor/AugmentedSteam/issues/294#issuecomment-544275854

**Comment by candela97** [comment]
This error box can also appear if the game is age-gated or for some other generic site error. I guess we can enable 3rd-party site links on these pages + a link to steam community page.
