### ISSUE TITLE
[FEATURE REQUEST] Enable "Game User Tag Votes" list infinite scroll

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1122]
https://help.steampowered.com/en/accountdata/AppUserTagVotes

### Current Behavior (if any)
To load the next portion of records, the user has to click the "Load more" link.

### Desired Behavior
The entire list is loaded immediately.

### Motivation / Use Case for Changing the Behavior
Now, just to look at the list with tens of thousands of tags set, you have to spend too much time loading this list. The site does not provide any export, only - saving html after loading it.

**Comment by candela97** [comment]
The help site has quite a few pages that have this "load all" link, not just the one you mentioned. Thing is, the extension currently doesn't run on the help site at all, and I think we'll need a good amount of useful features to start considering enabling the extension on the help site.
