### ISSUE TITLE
[FEATURE REQUEST] Add howlongis.io section (as an alternative for howlongtobeat)

### ISSUE THREAD

**Issue by alpe12** [IsThereAnyDeal/AugmentedSteam#1140]
### Motivation / Use Case for Changing the Behavior
Currently there is a _howlongtobeat_ section that [doesn't work](https://github.com/tfedor/AugmentedSteam/issues/924). Maybe because of appid not matching steam (?).
_howlongis.io_ appid matches the ones used by Steam.

It provides many average playtime statistics that would be very useful to have.
Specially since _howlongtobeat_ doesn't work. And even if it did, I think it would be nice to have an alternative so that we can choose.

The ones that I think definetly should be added from _howlongis.io_ are: **Average playtime** and the **playtime from TOP 10% players**.
There are also "Time played by percentile" and "Time played by rating" which could be interesting as an additional option.

Sample: https://howlongis.io/app/8870/BioShock+Infinite
How they determine playtime: https://howlongis.io/blog/2/How+we+determine+playtimes

Thanks.

**Comment by Revadike** [comment]
If howlongis.io has native API support, this could be easily added without having to wait for ITAD server to implement it.

**Comment by candela97** [comment]
FYI, data from HowLongToBeat should be up and working now. Let us know if there're still problems!

**Comment by candela97** [comment]
The site is gone and and redirects to a page that says the domain is up for sale it seems.
