### ISSUE TITLE
[FEATURE REQUEST] Steam Avatar Dialog

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#1148]
### Current Behavior (if any)
When you click on a player's avatar on their steam profile, nothing happens.

### Desired Behavior
Just like steam store screenshots, open a dialog displaying the full sized avatar, which an option to download it. 

### Motivation / Use Case for Changing the Behavior
Nice to have if you find an interesting player avatar that you'd like to save.

**Comment by candela97** [comment]
Sounds good. Would be cool if it can also show a popup of which game the avatar is from if it's official (like emojis).

**Comment by candela97** [comment]
Given that you can simply right click to save or open the avatar in a new tab, I don't think a dialog is neccessary. Now there's also a button on profiles to view their equipped points shop items, which solves the issue with finding out which game the items are from. Closing as resolved.
