### ISSUE TITLE
[FEATURE REQUEST] Add an option to show confirmation before deleting comments

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/AugmentedSteam#1166]
### Current Behavior (if any)
No confirmation is shown for deleting comments on your profile, for example, and it's easy to misclick.

### Desired Behavior
Show a confirmation before deleting a comment, like when deleting forum posts. Same thing can be done for the "hide and report" button, though it's less problematic because hiding can be undone.

### Motivation / Use Case for Changing the Behavior
Came across https://steamcommunity.com/discussions/forum/10/3118160027734851490/ and seems like a reasonable feature, pretty simple too:
```js
Page.runInPageContext(() => {

    const deleteOld = CCommentThread.DeleteComment;
    CCommentThread.DeleteComment = function(...args) {
        ShowConfirmDialog("", "Are you sure you want to delete this comment?", "Delete")
            .done(() => { deleteOld.apply(this, args); });
    }

    const reportOld = CCommentThread.HideAndReport;
    CCommentThread.HideAndReport = function(...args) {
        ShowConfirmDialog("", "Are you sure you want to hide and report this comment?", "Report")
            .done(() => { reportOld.apply(this, args); });
    }
});
````

TODO avoid inserting this script on forums/discussions because it'll cause the confirmation to show up twice when deleting posts.

**Comment by Revadike** [comment]
Yes, it needs an option. I think it would be awful to have.

**Comment by MxtOUT** [comment]
How about using the classic "Don't show again" checkbox and have this option enabled by default?
I think we should use this "opt-out" approach more often since the vast amount of options makes it hard to discover new ones by checking the options page

**Comment by Revadike** [comment]
Sounds like a good idea to me.
