### ISSUE TITLE
Lowest price for F1 2021 is incorrect. Showing price for F1 2012 instead

### ISSUE THREAD

**Issue by willbo** [IsThereAnyDeal/AugmentedSteam#1223]
https://store.steampowered.com/app/1134570/F1_2021/
![Screenshot 2021-07-12 202656](https://user-images.githubusercontent.com/7140554/125344640-759bd300-e34f-11eb-8beb-2dcaf7e1191c.png)

**Comment by Revadike** [comment]
This should be reported to ITAD, not AS.

**Comment by candela97** [comment]
Please report issues with price history here https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues instead, thanks!
