### ISSUE TITLE
[FEATURE REQUEST]  Ignore Lowest Price 0.00 and show next next highest as option.

### ISSUE THREAD

**Issue by Red-Eagle-LXIX** [IsThereAnyDeal/AugmentedSteam#1232]
### Current Behavior (if any)
Current behavior is to show a lowest price of "0.00" for some items (example: "Historical low: $0.00 at Amazon 9/28/2016"

### Desired Behavior
Show the next highest value even if it was only $0.01 (although most have a reasonable gap between 0.00 and the next higher value).

### Motivation / Use Case for Changing the Behavior
Provide an option to not show historical lows of $0.00 since they can be wrong sometimes from a low advertising before purchase was allowed or a price set while product was not available.  Given that there is often a reasonable gap between the 0.00 value and the next highest value it makes the 0.00 value limited in usefulness for judging the quality level of the sale price.

EDIT for real world example from Store Front Page:
https://store.steampowered.com/app/1063730/New_World/
Game releases August 31, 2021
Current best: $39.99 at Amazon
Historical low: $0.00 at Amazon 9/28/2016
Current Price on Steam: $39.99 
Clearly the $0.00 from 9/28/2016 is a useless value that was not ever sold at that price. 

Will this mean missing some occasions a title was indeed given away for free?: Yes, hence why only asking for an option.
I might also mention it would be more intuitive when the current best matches Steam's current price that it should say Steam  (or even highlight the Steam price) not some 3rd party site that is matched to the Steam price.

**Comment by candela97** [comment]
I'm sure there was an issue about this but I can't find it... maybe it was suggested on Discord. In any case, this will need changes on the ITAD end first because right now we don't have info about "the next lowest price apart from 0".

**Comment by candela97** [comment]
I'm sure there was an issue about this but I can't find it... maybe it was suggested on Discord. In any case, this will need changes on the ITAD end first because right now we don't have info about "the lowest price that isn't 0".

**Comment by Red-Eagle-LXIX** [comment]
Thank you for taking the time to answer.
Most understandable about the backend.

As another example there was a a game this past weekend:
https://store.steampowered.com/app/962130/Grounded/
Current best: $29.99 at Steam
Historical low: $0.00 at Steam 7/30/2021

Not only is this incorrect (the game was not free, it was a free weekend and once the weekend was over you did not get to keep), but my understanding is this title has never yet been on sale.
These free weekend events which are being used as replacements for demos have started greatly polluting the system with 0.00 low prices.

**Comment by candela97** [comment]
Those issues are best reported in the ITAD Discord's #bugs channel (I've posted about the game you linked).

Seems like the whole ITAD backend is undergoing a major overhaul, so it might take a while before new ideas are considered, but I support this feature too.

**Comment by candela97** [comment]
This has been implemented along with the new ITAD.
