### ISSUE TITLE
[FEATURE REQUEST] New settings stores to redirect to history for this stores

### ISSUE THREAD

**Issue by lmiol** [IsThereAnyDeal/AugmentedSteam#1240]
### Current Behavior (if any)
when click Historical low opens this link https://isthereanydeal.com/game/caveblazers/history/

### Desired Behavior
when click Historical low opens this link https://isthereanydeal.com/game/fallback/history/?shop%5B%5D=steam&generate=Select+Stores

### Motivation / Use Case for Changing the Behavior
to be more userfriendly interface. I always come to steam and by via steam while monitoring steam price via anydeal. And i always do Stores filter to None and then select Steam only =(
always doing excess actions

**Comment by candela97** [comment]
The new ITAD works differently now. I think the site should remember yout filters instead, but seems like it doesn't at the moment. Feel free hop on to the ITAD Discord and suggest ideas in the #feedback channel!
