### ISSUE TITLE
[FEATURE REQUEST] Show game last update date 

### ISSUE THREAD

**Issue by lingsamuel** [IsThereAnyDeal/AugmentedSteam#1279]
### Current Behavior (if any)
I remember there was a last update date under the release date, but it's been gone for months. Can we bring it back?

### Desired Behavior
Display last update date under release date.

### Motivation / Use Case for Changing the Behavior
The last update date can help us find out if the game is still in active development, as there are games that are never or rarely updated after (early access) release.

**Comment by candela97** [comment]
You mean this?
![螢幕擷取畫面 2021-10-17 213012](https://user-images.githubusercontent.com/54083835/137629279-d02cda06-bedf-412c-a420-4903bdfbd84d.jpg)

I believe this is provided by SteamDB's extension. The option is under the "enhancements" section.

**Comment by Korb** [comment]
> The option is under the "enhancements" section.

Now in the "Enhancements" section, only the following items are displayed, and the date of the last update of the game is not displayed:

- Accept SSA on market, inventory, and activate key pages automatically
- Skip age check gate (sets age and birthday cookies to always pass)
- Hide "Install Steam" button in header
- Display SteamDB rating on app pages
- Remove all linkfilter links (visiting linkfilter still works)
- Display app icons on store and community pages
- Load hidden achievements and their descriptions
- Hide descriptions behind a spoiler element
- Stop images from loading on app store pages. Some developers put multiple megabytes of images in game descriptions which can take a while to load. Click on an image to load.
- Support award parameters on profile and shared file links (see explanation on GitHub)

Mozilla Firefox 116.0b8 (64-bit). Microsoft Windows 10.0.19045.3208

**Comment by candela97** [comment]
It's now under "Extra Data". Anyway, please raise issues about SteamDD's extension in their [repository](https://github.com/SteamDatabase/BrowserExtension).
