### ISSUE TITLE
[FEATURE REQUEST] Ability to hide suggested curators block

### ISSUE THREAD

**Issue by McKillemGH** [IsThereAnyDeal/AugmentedSteam#1289]
### Current Behavior (if any)
It is possible to hide most of the information blocks on the front page from the CUSTOMIZE drop down menu, suggested curators block being one of a handful of exceptions.

### Desired Behavior
A new checkbox in the CUSTOMIZE drop down menu that would allow hiding the suggested curators block oin the front page.

### Motivation / Use Case for Changing the Behavior
I have no interest in discovering curators or browsing curator content and would like to be able to hide that information block when browsing Steam.

**Comment by candela97** [comment]
We have an option for this, but the section is lazy-loaded to it gets skipped when we check the page for visible elements. This is fixable, but you will need to wait until a new version is released to get the fix.

In the meantime, I suggest using a content blocker like uBlock Origin to achieve what you want. These extensions are specifically made for hiding unwanted content, and can do a much better job than we ever can. A custom filter like `store.steampowered.com##.steam_curators_ctn` will work.
