### ISSUE TITLE
[BUG] "Your Rank" gets overwritten when you sort by anything else and set an order number for an item.

### ISSUE THREAD

**Issue by TSK-95** [IsThereAnyDeal/AugmentedSteam#1293]
### Expected Behavior
Only place that one item in the "Your Rank" to the desired rank.

### Actual Behavior
Sets everything and "destroys" the "Your Rank".

### Steps to Reproduce the Problem

  1. Select anything other than "Your Rank" sort.
  2. Set one of the items to a number, for example 1.
  3. Go back to "Your Rank" and the whole list is overwritten.

### Specifications

  - Augmented Steam Version: 2.2.0
  - Browser Version: Microsoft Edge Version 95.0.1020.40 (Official build) (64-bit)

**Comment by candela97** [comment]
hmm I guess this is because `g_Wishlist.MoveToPosition` assumes rows are in ascending order. I think we'll need to further restrict this feature to only apply when sort = order, since this was never intended to work under other sorting methods.

**Comment by idgas01** [comment]
It seems that candela97 is already aware of the bug.  But just in case, this is what I was going to type just now until I saw that someone already created an issue for it.

>[BUG] Steam Wishlist - Typing The Order_Input Number Does Not Work

>Just now, I added a game to my wishlist.  It was added to the very bottom of my wishlist.  And since I had 174 games, it appeared where the 175th game would be but showed "0".  I typed in "21" because I wanted to move it towards the top of the list.  But no matter how many times I typed the number "21", refreshed the page, or even disabled addons like my Violentmonkey userscript extension, the game would not move up to that 21st row.  It would keep resetting to "174" or "175".  So I finally tried disabling the Augmented Steam extension, and that did the job.  It moved up to the 21st row and then I enabled the extension again.

**Comment by candela97** [comment]
> > [BUG] Steam Wishlist - Typing The Order_Input Number Does Not Work
> 
> > Just now, I added a game to my wishlist.  It was added to the very bottom of my wishlist.  And since I had 174 games, it appeared where the 175th game would be but showed "0".  I typed in "21" because I wanted to move it towards the top of the list.  But no matter how many times I typed the number "21", refreshed the page, or even disabled addons like my Violentmonkey userscript extension, the game would not move up to that 21st row.  It would keep resetting to "174" or "175".  So I finally tried disabling the Augmented Steam extension, and that did the job.  It moved up to the 21st row and then I enabled the extension again.

This is actually a separate bug that I just ran into myself. I'll have a potential fix up shortly.
