### ISSUE TITLE
[FEATURE REQUEST] Reimplement fix_app_image_not_found from Enhanced Steam

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/AugmentedSteam#1294]
### Current Behavior (if any)
Sometimes app images on profile/games page is "not found" for whatever reason, happens quite often to demos.

### Desired Behavior
This feature in ES fixed them and currently still works:
https://github.com/jshackles/Enhanced_Steam/blob/7d4b116941e850a3dafd90eb5372f1921e7a6534/enhancedsteam.js#L4112

**Comment by kazerniel** [comment]
Guild Wars (ID: 29720) has had a broken image for a long time that still doesn't show up with today's Augmented Steam release.

See in my recent games list: https://steamcommunity.com/id/kazerniel/games/

**Comment by candela97** [comment]
Unfortunately this feature can't handle broken images like the one you mentioned. Looks like the app is missing quite a lot of assets: https://steamdb.info/app/29720/info/

This feature works by replacing a specific "no image available" image with one of the app's capsule images.
![螢幕擷取畫面 2021-11-07 093849](https://user-images.githubusercontent.com/54083835/140629023-660a064a-819a-4936-a00f-c7ef835df942.jpg)

For broken images like the one you mentioned, we could try replacing them on a case by case basis, but I'm not sure if it's worth maintaining such a list 😥

**Comment by kazerniel** [comment]
Yeah, understandable, thanks anyway 👍

**Comment by candela97** [comment]
Looks like Steam did some tinkering and this is no longer an issue for most demos 👍
