### ISSUE TITLE
[FEATURE REQUEST] "Ctrl + Enter" = "Save" note

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1299]
### Current Behavior (if any)
In note editing mode, pressing Ctrl + Enter does nothing.

### Desired Behavior
The result is the same as pressing the "Save" on-screen button.

### Motivation / Use Case for Changing the Behavior
For Augmented Steam users who want to make the most of their keyboard to speed up their computing experience, this combination will save you time.

**Comment by MxtOUT** [comment]
Yesterday I actually merged #1291 which saves the note when you hit Enter.
New lines can be achieved with Shift + Enter.

This will be part of the next release

**Comment by Korb** [comment]
@MxtOUT, I did a little research on which applications use which keyboard shortcut to create a new line instead of ending the edit when pressing Enter:

## `Shift` + `Enter`
Augmented Steam
ChatGPT
Discord
Facebook Messenger
Google Messages
Google Voice
Microsoft Teams
Phone Link
PoeAI
Rainbow
Skype for Web
Slack

## `Ctrl` + `Enter`
Google Messages
Telegram

## `Alt` + `Enter`
Excel

Thank you for implementing the option that is most common, and not the one I suggested.
