### ISSUE TITLE
[FEATURE REQUEST] Confirmation of closing the note editing window when pressing the "Esc" key on the keyboard

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1300]
### Current Behavior (if any)
When you press the "Esc" key on the keyboard, the note editing window closes without warning, all changes are discarded.

### Desired Behavior
When you press Esc and there are changes made, a closing confirmation appears with the ability to confirm the cancellation of the changes, or return to editing.

### Motivation / Use Case for Changing the Behavior
Several times, along with closing the context menu of the browser with the Esc key, I also closed the open note editing window, losing all changes. If there was an opportunity to enable receipt of confirmations, I would use it.

**Comment by candela97** [comment]
How about adding auto save/reload funtionality that will kick in if for any reason you failed to save the note after typing stuff? `sessionStorage` should be a good candidate for this.
