### ISSUE TITLE
[BUG] Unable to disable "Search IsThereAnyDeal for"

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1307]
### Expected Behavior
In the extension' settings, when I click on the "Context Menu" / "Search IsThereAnyDeal for '..." "checkbox, the checkbox should disappear, and the corresponding context menu item on the web pages should disappear.

### Actual Behavior
(A checkmark is displayed in the checkbox) When I try to disable the item at the bottom of the add-on settings page, a blue bar with animation and the text "Saving ..." appears. The line does not disappear, animation and caption are displayed until the settings page is manually reloaded. The item in the context menu is still displayed.

![2021-11-11_08-35-48](https://user-images.githubusercontent.com/3509797/141243439-c90ee34e-3bc8-46f7-8609-ebb82c1f8f51.png)

### Specifications
  - Augmented Steam Version: 2.2.1
  - Browser Version: Mozilla Firefox 95.0b5 (64-bit)

**Comment by MxtOUT** [comment]
Could you take a look at your browser console (F12) and report any errors?

**Comment by Korb** [comment]
In a Mozilla Firefox 94.0.1 (64-bit)  on another computer, the same error.

```
Error: Type error for parameter permissions (Error processing permissions.0: Value "contextMenus" must either: must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["webNavigation"], or be one of ["nativeMessaging"]) for permissions.remove.
    remove Permissions.js:60
    removeOption Permissions.js:97
    x options.js:221
    j options.js:265
    init options.js:378
    async* options.js:386
    <anonymous> options.js:1
options.js:232:28
```
