### ISSUE TITLE
[FEATURE REQUEST] Get notification if price is historically low or equals lowest price

### ISSUE THREAD

**Issue by kaipingqi** [IsThereAnyDeal/AugmentedSteam#1309]
### Current Behavior (if any)
-
### Desired Behavior
Get an e-mail notification if game on wishlist is on historically low price or same price as lowest recorded price.

### Motivation / Use Case for Changing the Behavior
Comfort function

**Comment by MxtOUT** [comment]
This is what you use IsThereAnyDeal for
