### ISSUE TITLE
[BUG] Search results not colored

### ISSUE THREAD

**Issue by bestpika** [IsThereAnyDeal/AugmentedSteam#1310]
### Expected Behavior

Search results should be colored.

### Actual Behavior

![image](https://user-images.githubusercontent.com/5698157/143334703-59ac09d9-1dfc-47c1-b58c-1b4163f59648.png)
![image](https://user-images.githubusercontent.com/5698157/143335097-426c4926-420e-418b-bb2e-d7db30cda595.png)

### Steps to Reproduce the Problem

  1. Search anything.

### Specifications

  - Augmented Steam Version: v2.2.1
  - Browser Version: Edge 96.0.1054.34 beta 64bit

**Comment by candela97** [comment]
Looks like Steam made some changes earlier this month, you'll have to disable tagging for the time being 😥

**Comment by Korb** [comment]
@candela97, @MxtOUT, again?
![1](https://github.com/user-attachments/assets/68150472-734d-4403-9144-b09ca8d169e0)
![2](https://github.com/user-attachments/assets/57d4abc9-37d4-4b6b-8f93-d6bb81039285)
Augmented Steam 4.1.2 (September 20, 2024)
fMozilla Firefox 133.0b9 (64-bit)

**Comment by candela97** [comment]
Works on my end, even after filtering. Please log a new issue if it's still happening, the original bug was resolved long ago.
