### ISSUE TITLE
[BUG] Wolfpack prices are taking data from Wolf Pack.

### ISSUE THREAD

**Issue by Langolyers** [IsThereAnyDeal/AugmentedSteam#1311]
### Expected behavior
Current best price for Wolfpack (https://store.steampowered.com/app/490920/Wolfpack/) should show the current Steam price, as it is not on sale anywhere as of writing this. 
 
### Actual Behavior
Current best price shows Steam at 70% off at €2.99, but the actual Steam price is €29.99 with no discount. The discounted current best price is for this entry, Wolf Pack: https://store.steampowered.com/sub/418/

Similar name is causing a mix up in the data.

### Steps to Reproduce the Problem

  1. Go to Wolfpack store page: https://store.steampowered.com/app/490920/Wolfpack/
  2. Check prices.
  3. Click Current Best and get sent to Wolf Pack page.

### Specifications

  - Augmented Steam Version: 2.2.1
  - Browser Version: Firefox 94.0.2 (64-bit)

**Comment by MxtOUT** [comment]
This is an ITAD issue, report here https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/
