### ISSUE TITLE
[FEATURE REQUEST] Customer Reviews - Display As - Sort = Recent

### ISSUE THREAD

**Issue by merlin555** [IsThereAnyDeal/AugmentedSteam#1313]
Hi,

Wish me that the "Customer Reviews" the sorting of "DISPLAY AS" is adjustable.
Instead of always "Summary", I want "Recent".

Thanks !

Greetings..

 Merlin

<img width="1019" alt="Sort_NEW" src="https://user-images.githubusercontent.com/14818838/143564176-9f190577-67bb-48e4-9a94-99858f81bf9c.png">

**Comment by candela97** [comment]
Yeah we can save/load your most recent selection from local storage, can support the other options as well.

**Comment by merlin555** [comment]
Great !!
Thank you, for the fast answer..
