### ISSUE TITLE
Moving to a new laptop

### ISSUE THREAD

**Issue by markwr** [IsThereAnyDeal/AugmentedSteam#1325]
I bought a new laptop. On my old laptop, using the current version of the Firefox browser with your extension installed, I have added a "Note" (some notes are long) on a LOT of store.steampowered.com pages. I'm using your new way of storing notes because the old way was not big enough to hold all the notes total size. I need to know the following:

1. Are the notes stored locally or will they move to my new laptop via a Firefox sync function of some kind?
2. Is there a way for me to backup or export my notes to a file, such that the file could be restored or imported if I so choose?
3. Do you have any additional useful advice you'd like to impart to me on this topic?

Thank you.

**Comment by candela97** [comment]
Local database (the new way to store notes) is local to your device, and the data cannot be synced via browsers, or by using import / export from our options page.

I believe there're plans to support syncing with an ITAD account, but before then I'm afraid you'll need to trim your notes to fit into browser storage quotas before they can be synced across devices 😥

**Comment by markwr** [comment]
Thank you very much for your reply. This is a very important need (and not just to me, but for anyone getting a new computer for Christmas), so I hope you give this a high priority to be implemented as soon as possible.

For now, I'm considering moving my Firefox profile from my old laptop to my new one, and I have a question (below).

I only have one Firefox profile on my old laptop...
== about:profiles
Profile: Default
This is the profile in use and it cannot be deleted.
Default Profile	yes
Root Directory	C:\Users\Mark\AppData\Roaming\Mozilla\Firefox\Profiles\082atqin.Default-1575331692262
Local Directory	C:\Users\Mark\AppData\Local\Mozilla\Firefox\Profiles\082atqin.Default-1575331692262

== I'd use this Mozilla article to move my Firefox profile to my new laptop:
"Back up and restore information in Firefox profiles"
https://support.mozilla.org/en-US/kb/back-and-restore-information-firefox-profiles

== My question for you is:

Would your local "notes" database be stored in either the Root Directory or Local Directory shown above (I read somewhere else that some of the things included in the Firefox profile folder are: DOM storage, Containers, Stored session)?

Thanks.

**Comment by candela97** [comment]
According to https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_finding-your-profile-without-opening-firefox, it should be Root Directory. Seems like extensions are stored as well, but I have no idea if IndexedDB data can be transferred. Let us know how it went!

**Comment by candela97** [comment]
Closing as resolved. I created #1465 to track adding more convenient sync options.

**Comment by markwr** [comment]
> Closing as resolved. I created #1465 to track adding more convenient sync options.

I am truly sorry that I forgot to reply to your request to let you know how it went. I did find the folder (for me) that held the steam notes database, and I created a batch file for when I want to occasionally back it up:

@echo off
echo.
echo D:\-\Bac Ffe Steam_notes.BAT
echo.
echo This will backup the Firefox "Augmented Steam" extension files including
echo the STEAM NOTES database named: "1011854226amuagemtesn+tde.sqlite"
echo.
echo Will keep the last 10 backups in folder "D:\Firefox_augmentedsteam_notes\"
echo.
echo ## CLOSE FIREFOX FIRST ##
echo.
pause
D:
md\Firefox_augmentedsteam_notes
cd\Firefox_augmentedsteam_notes
del Steam_notes9.7z
ren Steam_notes8.7z Steam_notes9.7z
ren Steam_notes7.7z Steam_notes8.7z
ren Steam_notes6.7z Steam_notes7.7z
ren Steam_notes5.7z Steam_notes6.7z
ren Steam_notes4.7z Steam_notes5.7z
ren Steam_notes3.7z Steam_notes4.7z
ren Steam_notes2.7z Steam_notes3.7z
ren Steam_notes1.7z Steam_notes2.7z
ren Steam_notes.7z  Steam_notes1.7z
C:
cd\

rem echo C:\Users\Mark\AppData\Roaming\Mozilla\Firefox\Profiles\082atqin.Default-1575331692262\storage\default\moz-extension+++a01732e5-5bde-431a-9341-0768d03bc917\*
echo C:\Users\mark_\AppData\Roaming\Mozilla\Firefox\Profiles\hwwgmzg2.default-release\storage\default\moz-extension+++a01732e5-5bde-431a-9341-0768d03bc917\*

rem -mx=5 (Normal_compress) [0=none 1=fastest 3=fast 5=normal 7=max 9=ultra] (anything beyond 5 makes little difference)

rem D:\Pr\7-Zip\7z.exe a -mx=5 d:Steam_notes.7z ".\Users\Mark\AppData\Roaming\Mozilla\Firefox\Profiles\082atqin.Default-1575331692262\storage\default\moz-extension+++a01732e5-5bde-431a-9341-0768d03bc917\*"

D:\Pr\7-Zip\7z.exe a -mx=5 d:Steam_notes.7z ".\Users\mark_\AppData\Roaming\Mozilla\Firefox\Profiles\hwwgmzg2.default-release\storage\default\moz-extension+++a01732e5-5bde-431a-9341-0768d03bc917\*"

echo.
dir d:
echo.
pause

[Bac Ffe Steam_notes.bat.txt](https://github.com/IsThereAnyDeal/AugmentedSteam/files/9409456/Bac.Ffe.Steam_notes.bat.txt)
