### ISSUE TITLE
[FEATURE REQUEST] Add a separate checkbox to hide the "More like this" block

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1326]
### Current Behavior (if any)
When the Augmented Steam 2.2.1 add-on is enabled in Mozilla Firefox 96.0b2 (64-bit), the "More like this" block disappears from the game pages on Steam.

### Desired Behavior
In the browser add-on settings, there is a separate item that controls hiding or displaying the "More like this" block on Steam pages.

### Motivation / Use Case for Changing the Behavior
Perhaps this setting is already in the add-ons. But, since the field on Steam is called "More like this", the user is looking for this text on the settings page. Which is now explicitly absent in the settings.

**Comment by candela97** [comment]
The extention does not hide this section by itself, my guess is that you hid it through the customizer:
![螢幕擷取畫面 2021-12-12 005902](https://user-images.githubusercontent.com/54083835/145685094-d349a3bf-bcb7-4c1d-822f-2088df370f15.jpg)

**Comment by Korb** [comment]
@candela97, thanks, I forgot about this dropdown!
