### ISSUE TITLE
[BUG] Current Best price is not shown correctly

### ISSUE THREAD

**Issue by Kallan007** [IsThereAnyDeal/AugmentedSteam#1341]
### Expected Behavior
Show the lowest price on Steam's website.

### Actual Behavior
The lowest price is not always shown, making the addon useless.

### Steps to Reproduce the Problem

  1. View the DLC Total War: WARHAMMER II - The Queen & The Crone on Steam (https://store.steampowered.com/app/779880/Total_War_WARHAMMER_II__The_Queen__The_Crone/).
  2. Current best price listed is $4.50 at 2game (https://2game.com/en-us/total-wartm-warhammerr-ii-the-queen-the-crone). That is not the lowest price available for that DLC. 
  3. Currently the lowest price for the DLC is $3.98 at GameBillet (https://isthereanydeal.com/game/totalwarwarhammeriiqueenandcrone/info/). 
  4. The correct lowest price is shown on the IsThereAnyDeal website for the DLC but not on Steam.
  4. Another issue is that the price of the DLC on 2game is $5.00, not $4.50 as shown on Steam even using the suggested voucher (COMMUNITY).
  5. One other thing, I noticed that the IsThereAnyDeal website lists prices for several websites but the 2game website is not one of them. I am using the link on Steam to the IsThereAnyDeal website.
  6. All these are not isolated issues. I have seen them all occur before I have just never reported them. 

### Specifications

  - Augmented Steam Version: 2.2.1
  - Browser Version: Microsoft Edge Version 96.0.1054.62 (Official build) (64-bit)
  
![AugmentedSteam showing incorrect price on steam 1](https://user-images.githubusercontent.com/80496992/147381956-fb42db90-6471-4fe7-96d0-5c13d352a559.png)
![AugmentedSteam showing incorrect price on steam 2](https://user-images.githubusercontent.com/80496992/147381963-2caaa4ab-4bf2-437b-995c-2e12050696ba.png)
![AugmentedSteam showing incorrect price on steam 3](https://user-images.githubusercontent.com/80496992/147381965-b37d9c27-d33e-4f96-9c54-b792ed5d7a63.png)
![AugmentedSteam showing incorrect price on steam 4](https://user-images.githubusercontent.com/80496992/147382076-65bb831d-7ef7-4b37-a1fb-eb3b82d72b32.png)

**Comment by candela97** [comment]
This is an ITAD issue with duplicate entries for the same DLC https://isthereanydeal.com/search/?q=The+Queen+%26+The+Crone, causing the API to return incomplete info. I've posted about this here https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2463.
