### ISSUE TITLE
[BUG] Elements misplaced

### ISSUE THREAD

**Issue by bestpika** [IsThereAnyDeal/AugmentedSteam#1346]
### Steps to Reproduce the Problem

When used with STEAMDB extension, the position of the elements in the picture will be misplaced.

1. Turn on this option for STEAMDB extension.
![image](https://user-images.githubusercontent.com/5698157/147429304-010d5bf1-c1fb-4637-8bea-0e2726d32940.png)
2. Go to <https://store.steampowered.com/app/1091500/>
![image](https://user-images.githubusercontent.com/5698157/147429585-4b933ffb-fbe3-433c-9931-6fc56415e3e9.png)
![image](https://user-images.githubusercontent.com/5698157/147429492-ea965535-34e8-4050-b134-421e6e3e7dff.png)

### Specifications

- Augmented Steam Version: v2.2.1
- SteamDB Version: v3.0.0
- Browser Version: Microsoft Edge	97.0.1072.41 (官方組建) beta (64 位元)

**Comment by candela97** [comment]
Hmm...this is a tricky one. We determine developer/publisher fields simply by the order they are displayed, but I suppose if this is an issue, developer fields have an additional `id` attribute, or we can look from the bottom instead. Though these changes add unnecessary complexity, and this feature has been broken by Steam changes many times already.

**Comment by bestpika** [comment]
Why not check the URL of ".glance_ctn_responsive_left .dev_row a" for "href" directly?
![image](https://user-images.githubusercontent.com/5698157/147632675-aaaa53de-2089-4350-9421-46f1abec7352.png)
The URLs in this element will contain "developer" or "publisher" strings respectively, so you can tell the difference, right?

**Comment by bestpika** [comment]
Oh no, I found that some of them are only "curator".
