### ISSUE TITLE
[FEATURE REQUEST] Codeblock Highlighting and other enhancements

### ISSUE THREAD

**Issue by GreenMan36** [IsThereAnyDeal/AugmentedSteam#1347]
### Current Behavior (if any)
`<div class="bb_code"> code </div>`
Is used for codeblocks on Steam, however, the codeblocks have 0 highlighting??
[Large Image](https://i.imgur.com/DjK9tFW.png) They aren't that readable because of it.
There's also no line numbers, its not a text box that can be scrolled, etc. Its quite basic.
Its far from a codeblock, its more of a `monofont` block than anything code like.

### Desired Behavior
Something more like this: [BetterCodeblocks for Discord](https://github.com/xiBread/bd-contributions/tree/1be95b118ae78f3f46941df24c68403de9533e86/BetterCodeblocks) but then for Steam would be amazing.
Even with [basic highlighting](https://i.imgur.com/11tbbPl.png) code would be a lot more readable.
And even better would be if it had a resizable and scroll-able textbox, or by default collapsed to 10 lines with a expand button might be better?

You would need to find the language, possibly by having a list of unique things a language does and have the highlighting change by default to what it detects. Then having the option to change it in case its not correct, dropdown maybe? Small searchbox?

### Motivation / Use Case for Changing the Behavior
It would greatly improve the lackluster use of codeblocks on the site.
But its probably more of a hassle than what its worth.

**Comment by GreenMan36** [comment]
Hope there's parts of BetterCodeblocks that can be used for this to safe on work.
Its just JS made to change behavior of the Discord client, should also work on web just fine.

**Comment by MxtOUT** [comment]
I'm sorry, but as you said this is not something I consider worth it to have integrated in AS.
Also I've never encountered code samples on Steam
