### ISSUE TITLE
[FEATURE REQUEST] Add "Customize" / "Awards"

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1350]
### Current Behavior (if any)
On the page with the description of the game, the following items are present in the drop-down list of checkboxes for selecting blocks to display:

> Customize
> Select the sections you would like to see on this page
> 
> - Recent Events & Announcements
> - Reviews
> - About this game
> - Performance survey
> - Player data
> - Current players
> - System requirements
> - Legal Information
> - More like this
> - What curators say
> - Customer reviews

### Desired Behavior
Add "Awards" item to hide the block with the awards received by the game.

### Motivation / Use Case for Changing the Behavior
Too often I have found that awards go to the best games in a limited set, and if there are no good games among them, the award is still given. Thus, the award-winning games are "the best of a number of submissions" and not "matching the level of awards on a list of specific criteria." In short, "award-winning games are not necessarily great games. They can be downright bad games." And, therefore, the very fact of the award when choosing a game is insignificant, and trusting this list is like buying all games with a review rating above 95% (stupid).

**Comment by candela97** [comment]
For hiding unwanted stuff, I strongly recommend using content blockers like uBlock Origin. A custom filter like `store.steampowered.com###awardsTable` will work for this case.

**Comment by Korb** [comment]
@candela97, you are absolutely correct, this concealment rule does work. The point is that I only use custom filters for absolutely harmful content - ads, "similar products" blocks, promotional items, carousel, and warnings about collecting user information. My friends and I exchange our collections of custom filters, thereby complementing the subscription filters. There are quite a few of them, about 8 thousand.

Game rewards are not necessarily objectionable content. But there is no way in Adblock Plus to create custom filter groups to separate filters for general use and filters just for me.
