### ISSUE TITLE
[BUG] Version 2.3.0 collapses the game list, hiding them all from search

### ISSUE THREAD

**Issue by Lenmaer67** [IsThereAnyDeal/AugmentedSteam#1359]
### Expected Behavior
[https://i.imgur.com/9dsv3dc.png](url)

### Actual Behavior
[https://i.imgur.com/x1IMlii.jpg](url)

### Steps to Reproduce the Problem

  1. Any browsing by tag will produce this bug
  2. Exemple: https://store.steampowered.com/search/?sort_by=Released_DESC&tags=122&filter=comingsoon
  3. 

### Specifications

  - Augmented Steam Version: 2.3.0
  - Browser Version: Opera 82.0.4227.43

**Comment by DoLLo73** [comment]
"Same" problem here with Chrome 96 and Edge 97.
Working great with Firefox 95.

**Comment by MxtOUT** [comment]
> Any browsing by tag will produce this bug

The problem is actually that you're on the "Upcoming" page where most titles don't have reviews yet.
The fix that introduced this problem was always filtering by review score, no matter if you had changed the slider or not.

> Working great with Firefox 95.

Yes, FF hasn't been updated yet

**Comment by Lenmaer67** [comment]
Even on normal pages it's happening https://store.steampowered.com/search/?sort_by=Released_DESC&tags=122

**Comment by MxtOUT** [comment]
Because you're sorting by release date

**Comment by DoLLo73** [comment]
Not in my case.
[Check this ](https://store.steampowered.com/search/?developer=Debonosu%20Works)
With the 2.3.0 some results are missing on Chrome/Edge. No problem without or with Firefox.
