### ISSUE TITLE
[BUG] Latest AugmentedSteam version 2.3.1 has stopped working on Waterfox Classic

### ISSUE THREAD

**Issue by Killogy** [IsThereAnyDeal/AugmentedSteam#1367]
### Expected Behavior

To Work properly like the previous version 2.2.1

### Actual Behavior

AugmentedSteam is not activated anymore so there is nothing related to AugmentedSteam.

### Steps to Reproduce the Problem

  1. Run Waterfox Classic 
  2. Visit https://store.steampowered.com or any game store page or user profile

### Specifications

  - Augmented Steam Version: 2.3.1
  - Browser Version: Waterfox Classic 2021.11 (64-bit)

**Comment by candela97** [comment]
I think this is due to bumping the minimum supported FF version to 84.

**Comment by Killogy** [comment]
The minimum supported FF version is the same on 2.3.1 and 2.2.1 "strict_min_version": "84.0" so I think some changes on latest version includes some instructions that Waterfox Classic can´t performing.

**Comment by MxtOUT** [comment]
Waterfox Classic definitely shouldn't be working anymore, it's way too outdated and we don't support it
