### ISSUE TITLE
[FEATURE REQUEST] Ability to disable all the market changes

### ISSUE THREAD

**Issue by pacopepepipo** [IsThereAnyDeal/AugmentedSteam#1369]
### Current Behavior (if any)
Currently, AugmentedSteam, do some changes on the steam market page

https://steamcommunity.com/market/

where it makes a triangle appear on the top op the page to order items, and maybe some other optimizations.

### Desired Behavior
An option to completely disable all the market optimizations or changes in the extension

### Motivation / Use Case for Changing the Behavior

Those changes, cannot be disabled on the extension as there is no way to do it, nor any option to do it, and makes using the extension with other extensions or scripts that are specifically designed to the market, break everything, forcing the user to disable AugmentedSteam every time you want to load the market so it doesn't fight or make changes that other extensions/scripts are also doing it, making it a mess between both of them.

**Comment by candela97** [comment]
So the main problem is the sorting feature for your active listings? There's an option to disable showing lowest prices already.

**Comment by pacopepepipo** [comment]
Yep, as I have a huge script with multiple features like that one, they clash between them and I need to disable augmented steam because of it as the other script is just a market one without config features and have dozens of small things to trade, so it's a must for the market.
