### ISSUE TITLE
[BUG] The extension does not retain the settings set in the Web Catalog application based on Chromium (https://webcatalog.io/webcatalog/)

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [IsThereAnyDeal/AugmentedSteam#1372]
### Expected Behavior

Importing the settings should theoretically save them. It does not happen and therefore I cannot configure anything!

### Actual Behavior

I cannot change anything, and therefore I cannot use the extension

### Steps to Reproduce the Problem

  1. Launch WebCatalog
  2. Create an app for Steam DB (Database) or Steam
  3. Install the extension and try to change the setttings from the menu on steam webpage (as figure below ↓)
  
  ![image](https://user-images.githubusercontent.com/77741077/150166959-44dbd63c-8d5d-4704-9983-203beca36da2.png)

### Specifications

  - Augmented Steam Version: 2.3.1
  - "Browser Version": 
      (WebCatalog, x64) Version 21.12
      -- Neutron: 21.12.0
      --- Electron: 16.0.6
      ---- Node: 16.9.1
      ----- Chromium: 96.0.4664.110
      ------ OS: Windows 10 Pro N 21H2 (19044.1466)
      
I leave here below the link to the ticket on Webcatalog's github I opened a few minutes ago → https://github.com/webcatalog/webcatalog-app/issues/1613

**Comment by MxtOUT** [comment]
I'd just guess that WebCatalog doesn't support web extensions, because the link that you try to open when you click on "Options" uses the "chrome-extension://" protocol.
This is not something we can fix and I doubt that it's something that they will implement
