### ISSUE TITLE
[BUG] Roll game mistaken for ROLL!

### ISSUE THREAD

**Issue by mibac138** [IsThereAnyDeal/AugmentedSteam#1373]
### Steps to Reproduce the Problem

  1. Open [Roll](https://store.steampowered.com/app/1585910/Roll/) on steam
  2. See `Current best: 3.57zł at Steam`. Click on `at Steam`
  3. Store page for a _different_ game opens: [ROLL!](https://store.steampowered.com/app/938280/ROLL/)

### Specifications

  - Augmented Steam Version: 2.3.1
  - Browser Version: Chrome 97

**Comment by candela97** [comment]
ITAD issues should go here https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues. There's an open issue with this game already https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2521.
