### ISSUE TITLE
[BUG] Incorrect ITAD pricing (A$)

### ISSUE THREAD

**Issue by infekSK** [IsThereAnyDeal/AugmentedSteam#1374]
### Expected Behavior

ITAD extension should be comparing storefronts and suggesting the cheapest price in the selected currency

### Actual Behavior

ITAD extension is incorrectly showing the cheapest price (in AUD from my pov), it's showing the USD price as if it's the AUD price

![image](https://user-images.githubusercontent.com/15379158/150468740-053ee4bf-b7fc-49ff-9825-27430aa061fc.png)
![image](https://user-images.githubusercontent.com/15379158/150468775-ce43e4ca-26ac-4883-a412-d91464183281.png)

### Specifications

  - Augmented Steam Version: 2.3.1
  - Browser Version: FF 96.0.1

**Comment by MxtOUT** [comment]
This is an IsThereAnyDeal issue and should be reported at the corresponding [repository](https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/)
