### ISSUE TITLE
[BUG] Uncaught (in promise) Error: SyntaxError: Unexpected token < in JSON

### ISSUE THREAD

**Issue by C-O-S** [IsThereAnyDeal/AugmentedSteam#1382]
### Expected Behavior

Being able to synchronize library and wishlist successfully without errors occurring. 

### Actual Behavior

I connect to my steam account, but whenever I check Library or Wishlist to periodically import data from the account, the status indicator bubble throws the error below:

![1](https://user-images.githubusercontent.com/33273295/153602791-2fd24a8c-f539-412e-a739-4ef2f7ff829d.png)

The console displays the following with Library and Wishlist checked:
```
DevTools failed to load source map: Could not load content for chrome-extension://hokifickgkhplphjiodbggjmoafhignh/editor/config.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hokifickgkhplphjiodbggjmoafhignh/editor/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://dnpjkgmekpilchdgolfifobohlohlioc/js/store/frontpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
frontpage.js:1  Augmented Steam v2.3.1  https://augmentedsteam.com
browser-polyfill.js:1 
        
       Uncaught (in promise) Error: SyntaxError: Unexpected token < in JSON at position 0
    at d (browser-polyfill.js:1:9056)
d @ browser-polyfill.js:1
await in d (async)
action @ frontpage.js:1
create @ frontpage.js:1
await in create (async)
run @ frontpage.js:1
await in run (async)
(anonymous) @ frontpage.js:1
(anonymous) @ frontpage.js:1
frontpage.js:1 Feature loading complete, 5 successfully loaded, 0 failed to load, 0 didn't load due to dependency errors

```
With them unchecked and account still linked:
```
DevTools failed to load source map: Could not load content for chrome-extension://hokifickgkhplphjiodbggjmoafhignh/editor/config.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hokifickgkhplphjiodbggjmoafhignh/editor/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://dnpjkgmekpilchdgolfifobohlohlioc/js/store/frontpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
frontpage.js:1  Augmented Steam v2.3.1  https://augmentedsteam.com
frontpage.js:1 Feature loading complete, 5 successfully loaded, 0 failed to load, 0 didn't load due to dependency errors
```

I have a LARGE steam library (and inventory) and have had issues like this in the past where I have had to limit or otherwise slow down the page requests from steam to have syncs complete without erroring out.

Of note: I also have a similar issue on the isthereanydeals website, where my wishlist will sync -- however, my owned games will not even though everything is marked completely open to the public.

### Steps to Reproduce the Problem

  1.  Link addon to my profile ( http://steamcommunity.com/profiles/76561197973009892 )
  2.  Enable periodically import Library or Wishlist
  3.  Refresh Steam Page.

### Specifications

  - Augmented Steam Version:  2.3.1
  - Browser Version:   Microsoft Edge Version 98.0.1108.43 (Official build) (64-bit)

**Comment by candela97** [comment]
Please file a new issue if there're still problems with the new ITAD, thanks!
