### ISSUE TITLE
[BUG] Badge page's Current Lowest Price links are missing "753/"

### ISSUE THREAD

**Issue by jfjx** [IsThereAnyDeal/AugmentedSteam#1383]
### Expected Behavior
Clicking any Current Lowest Price link in a badge's page (for example: https://steamcommunity.com/my/gamecards/601220) leads to the item's individual market page. (example: https://steamcommunity.com/market/listings/753/601220-Door)

### Actual Behavior
After the recent update, the link is missing "753/" (example: https://steamcommunity.com/market/listings/601220-Door), ending up going to market main page (https://steamcommunity.com/market/)
![unknown](https://user-images.githubusercontent.com/12727188/153710950-76d03f53-d4c5-4766-a826-e7ebe9cae380.png)

### Steps to Reproduce the Problem

  1. Go to any badge's individual page
  2. Click any Current Lowest Price link

### Specifications

  - Augmented Steam Version: 2.3.1
  - Browser Version: Google Chrome Version 98.0.4758.82 (Official Build) (64-bit)

**Comment by candela97** [comment]
This should be fixed on the server side already.

**Comment by MxtOUT** [comment]
I also can't reproduce this, closing
