### ISSUE TITLE
[BUG] How long tp beat sections link captions formatting error

### ISSUE THREAD

**Issue by hgdagon** [IsThereAnyDeal/AugmentedSteam#1394]
### Expected Behavior
Captions for link should be `More Information` and `Submit Your Time`

### Actual Behavior
Captions are `More Information">` and `Submit Your Time">`

### Steps to Reproduce the Problem

  1. Open any game page
  2. Look at How long to beat section

### Specifications

  - Augmented Steam Version: 2.3.1
  - Browser Version: Firefox Developer 99.0b1
![augstm](https://user-images.githubusercontent.com/15173076/157526156-fe78f7ae-8dab-4b24-ab2f-816a4b66ed8f.png)

**Comment by candela97** [comment]
This'll be fixed by #1385.

**Comment by MxtOUT** [comment]
And merged
