### ISSUE TITLE
[FEATURE REQUEST] Custom Funds Allow Amounts Below $5

### ISSUE THREAD

**Issue by BeansOnButter** [IsThereAnyDeal/AugmentedSteam#1397]
### Current Behavior (if any)
Custom Funds only give amounts above $5

### Desired Behavior
You can select any amount, including amounts below $5, which prevent extra money being left in the account after a purchase like a trading card on the market, because a card can't be used

### Motivation / Use Case for Changing the Behavior
It's a feature that Valve, for some reason, chose not to give, this is a very necessary option for people when it comes to online stores, it'd also protect some part of your account against hackers, because if you have any extra money left in your account then hackers could waste that

**Comment by candela97** [comment]
Last I checked, you'll get a purchase error when adding amounts under the minimum, so this isn't possible.

**Comment by BeansOnButter** [comment]
> Last I checked, you'll get a purchase error when adding amounts under the minimum, so this isn't possible.

But why though?

**Comment by candela97** [comment]
Steam simply rejects the purchase if it's lower than the minimum (I guess there's an upper limit as well), so we won't be able to get around that.

**Comment by BeansOnButter** [comment]
> Steam simply rejects the purchase if it's lower than the minimum (I guess there's an upper limit as well), so we won't be able to get around that.

*sigh*... Valve... why? Why is this not a feature
