### ISSUE TITLE
[FEATURE REQUEST] Ban List

### ISSUE THREAD

**Issue by BeansOnButter** [IsThereAnyDeal/AugmentedSteam#1398]
### Current Behavior (if any)
Only way of knowing what bans you have is to dig through your community messages, which become crowded when you report comments and posts
### Desired Behavior
A straight-up list detailing all your bans, past and active, temporary, permanent and VAC, including warnings as well as the number of total bans/warnings you have in that forum, you can also choose to only show active bans, or all bans as well as different types of bans
If it's an active ban, it says [ACTIVE] next to it
If it's an expired ban, it will say [EXPIRED]
You can also choose to only show bans in a certain forum

If a response came with the ban, you'll be able to click a link to take you straight to the message/warning
### Motivation / Use Case for Changing the Behavior
Tedious process for finding out what bans you have, no way to accurately keep track of them or pair them up with the response

**Comment by candela97** [comment]
We could parse community messages to get discussion bans/warnings for sure, but it may be tricky since they are localized. I don't know if there's a way to get a list of one's VAC and game bans though. In any case, in order to test this properly I'll need to get a few bans myself, and I kinda don't want that 😆.

**Comment by BeansOnButter** [comment]
> We could parse community messages to get discussion bans/warnings for sure, but it may be tricky since they are localized. I don't know if there's a way to get a list of one's VAC and game bans though. In any case, in order to test this properly I'll need to get a few bans myself, and I kinda don't want that 😆.

You could create another account and ask moderators "Ban me, it's for an update to an extension that's open source". I think somebody would, there are a lot of forums with their own moderators, plus you won't feel guilty because there's nothing to feel guilty about

At first you can ask for a permanent ban in 2 seperate forums so you don't start annoying mods with constant requests, then when you get to temporary bans just copy the code and alter the aspects which make up the category, ask for a 3 month ban, then test the changes

And if that doesn't work... well, you know what Plan B is

**Comment by MxtOUT** [comment]
This is too much effort for what it gives, sorry
