### ISSUE TITLE
[FEATURE REQUEST] Add G2A for searchable markets

### ISSUE THREAD

**Issue by Twizzer** [IsThereAnyDeal/AugmentedSteam#1400]
Currently G2A is not a searchable market, we should absolutely list it on this plugin

**Comment by candela97** [comment]
Suggestions for new stores should be made to ITAD directly, see available options on  https://isthereanydeal.com/#/page:web/contact. But fyi ITAD only lists authorized sellers, so I doubt G2A will be added.

**Comment by MxtOUT** [comment]
Yes, won't be added
