### ISSUE TITLE
What's The Difference Between "Quick Sell" And "Insta-Sell"?

### ISSUE THREAD

**Issue by BeansOnButter** [IsThereAnyDeal/AugmentedSteam#1402]
Aren't they both.. fast? Why are the prices different?

**Comment by candela97** [comment]
Instant Sell sells the item at the price of the highest current buy order, which usually guarantees an instant match; Quick Sell sells the item at the price of the lowest current sell order ± a user-defined offset.

For questions like this you are welcome to join the ITAD Discord, where you'll get a faster response!

**Comment by BeansOnButter** [comment]
> Instant Sell sells the item at the price of the highest current buy order, which usually guarantees an instant match; Quick Sell sells the item at the price of the lowest current sell order ± a user-defined offset.
> 
> For questions like this you are welcome to join the ITAD Discord, where you'll get a faster response!

> Instant Sell sells the item at the price of the highest current buy order, which usually guarantees an instant match; Quick Sell sells the item at the price of the lowest current sell order ± a user-defined offset.
> 
> For questions like this you are welcome to join the ITAD Discord, where you'll get a faster response!

1: Isn't that against the Steam Rules? I think a rule states you can't use things that "snipe" prices from the Market
2: Why isn't one of the options always available? Sometimes I only see one

**Comment by MxtOUT** [comment]
> 1: Isn't that against the Steam Rules? I think a rule states you can't use things that "snipe" prices from the Market

I don't know the rule, but I think sniping is a term that applies to buying items and not selling them.

Anyway, I see this as resolved, closing.
