### ISSUE TITLE
[BUG] Wanderer VR page displays current and historical low prices of The Wanderer

### ISSUE THREAD

**Issue by pacsuta** [IsThereAnyDeal/AugmentedSteam#1404]
On the [Wanderer (VR game) store page](https://store.steampowered.com/app/1599560/Wanderer/), the prices and IsThereAnyDeal links pointing to pages for [The Wanderer](https://store.steampowered.com/app/530860/The_Wanderer/) are being displayed instead.

**Comment by MxtOUT** [comment]
This is an IsThereAnyDeal issue and should be reported at the corresponding [repository](https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/)
