### ISSUE TITLE
[FEATURE REQUEST] "Add free license" button on F2P game store pages

### ISSUE THREAD

**Issue by MateusAuri** [IsThereAnyDeal/AugmentedSteam#1406]
### Current Behavior (if any)
Currently, AFAIK, to add a F2P game license, you need to either:
- Click "Play Game" (which opens the Steam client and an installation prompt); or
- Go to the game's SteamDB page, find its corresponding "Free on demand" package, click "Add free license" (if you have the SteamDB extension); or
- Use some sort of script or command tool such as ArchiSteamFarm (which still requires you to look up the package ID).

### Desired Behavior
- Have an "Add free license" button in the game's store page (maybe under or above the default "Play Game" button);
- Just like the one already implemented on SteamDB... when you click it, it activates the "Free on demand" license for that game, without prompting the client app to start up and try to install the game right away.

### Motivation / Use Case for Changing the Behavior
For when you want to quickly add a F2P game to your library from a browser, but you don't want to start the Steam client or get prompted to install the game yet.
The SteamDB implementation is almost perfect, except that it requires you to navigate to a corresponding package page to find the button. It would be way more convenient (if possible at all) to have it on the game store page itself, for a fast 1-click activation.

You can find plenty of "Free on demand" packages [here](https://steamdb.info/freepackages/) to test this.

**Comment by candela97** [comment]
I guess a dedicated button wouldn't hurt. Looks like it's done by sending a request to `https://store.steampowered.com/checkout/addfreelicense/`, although I can see SteamDB also handles the case for free bundles? I wonder what those are about.

**Comment by candela97** [comment]
Looks like Steam just added this feature:
![123133](https://user-images.githubusercontent.com/54083835/185462586-08cb950b-59c7-4597-b827-0bd1ed4f8f9b.jpg)

I've checked and any sort of free package like f2p games, demos and free weekends are all supported, so I guess we can call this resolved?

**Comment by MateusAuri** [comment]
> Looks like Steam just added this feature: ![123133](https://user-images.githubusercontent.com/54083835/185462586-08cb950b-59c7-4597-b827-0bd1ed4f8f9b.jpg)
> 
> I've checked and any sort of free package like f2p games, demos and free weekends are all supported, so I guess we can call this resolved?

Ooh, that's good!
I tested it and it seems to do exactly what I wanted, so I think yeah, it's resolved!
