### ISSUE TITLE
[FEATURE REQUEST] Add Option to use new ITAD site

### ISSUE THREAD

**Issue by itshypax** [IsThereAnyDeal/AugmentedSteam#1411]
### Current Behavior (if any)
None

### Desired Behavior
Add the ability to set an option where every itad link is opened with new.isthereanydeal.com, except only isthereanydeal.com.

### Motivation / Use Case for Changing the Behavior
I really like the newer version and think it doesn't only look better, but gives me every info I want in an easier way. So, I would love to be able to just use the new site without always having to edit the link.

**Comment by candela97** [comment]
I guess a dedicated button wouldn't hurt. Looks like it's done by sending a request to `https://store.steampowered.com/checkout/addfreelicense/`, although I can see SteamDB also handles the case for free bundles? I wonder what those are about.

**Comment by candela97** [comment]
All links should be directed to the new site now!
