### ISSUE TITLE
[Localization] Question

### ISSUE THREAD

**Issue by Tiagoquix** [IsThereAnyDeal/AugmentedSteam#1414]
![image](https://user-images.githubusercontent.com/30274161/166245103-011214e6-ae7b-4698-9fe6-152e1ad22b2a.png)
I was using the POEditor when I saw this.

The correct in href link is to use single quotes or double quotes? `'` or `"`?

Thanks in advance.

**Comment by candela97** [comment]
1. Doesn't matter, so long as the opening and ending quotes are the same. FYI only the third entry in your screenshot is currenty in use.
2. Feel free to update it. You'll have to edit en.json and open a PR here.

**Comment by candela97** [comment]
No, the English source text edited here will be synced with POEditor, not the other way round.
