### ISSUE TITLE
Game Matching on Name Bug

### ISSUE THREAD

**Issue by CandiceJoy** [IsThereAnyDeal/AugmentedSteam#1429]
There's a game on Steam called Offside.  I don't own it.  AugmentedSteam says I do.  Doing some more digging, there's two games on Steam called "Offside" and I own the other one.  Can you do the checks on game ID instead of name?

**Comment by candela97** [comment]
This is an issue with ITAD and should go here: https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues.
I've filed this on Discord: https://discord.com/channels/301903094080339968/532283798914859030/980805995737518110

**Comment by candela97** [comment]
Please report similar issues in the repository linked above, thanks!
