### ISSUE TITLE
[BUG] Current Best/Price History incorrect

### ISSUE THREAD

**Issue by SleepDaemon** [IsThereAnyDeal/AugmentedSteam#1434]
### Expected Behavior
Current Best price should match with the one shown on steam

### Actual Behavior
Current Best being either less or higher (varies between games) compare to one shown on steam

### Steps to Reproduce the Problem
Just go to any game store page and look.

### Specifications

  - **Augmented Steam Version:** _2.3.2_
  - **Browser Version:** _Microsoft Edge Version 103.0.1264.17 (Official build) beta (64-bit)_
  
  ### Screenshots
Lower
![image](https://user-images.githubusercontent.com/88533953/172450055-f0244b35-7e00-4275-9a25-7f92d17749e2.png)

Higher
![image](https://user-images.githubusercontent.com/88533953/172450221-d5b69dc6-76f0-423e-85d6-68ff0a2957a0.png)

**Comment by candela97** [comment]
For regions not supported by ITAD, the prices may be misleading, see #482
