### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Tom21200** [IsThereAnyDeal/AugmentedSteam#1444]
### Current Behavior (if any)
(none)

### Desired Behavior
Got an idea for Augmented Steam , if it's possible , maybe making an ""proxy"" that injects JavaScript (I mean, all of the current plugin's features) in the steam client (store.steampowered.com and steamcommunity.com) .. or making an mod for the client

### Motivation / Use Case for Changing the Behavior
Easier to use AND can be used everyday without going trough a web browser, also, may give people more ""motivation"" to download this extension.

(PS : sorry for my bad english, i'm french!)

**Comment by candela97** [comment]
Replied on Discord. In short: can't do this anymore since Steam switched to HTTPS. See related discussion at https://discord.com/channels/301903094080339968/532283733076869143/933200370472210492
