### ISSUE TITLE
[BUG] Sprocket steam/itch.io mismatch

### ISSUE THREAD

**Issue by evinnichenko** [IsThereAnyDeal/AugmentedSteam#1446]
### Expected Behavior
Sprocket on Steam (https://store.steampowered.com/app/1674170/Sprocket/) and on itch.io (https://ruoxuan-ying.itch.io/sprocket) are two different games, yet the latter shows as a "current best" for the former.

### Actual Behavior
The itch.io game shouldn't show in the "current best" for the steam game.

### Steps to Reproduce the Problem

  1. Open https://store.steampowered.com/app/1674170/Sprocket/
  2. Scroll down to the "current best" window
  3. Click on the itch.io link to see that it is different game

### Specifications

  - Augmented Steam Version: 2.3.2
  - Browser Version: Firefox 101.0.1 64 bit

**Comment by candela97** [comment]
Yeah this is an ITAD issue and was reported here https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2224. Seems like it isn't fixed though...

**Comment by candela97** [comment]
As mentioned this is an ITAD issue. The tracking issue is linked above, and you can report similar issues in that repository in the future.
