### ISSUE TITLE
[FEATURE REQUEST] View in Client button for all games, not just owned games.

### ISSUE THREAD

**Issue by Arindel** [IsThereAnyDeal/AugmentedSteam#1447]
### Current Behavior (if any)
View in Client button only available on owned games.

### Desired Behavior
View in Client button available for all games, owned and unowned, at all times.

### Motivation / Use Case for Changing the Behavior
I only use Steam client to make purchases and would like a way to get to store page directly in client without having to start from homepage in client.
Also I'm too lazy to keep logging in browser because the website is too forgetful so I just browse without login and when I want to wishlist something I gotta go to client and find the page manually so a View in Client button would be very helpful...

An extra would be to have a button that transfer any Steam store link to the client, including search pages, like when I search the MMORPG tag and would like to transfer that page from browser to the client.

**Comment by Arindel** [comment]
Ah, only now did I notice the little button at the very top. Thank you, I thought it was only for the button in the screenshow below which only appeared on owned games:

![Untitled](https://user-images.githubusercontent.com/21239038/178036279-1820cb1b-dd15-4689-a7b4-51a2ff90190b.jpg)

**Comment by candela97** [comment]
Closing as resolved.
