### ISSUE TITLE
[INFO NEEDED] Lowest Price Market on Sell Listing Bug

### ISSUE THREAD

**Issue by TakashiHafuza** [IsThereAnyDeal/AugmentedSteam#1448]
### Expected Behavior
My lowest price sell listing works well on page 2.
![image](https://user-images.githubusercontent.com/109186522/178617432-fe654aff-e54b-4f0f-a748-94d682b64cc6.png)

### Actual Behavior
But on page 1 it goes wrong. The listing date & my sell price is shifted to right, & the lowest sell price is gone. It just happens today
![image](https://user-images.githubusercontent.com/109186522/178617672-87acc825-9f56-4679-9bbe-cbd06de0b8ae.png)
I've tried to clear cached data or even reinstalling Augmented Steam but the bug persists.

### Steps to Reproduce the Problem
  1. Well, just open your sell listing at Steamcommunity Market

### Specifications
  - Augmented Steam Version: 2.3.2
  - Browser Version: Chrome Version 103.0.5060.114 (Official Build) (64-bit)
All updated

**Comment by TakashiHafuza** [comment]
OK now it seems back to normal
![image](https://user-images.githubusercontent.com/109186522/178624986-ffa50556-86bd-4c72-923e-4ab091d0b1d9.png)
But I assume it can happen again later

**Comment by TakashiHafuza** [comment]
OK
Besides it solves now, I need response from the dev about this

**Comment by candela97** [comment]
Interesting... maybe Steam changed something and there's some kind of race condition now 🤔
I'll see if I can reproduce this and check back. Thanks for the report and screenshots!
