### ISSUE TITLE
[FEATURE REQUEST] Add a button to view game on Steampeek

### ISSUE THREAD

**Issue by dilirity** [IsThereAnyDeal/AugmentedSteam#1449]
### Desired Behavior

Add a button to view the game on https://steampeek.hu/

### Motivation / Use Case for Changing the Behavior

It will be easier to check for alternatives of the current game.

Greatest thing is, steampeek works with app ids, so it shouldn't be that hard to implement.

**Comment by candela97** [comment]
We have an extra tab in the "More Like This" section that displays related apps from Steampeek. Hope this helps!
![123123](https://user-images.githubusercontent.com/54083835/179390817-f9b5c287-77ff-4d33-abd8-92b6129d5f07.jpg)

**Comment by dilirity** [comment]
I didn't even notice the "more like this" section. Closing this, as that fulfills the feature request.

Sorry about that 😅
