### ISSUE TITLE
Some games not syncing

### ISSUE THREAD

**Issue by fecheva** [IsThereAnyDeal/AugmentedSteam#1453]
I have noticed some game are not syncing. For example, in the last steam sale I bought from steam:
https://store.steampowered.com/app/1646810/NARGUL__Humans_are_among_us/
https://store.steampowered.com/app/1936360/Escape_From_Mandrillia/
together with some others.

All the games I bought appear in my collection at ITAD, but only some of the games I bought are synced while these two aren't.

I have deleted cache, disabled and re-enabled Augmented Steam, logged out and in again from ITAD and reconnected augmented steam and had no positive results.

**Comment by Kallan007** [comment]
I am having a similar issue. I added a game I own on Amazon to my collection on ITAD. Unfortunately, it does not appear on Steam having owned the game on another platform. This is only happening to one game, Football Manager 2022 https://store.steampowered.com/app/1569040/Football_Manager_2022/.

**Comment by candela97** [comment]
Please file a new issue if there're still problems with the new ITAD, thanks!
