### ISSUE TITLE
[FEATURE REQUEST] ProtonDB link on game page

### ISSUE THREAD

**Issue by Galdere** [IsThereAnyDeal/AugmentedSteam#1454]
### Current Behavior (if any)

n/a

### Desired Behavior

A link to the protondb page for a game beneath the pcgamingwiki article link

### Motivation / Use Case for Changing the Behavior

Steam deck and linux information

**Comment by 32423d** [comment]
This feature is already present with the extension. 
![image](https://user-images.githubusercontent.com/95009201/180949517-22ceaf84-e074-44c5-92e3-2ed9db2aa13a.png)
Steam also displays steam deck compatibility information on game pages now.
![image](https://user-images.githubusercontent.com/95009201/180949820-4ffd00ea-af58-482c-be05-96dd8a8a5534.png)
