### ISSUE TITLE
[BUG] Wrong Game Price History Listing

### ISSUE THREAD

**Issue by syto203** [IsThereAnyDeal/AugmentedSteam#1458]
### Expected Behavior
Show historical data for the game "The Forest"
https://store.steampowered.com/app/242760/The_Forest/

### Actual Behavior
Shows historical data for "Forest" 
https://store.steampowered.com/app/1859730/Forest/

### Steps to Reproduce the Problem

  1. open steam store page for "The Forest".
  2. wait for the extension to finish loading.
  3. point eye to history information view.

### Specifications

  - Augmented Steam Version: 2.3.2
  - Browser Version: Firefox 104.0 - Microsoft Edge Canary 105

Extra info:
Listing on isthereanydeal.com show the wrong information as well. it treats both games as one.

**Comment by candela97** [comment]
Yeah, this was most recently reported in https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/3002 and triaged. You can file ITAD-related issues in that repository in the future, thanks!
