### ISSUE TITLE
[FEATURE REQUEST] Focus search on Store page

### ISSUE THREAD

**Issue by splendid25** [IsThereAnyDeal/AugmentedSteam#1459]
### Desired Behavior

Focus search field when opening Store page (or option to enable this behavior)

### Motivation / Use Case for Changing the Behavior

To save a few seconds when I open the store page to search a game.

Thanks

**Comment by candela97** [comment]
This seems simple enough to do. BTW can you fill in the issue title so others can find this when searching for similar issues?

**Comment by candela97** [comment]
After some thinking, focusing the search box disrupts normal keyboard navigation, and may not be a good idea for a default-enabled feature. How about hitting "s" to focus (and scroll to) the search box when not focusing any other text box? Same as how the GitHub site handles it.

**Comment by splendid25** [comment]
Yeah actually, the store is the home page, so it would not be ideal.
OK the same behavior as Github would be useful, if it's easy to implement.
