### ISSUE TITLE
[FEATURE REQUEST] Search developer in steam store

### ISSUE THREAD

**Issue by emorkovin** [IsThereAnyDeal/AugmentedSteam#1462]
### Current Behavior (if any)

On some store page Steam opens special hub for publisher and/or developers.

### Desired Behavior 

By adding small icon that refer to link on steam serach in store by developer/publicher name will be usefull.

### Motivation / Use Case for Changing the Behavior

Old option for search games in store may usefull when normal developer page lead to BIG Hub of publicher, but you want see only games by one developer. Bring back the old functionality is good option.

**Comment by candela97** [comment]
We have this exact feature already on app pages, though we replace the old link with a search page link instead.
![螢幕擷取畫面 2022-08-14 210842](https://user-images.githubusercontent.com/54083835/184538529-88372ad7-76f9-445b-808f-0a718994880d.jpg)

**Comment by candela97** [comment]
Closing as resolved. Feel free to comment if I missunderstood the request. There *is* a bug right now that we only parse the first developer/publisher, not all if there're multiple. I'll send a fix for that soon...
