### ISSUE TITLE
[FEATURE REQUEST] Show hidden achievements

### ISSUE THREAD

**Issue by Lukkian** [IsThereAnyDeal/AugmentedSteam#1463]
### Current Behavior (if any)
Does not show hidden achievements

### Desired Behavior
A setting or button to show hidden achievements

### Motivation / Use Case for Changing the Behavior
Today I need to access other tools just to show hidden achievements, please add that to AugmentedSteam

**Comment by candela97** [comment]
Problem is where to get the descriptions. I only know of the global achievement stats page, which displays all achievements but only the title for hidden ones that are locked.

**Comment by Lukkian** [comment]
The game's global stats page shows the titles and descriptions of all achievements, including "hidden" ones.
https://steamcommunity.com/stats/589360/achievements/

**Comment by candela97** [comment]
I'm pretty sure only the title is displayed for hidden achievements that are locked. The description is revealed after you unlock the achievement. I feel this will end up being a half-baked feature if we can't work around this limitation...

**Comment by candela97** [comment]
According to SteamDB's implementation, we can append `&panorama=please` to get the `g_rgAchievements` which has all achievement related data. So yeah this is doable.
