### ISSUE TITLE
Confusing two different games?

### ISSUE THREAD

**Issue by CPTpurrfect** [IsThereAnyDeal/AugmentedSteam#1480]
AS thinks 30XX is 2002XX
30XX https://store.steampowered.com/app/1029210/30XX/
2002XX https://store.steampowered.com/app/1576140/2002XX/

**Comment by candela97** [comment]
Yep, this game has been reported several times, the most recent being https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/3006, and is on the list of entries to fix. You can file ITAD-related issues in that repository in the future, thanks!
