### ISSUE TITLE
[BUG] How Long To Beat links broken

### ISSUE THREAD

**Issue by Canadiancookie** [IsThereAnyDeal/AugmentedSteam#1488]
![0n9dhsU](https://user-images.githubusercontent.com/33509033/190267504-2082924c-856f-49af-90f8-20f968386c71.png)

How Long To Beat links here are broken. For example, More Information links to https://howlongtobeat.com/game.php?id=38050 when it should be https://howlongtobeat.com/game/38050 on the store page for God of War.

### Specifications

  - Augmented Steam Version: 2.3.3
  - Browser Version: Chrome 105.0.5195.125 (Official Build) (64-bit)

**Comment by candela97** [comment]
Fixed server-side.
