### ISSUE TITLE
[FEATURE REQUEST] Improve handling of voucher discounts in prices

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/AugmentedSteam#1489]
### Current Behavior (if any)
We always display prices with voucher discounts included if there's an available (but not necessarily applicable) voucher.

### Desired Behavior
We need to take possible voucher exclusions into consideration when displaying prices. The new ITAD site will ideally have an easier way to handle this. In the meantime, a temporary solution can be to display vouchers and related prices in a separate row, and list vouchers as a "possible addtional discount".

### Motivation / Use Case for Changing the Behavior
Better reflect the applicability of vouchers on any given game.

**Comment by visor841** [comment]
A particularly bad case is for the FANATICAL15 code on Fanatical, which *only* works for full-price games. This means that frequently when Fanatical is listed as the lowest price for a game right now, it isn't actually the lowest (because the price listed is after applying both sale and voucher).

**Comment by JohnChristmann** [comment]
The extension incorrectly listing stacked discounts for un-stackable coupon codes for Green Man Gaming also seems to be quite common.  Currently it's showing that for an EXPIRED coupon.

**Comment by candela97** [comment]
The new ITAD handles this better now. Future issues with coupons should be filed against ITAD.
