### ISSUE TITLE
[BUG] regional prices dont work

### ISSUE THREAD

**Issue by Fan4eGGG** [IsThereAnyDeal/AugmentedSteam#1499]
### Dont work a regional prices on a "mouse" or "always" settings. but in "privat window" in Opera it works.
trying to turn off my extensions n it didnt help. tryin to reset settings and reinstall - nthg.
some help?

### win10, dunno what else.

  - Augmented Steam Version: **2.3.3**
  - Browser Version: **Opera 90.0.4480.84**

**Comment by candela97** [comment]
Any errors in the browser console (F12)? A common cause is failure to fetch currency conversion rates from the ITAD server, which usually resolves after a while.

**Comment by Fan4eGGG** [comment]
It seems to me not about itad Server. In another browser, everything works correctly.
I don’t even have a globe icon near the prices, although it was before.

There are mistakes in the console, though I do not understand anything about this. Here is [a screenshot](http://prntscr.com/H18FnAZ2gsVg).

**Comment by candela97** [comment]
Oh another case of HTTP 400! Somebody on Discord had this issue too, and deleting Steam's cookie (you will have to log in again) resolved it for them, wanna give it a try?

**Comment by Fan4eGGG** [comment]
welp.
I delete all cookie in browser n it didnt help.

**Comment by candela97** [comment]
Still HTTP 400? Do you have other browser extensions installed? Can you try with only AS enabled?

**Comment by Fan4eGGG** [comment]
yep. still 400

**Comment by candela97** [comment]
I got Opera 91 and installed the extension from the Chrome store, and everything works normally on my end, even with Opera's built-in adblocker enabled, so sadly I'm out of ideas.

**Comment by Fan4eGGG** [comment]
well, I have a suspicion that some extension is interfering with this (since regional prices are shown in private mode), but the fact is that I already turned off each one and left only the AS - and it still didn’t work.
I do not even know what to do, a very useful feature.

**Comment by candela97** [comment]
A faster way to test is to open any of the links directly, like `https://store.steampowered.com/api/packagedetails/?packageids=320848&cc=gb`, and see if they return something (other than `null`).

I still think it has something to do with cookies, since in private mode the request doesn't include cookies.

**Comment by Fan4eGGG** [comment]
umm, look.
I don't know how, but everything worked itself out for me. I left today for the day, leaving the PC on. I come, open page of the game to buy it, and a globe icon appeared and, on hover, regional prices appeared.
I did NOTHING after I answered you here in the post. what happened - I have no idea.

**Comment by candela97** [comment]
I think we can try with omitting credentials when fetching this endpoint, since it works without sending cookies. That should fix it for people who are having problems.

**Comment by Fan4eGGG** [comment]
I'm glad everything is back.
thank you for your help.
