### ISSUE TITLE
[FEATURE REQUEST] After my chrome updated, the SteamID turned into a pull down

### ISSUE THREAD

**Issue by skozzyau** [IsThereAnyDeal/AugmentedSteam#1501]
Up till recently I used to have a button to click on for VIEW STEAMID, now it has changed into a small button with three dots and it changed to a pulldown menu with a bunch of links I dont use like Follow, View Post History, Add Nickname and so on.
I assume the update caused the change, if not how do I config it so the VIEW STEAMID is a stand alone button to click on.
I do use this a lot in my game admin role.

**Comment by candela97** [comment]
It has always been like this in AS - the link is placed in the dropdown when viewing other people's profiles, so you may have been using a different extension for this feature.

**Comment by skozzyau** [comment]
Oh I found out why it changed, when I sign out of steam the button I was
talking about comes back

[image: image.png]
