### ISSUE TITLE
[BUG] Deleting comments on steam reviews doesn't work

### ISSUE THREAD

**Issue by bottleblue** [IsThereAnyDeal/AugmentedSteam#1510]
### Expected Behavior
Clicking the trash can icon then clicking OK should delete the comment

### Actual Behavior
When I click the trash can icon, Augmented Steam gives me a popup asking if I want to delete the comment, with a checkbox option to not show the message again which I didn't enable. I click OK and then nothing happens. The comment is not deleted. I had to disable AS in order to delete the comment.

### Steps to Reproduce the Problem

  1. Make a comment on a steam review
  2. Click the trash can icon to delete the comment. Get the popup asking if you want to delete it. Click Ok.
  3. Nothing happens, the comment is still there.

### Specifications

  - Augmented Steam Version: 2.3.3
  - Browser Version: Firefox 106.0.1

**Comment by candela97** [comment]
Can you check if there're any errors in the browser console? You can test this in the comment section of your own profile.

You can also disable this feature in Options ( Show confirmation when deleting comments) if you want.

**Comment by bottleblue** [comment]
Hmm it seems to be working now. It must have been something on Steam's end. Like sometimes I'll click the thumbs up/down on a review and it doesn't register, saying there's an error. Ok false alarm sorry.

**Comment by candela97** [comment]
Yeah that happens to me too, especially on the news hub. Says "Access denied, not logged in" and I'm like ???

In any case, this feature eventually calls Steam's method, so there's nothing we can do if that fails.
