### ISSUE TITLE
[BUG] Call of Duty: Modern Warfare II is being confused with Call of Duty: Modern Warfare 2 for pricing

### ISSUE THREAD

**Issue by m384wwn** [IsThereAnyDeal/AugmentedSteam#1512]
### Expected Behavior
isthereanydeal Call of Duty: Modern Warfare II pricing on the steam store is shown for Call of Duty: Modern Warfare II

### Actual Behavior
isthereanydeal Call of Duty: Modern Warfare 2 pricing is being shown as the pricing for Call of Duty: Modern Warfare II

![image](https://user-images.githubusercontent.com/12596995/198761775-930c8d6a-f61c-44d4-bb29-72d8ca5b42f6.png)

### Steps to Reproduce the Problem

  1. look at Call of Duty: Modern Warfare II isthereanydeal pricing on the steam store https://store.steampowered.com/app/1938090/Call_of_Duty_Modern_Warfare_II/

### Specifications

  - Augmented Steam Version: 2.3.3
  - Browser Version:  Chrome 106.0.5249.119 (Official Build) (64-bit)

P.S. this is a real bug report. maybe the issue is on the isthereanydeal.com end? keep up the good work

**Comment by candela97** [comment]
Yeah, this is an ITAD issue and is being tracked at https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/3059. You can file issues with ITAD data in that repository in the future, thanks!
