### ISSUE TITLE
[BUG] Issues with reviews sort

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/AugmentedSteam#1526]
This feature needs an update to support new Steam features and fix a few edge cases.

### Actual Behavior
1. Click handlers for the new Steam rewards are not preserved (note: a `.more_btn` is shown after 3 rewards)
2. Developer responses are not properly restored to its original position
3. ~~Need to check what happens with banned reviews, I think there's a red banner of some sorts~~
The banner is placed within the review box so we're good
4. Reverse sort isn't working properly for some sort methods
5. Sorting by helpful and funny is broken due to the addition of the Steam rewards node

**Comment by BlueRaja** [comment]
Forward sort also seems to be broken. See [this profile](https://steamcommunity.com/id/BlueRaja/recommended/?p=1) _(from the above linked issue)_

**Comment by BlueRaja** [comment]
The above issue appears to be caused by the fact that, when a user gives a review an award, the Steam API seems to multiply the review `helpful` rating (or sometimes the `funny` rating) by a few billion trillion 

```
reviews[30].helpful
> 6.1223342630128214e+32 
```

**Comment by BlueRaja** [comment]
oh, I missed [this](https://github.com/IsThereAnyDeal/AugmentedSteam/blob/a2f566a16ee89946ca387fa81253ce73d88a5d9f/src/js/Background/Modules/SteamCommunityApi.js#L243). I thought those values were coming from the API.

I think you can fix that by removing the `/g`

```
parseInt(headerText[0].match(/\d+/g).join(""))
> 3.917516001175145e+31
parseInt(headerText[0].match(/\d+/))
> 39
```

**Comment by BlueRaja** [comment]
I tried a few other languages and it seemed to work in those as well. I'm not sure about RTL languages because I can't find the option to switch to Arabic.

**Comment by candela97** [comment]
I think the `g` is needed due to thousands separators.

Steam doesn't support Arabic, so we don't either.
