### ISSUE TITLE
[BUG] Not working vendor websites options

### ISSUE THREAD

**Issue by H4M5TER** [IsThereAnyDeal/AugmentedSteam#1532]
### Expected Behavior

Metacritic, OpenCritic.com, HowLongToBeat.com information appears in the store page.

### Actual Behavior

didn't appear, the others are fine

### Steps to Reproduce the Problem

  1. Tick the checkbox above.
  2. Go to random store page.

### Specifications

  - Augmented Steam Version: 2.3.3 from Chrome Web Store
  - Browser Version: Vivaldi 5.5.2805.32, Chromium 106.0.5249.113

**Comment by candela97** [comment]
This is temporary and should work after a few retries.

**Comment by candela97** [comment]
Let us know if this issue persists. I can't reproduce anymore, not even occasionally.
