### ISSUE TITLE
[BUG]Data error on the lowest price in history

### ISSUE THREAD

**Issue by DistanceV** [IsThereAnyDeal/AugmentedSteam#1534]
The lowest function in history has errors
When you are not logged in, everything is normal,
However, after logging in, the data of the lowest price in history seems to be the data of the United States in any case, and it is wrong in any case.

**Comment by DistanceV** [comment]
> For example, let me give an example, such as World War Z: Aftermath.

>My current account is in Argentina. Now the game is worth 999ARS. I found that the lowest price of the game in history is 
439ARS through steam DB. However, the data displayed by Augmented Steam is always the lowest price in history in the United States.

![image](https://user-images.githubusercontent.com/119254802/205464344-b2445e13-4613-46fd-95e9-5c7f2a50c072.png)
![image](https://user-images.githubusercontent.com/119254802/205464382-aa446408-388e-46bd-b876-912bbbab6d4c.png)
![image](https://user-images.githubusercontent.com/119254802/205464415-76d5e1b0-c215-4e16-ac12-89c88444a622.png)
> It is worth saying that my account region is Argentina, but my current real region is China. However, whether I use the Internet proxy tool or not, the lowest price in history is always the data of the United States.

> To put it simply, I hope that the lowest price in history should correspond to the region where the current account is located rather than the data in the United States.I don't know what caused this, Because it has nothing to do with me. I hope you can find this problem and solve it. Although he may only be a potential one, as far as I know, this situation does not happen to me,Thank you very much!

**Comment by candela97** [comment]
Right, for regions not supported by ITAD, prices are converted from USD, see https://github.com/IsThereAnyDeal/AugmentedSteam/issues/482. We detect store country via the page's inline scripts, that's why you see a mismatch when not logged in, and CNY is supported so prices are tracked accordingly. If you're only interested in prices from Steam, I suggest using SteamDB's extension.
