### ISSUE TITLE
[FEATURE REQUEST] Show last update date and player approval rating

### ISSUE THREAD

**Issue by lucasbooz** [IsThereAnyDeal/AugmentedSteam#1535]
### Current Behavior (if any)
Just below the game reviews on the steam purchase page, it doesn't exist but it would be interesting to add this new information.
### Desired Behavior
![desired](https://user-images.githubusercontent.com/67797271/204592981-cd2e3979-f9b2-4daf-a01f-d228cd2a43e7.PNG)
![desired2](https://user-images.githubusercontent.com/67797271/204595057-63c02754-1af8-4214-b9e3-eb09a78bbc1f.PNG)
### Motivation / Use Case for Changing the Behavior
I believe it would be important for people to be able to see the date of the last update of a given game, if it is abandoned or not, in addition to the percentage of approval of the players would be more useful information.

**Comment by candela97** [comment]
That data is provided by SteamDB and is a feature of SteamDB's extension, so you can enable that if you want. There are some duplicate features, but you can disable them if there're conflicts. I don't think it makes sense for us to duplicate this particular feature here...
