### ISSUE TITLE
[BUG] Failed to sync with ITAD

### ISSUE THREAD

**Issue by sehraf** [IsThereAnyDeal/AugmentedSteam#1542]
### Expected Behavior
Sync to ITAD works.

### Actual Behavior
Sync to ITAD doesn't work:

![image](https://user-images.githubusercontent.com/2230104/206744092-d2d031a4-ecf7-47d0-a855-28d0474e95dc.png)

![image](https://user-images.githubusercontent.com/2230104/206744131-68871a78-b3aa-4e9f-b77a-fe326c04a751.png)

### Steps to Reproduce the Problem

  1. connect ITAD in the augmented steam options
  2. click the ITAD sync button
 
### Specifications

  - Augmented Steam Version: 3.15.2
  - Browser Version: Chrome 108.0.5359.98

### Notes
Triggering a sync from ITAD's side also doesn't work for collection (waitlist syncs fine) 

![image](https://user-images.githubusercontent.com/2230104/206763612-70f70a0f-f622-4393-8335-bd2c826ab912.png)

**Comment by candela97** [comment]
Please file a new issue if there're still problems with the new ITAD, thanks!
