### ISSUE TITLE
[BUG]  "Install game" erroneously adds to cart

### ISSUE THREAD

**Issue by DAOWAce** [IsThereAnyDeal/AugmentedSteam#1546]
Might be a bug with the new feature:  
> Add option to stay on the page after you add game to your cart, instead of redirecting to the cart

Couldn't get it working until I disabled the addon (didn't toggle option, which I now see defaulted to enabled)

### Expected Behavior
"Install game" adds to library instantly

### Actual Behavior
"Install game" adds to cart, and will error out attempting to purchase the 'free' game

### Steps to Reproduce the Problem

  1. Visit a currently free game you can add to your account (ex. https://store.steampowered.com/app/1294660/Divine_Knockout_DKO/ )
  2. Click "install game"
  3.  Watch as it gets added to cart instead

### Specifications

  - Augmented Steam Version: 2.4.0
  - Browser Version: Vivaldi 4.3.2439.65 (Chrome/94)

**Comment by candela97** [comment]
I wonder if hitting checkout works the same for these free promotions 🤔
