### ISSUE TITLE
[BUG] Steam Subscriber Agreement unchecked when using "Activate more keys"

### ISSUE THREAD

**Issue by Rex000** [IsThereAnyDeal/AugmentedSteam#1559]
### Expected Behavior
Should be checked

### Actual Behavior
Is unchecked

### Steps to Reproduce the Problem

  1. Activate a key using "Activate a product" page
  2. Once activated, click on "Activate more keys"

### Specifications

  - Augmented Steam Version: 2.4.0
  - Browser Version: Chrome Version 108.0.5359.125 (x64)

**Comment by candela97** [comment]
This'll be fixed by the linked PR.
