### ISSUE TITLE
[BUG] Hiding featured franchises only hides the label

### ISSUE THREAD

**Issue by NekoiNemo** [IsThereAnyDeal/AugmentedSteam#1562]
### Expected Behavior
To hide the entire section

### Actual Behavior
Only the label "Featured Franchises" gets hidden, the cards themselves are still shown

![screenshot_1672056992](https://user-images.githubusercontent.com/3595771/209548223-baca7dd5-8778-4d26-b79e-13337e1ccb5c.png)
![screenshot_1672057014](https://user-images.githubusercontent.com/3595771/209548228-20a2f777-9b02-4e5d-9e22-c394da478d52.png)

### Specifications

  - Augmented Steam Version: 2.4.0
  - Browser Version: Chrome 108.0.5359.124

**Comment by candela97** [comment]
Yeah, but it's a dynamic entry and I'm not sure if it's worth further tweaking the logic...

In any case, I strongly recommend using content blockers like uBlock Origin to hide unwant stuff. A custom rule like this will do: `store.steampowered.com##.home_franchises_ctn`
