### ISSUE TITLE
[FEATURE REQUEST] Wishlist groups

### ISSUE THREAD

**Issue by Dave247** [IsThereAnyDeal/AugmentedSteam#1567]
### Desired Behavior
Being able to somehow "group" items on your own wishlist together, kinda in the same vain how you can in your library. Either in a custom order, or by a game tag.

### Motivation / Use Case for Changing the Behavior
This would bring the wishlist to better align with how the library operates, where you are able to group games in your own custom order, or even partly automated by grouping via a specific tag. I have a lot of games on my wishlist that could be defined as "Co-op" for example, that I wish to keep an eye on to potentially purchase at a later date when the need arises, such as I have completed all of the current co-op games I own with friends.

Another such category could be "Early Access", games I wish to keep an eye on but probably not purchase until they get a full release.

**Comment by candela97** [comment]
I saw this being suggested on Steam discussions many times, but it would take quite a lot of work. We'll essentially have to maintain a "fork" of wishlist.js to support any substantial modification like this.
