### ISSUE TITLE
[FEATURE REQUEST] One-click Steam Cloud backups

### ISSUE THREAD

**Issue by BynariStar** [IsThereAnyDeal/AugmentedSteam#1568]
### Desired Behavior
Steam has a [page on its site](https://store.steampowered.com/account/remotestorage) where you can view and download individual game files that were backed up to Steam Cloud. However, if you wanted to download a backup of all your files, you'll find yourself endlessly clicking download on each file and organizing them into endless folders. 
A simple one-click download button that would consolidate all the files into a zip file would be very handy.

![image](https://user-images.githubusercontent.com/1224547/210120844-5aed5652-5e66-4a0d-9a86-57c941aa5826.png)

![image](https://user-images.githubusercontent.com/1224547/210120868-ea310b25-9063-413f-babd-697a04409691.png)

**Comment by candela97** [comment]
Would be handy indeed, but we'll need a 3rd-party library to do the zipping and I'm not sure if we'll run into issues downloading muliple files at once 🤔

**Comment by MxtOUT** [comment]
Way too niche to justify including a library, sorry
