### ISSUE TITLE
[BUG] Wrong game store URL

### ISSUE THREAD

**Issue by avi12** [IsThereAnyDeal/AugmentedSteam#1570]
### Expected Behavior
The link should redirect to https://www.ea.com/games/starwars/jedi/jedi-survivor

### Actual Behavior
It redirects to https://www.ea.com/games/star-wars/star-wars-jedi-survivor

### Steps to Reproduce the Problem

  1. Go to https://store.steampowered.com/app/1774580/STAR_WARS_Jedi_Survivor
  2. ![image](https://user-images.githubusercontent.com/6422804/211659879-6cbf3849-baa1-402a-94d6-845861a5f6c5.png)

### Specifications

  - Augmented Steam Version: 2.4.0
  - Browser Version: Brave 1.46.153

### Another example
At https://store.steampowered.com/app/1426210/It_Takes_Two/
![image](https://user-images.githubusercontent.com/6422804/211801529-3306c428-6c7b-4c9e-bce7-da3f34194087.png)
The link redirects to https://www.humblebundle.com/store/p/ittakestwo_switch_storefront
Whereas the game was apparently removed from [Humble Bundle](https://www.humblebundle.com/store/search?sort=bestselling&search=It%20Takes%20Two):
![image](https://user-images.githubusercontent.com/6422804/211801868-14392643-f963-4c79-ac3a-2bda9843c613.png)

**Comment by candela97** [comment]
Looks like EA changed the store link at some point. Please file ITAD issues like this over at https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues or in the Discord #bugs channel (I've about this posted there), thanks!
