### ISSUE TITLE
[BUG] Pulling price for Shenmue 3 when looking at Shenmue 1 and 2

### ISSUE THREAD

**Issue by Glizbane** [IsThereAnyDeal/AugmentedSteam#1573]
I'm using the add-on for firefox, and like the title says, it's pulling the price for Shenmue 3 when on the page for the Shenmue 1 and 2 bundle.

While the price pulled for Shenmue 3 is accurate, GOG does not even carry Shenmue 1 and 2.

![image](https://user-images.githubusercontent.com/120626164/213879373-381c837b-80f6-495f-8df1-8afdb27dfb59.png)
![image](https://user-images.githubusercontent.com/120626164/213879451-cd6d76ea-207d-4620-b00b-f4e309a84e6d.png)

**Comment by candela97** [comment]
Yep, this has been filed here https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/1363. You can report ITAD-related issues in that repository in the future, thanks!
