### ISSUE TITLE
问一个关于“用户备注”的问题

### ISSUE THREAD

**Issue by wellkens** [IsThereAnyDeal/AugmentedSteam#1574]
作者你好，Augmented Steam有一个功能是可以在愿望单里给游戏添加备注信息，我发现这个功能是有上限的，因为添加到一定数量之后就无法添加了，所以我想问一下，假如这个上限是100，如果我从愿望单里移除了一个已经写了备注信息的游戏，那么现在我的备注上限仍然是100还是变成了99？

**Comment by wellkens** [comment]
如果变成了99的话，有没有办法清理已经写入的备注信息呢？

**Comment by candela97** [comment]
No, we don't have logic that removes the associated note when unwishlisting a game. You'll have to visit the game's store page to remove it. We're also working on an overview feature to make it more convenient to manage notes, see #429.
