### ISSUE TITLE
[FEATURE REQUEST] Early access on search / frontpage results

### ISSUE THREAD

**Issue by jadekler** [IsThereAnyDeal/AugmentedSteam#1575]
It's annoying having to click into a game to see whether it's early access.

**Comment by aricneto** [comment]
Isn't this already a feature? 
https://github.com/IsThereAnyDeal/AugmentedSteam/blob/master/src/js/Content/Features/Common/FEarlyAccess.js

![](https://i.imgur.com/MgYaLha.png)
![](https://i.imgur.com/HNirDml.png)

**Comment by candela97** [comment]
I guess the OP filed this during the sale. We can't handle these new pages built with React yet.

**Comment by candela97** [comment]
This is a known issue on new style pages that we're actively looking into, otherwise the EA banner feature should be working fine.
