### ISSUE TITLE
Skyrim Special Edition page appears to have Elder Scrolls Online Opencritic info [BUG]

### ISSUE THREAD

**Issue by beltofdespair** [IsThereAnyDeal/AugmentedSteam#1576]
### Expected Behavior
Skyrim Special Edition page should have information on Skyrim Special Edition reviews (https://opencritic.com/game/2851/the-elder-scrolls-v-skyrim-special-edition) from Opencritic.

### Actual Behavior
Skyrim Special Edition page has information on Elder Scolls Online reviews (https://opencritic.com/game/2212/the-elder-scrolls-online) from Opencritic.

### Steps to Reproduce the Problem

  1. Go to https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 109.0

**Comment by candela97** [comment]
There doesn't seem to be any reviews specifically for "Skyrim Special Edition" on OpenCritic, so it has been unlinked.
