### ISSUE TITLE
[FEATURE REQUEST] Check user's profile from thier wishlist.

### ISSUE THREAD

**Issue by abi-21** [IsThereAnyDeal/AugmentedSteam#1579]
When viewing someones steam wishlist, there is no easy way to go to their main profile. For example opening this link https://store.steampowered.com/wishlist/profiles/76561198235320820/#sort=price , you can't check their profile.

**Comment by candela97** [comment]
We can probably add a link to the avatar image?

**Comment by abi-21** [comment]
> We can probably add a link to the avatar image?

That would be great!

**Comment by abi-21** [comment]
Doesn't seem to work anymore. 
Using Augmented Steam v4.1.2, Brave browser v1.73.97.

**Comment by candela97** [comment]
@abi-21 will be fixed in v4.2.1
