### ISSUE TITLE
[BUG] Wolfpack shows prices on IsThereAnyDeal for Wolf(space)Pack

### ISSUE THREAD

**Issue by Joonasm** [IsThereAnyDeal/AugmentedSteam#1582]
### Expected Behavior
The page for game Wolfpack shows prices from IsThereAnyDeal for the same game

### Actual Behavior
The prices shown are for a bundle [Wolf Pack](https://isthereanydeal.com/game/wolfpack/info/) Instead

### Steps to Reproduce the Problem

  1. Navigate to [Wolfpack](https://store.steampowered.com/app/490920/Wolfpack/#app_reviews_hash) store page
  2. Go to the buy wolfpack button and click on the current best price above it
  3. Be directed to a bundle for different games instead of Wolfpack

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 110.0 (64-bit)

**Comment by candela97** [comment]
This has been reported here https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2386 and is on the list of entries to split. You can file ITAD related issues in that repository in the future , thanks!
