### ISSUE TITLE
[FEATURE REQUEST] Add "Show AppAgg links" to "Options for information from 3rd-party sites"

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1583]
### Current Behavior (if any)

Appagg.com (alternative game price tracker) does not appear in the list of sites that can be reached from the game page.

### Desired Behavior

Add a link to the corresponding page on appagg.com in the "3rd-party sites" section of each game. For example, https://appagg.com/steam/actionandadventure/wolfenstein-3d-32798576.html for https://store.steampowered.com/app/2270

### Motivation / Use Case for Changing the Behavior

AppAgg is interesting because it monitors the prices of not only PC and console games, but also mobile games. Including for this reason, I prefer to use it instead of ITAD.

**Comment by candela97** [comment]
You can add it as a custom link for now, see https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1263#issuecomment-948123330 for an example.

**Comment by Korb** [comment]
> You can add it as a custom link for now

Thank you.  With these settings:

```
Name: AppAgg
URL: https://appagg.com/search/[NAME]:steam-games/?hl=en
Icon: https://appagg.com/i/favicon48f.png
```

it turned out like this:

![Screenshot 2023-02-23 at 20-26-42 The Planet Crafter on Steam](https://user-images.githubusercontent.com/3509797/220983761-12d5e2e2-b865-42d7-9209-54616d8e242f.png)

Not a direct link to the application page, but not bad either.

**Comment by Korb** [comment]
It seems that something is broken. Whatever values I enter in the "Name", "URL" and "Icon" fields of the "Options for information from 3rd-party sites" block, the corresponding links do not appear on the game pages on Steam.

Augmented Steam 2.4.1 (January 17, 2023)
Mozilla Firefox 115.0b9 (64-bit)
Microsoft Windows 10.0.19045.3086
