### ISSUE TITLE
[FEATURE REQUEST] View list of games with notes

### ISSUE THREAD

**Issue by ZachFett** [IsThereAnyDeal/AugmentedSteam#1591]
### Current Behavior (if any):
Have to remember which games I've added notes to.

### Desired Behavior:
Some method of sorting the store or viewing a list of which games I've added a note to, without needing to add them to my wishlist or bookmark each one.

### Motivation / Use Case for Changing the Behavior:
I've written little notes on so many games to remind myself where I own them on other platforms and various other things, but as far as I can tell there's no convenient way to look at all of the games I've left notes on. It'd be useful, especially if you're using the synced storage option and need to clear some space. I'm at 90% but I don't see any convenient way to go through and clear up some older notes without just wiping the entire thing.

Also side note: Where are notes stored when using the local storage option?

**Comment by enchained** [comment]
There's already a similar request https://github.com/IsThereAnyDeal/AugmentedSteam/issues/429

For now, you can try exporting the extension settings (bottom right on the settings page). All your notes should be listed under "user_notes" in that text file. There's no game names, just app ids, so if you need other info, you'll have to go to https://store.steampowered.com/app/{app_id} links manually.

***

Also, just for keeping track of games owned elsewhere, you could use a more convenient feature of the extension - ITAD Library sync. On any Steam game page, you'll need to click the "Current best" link, [ITAD](https://isthereanydeal.com/) page will open, and you can Add to Collection from there (and select a specific store). There's also [auto import](https://isthereanydeal.com/settings/profiles/) of GOG and Humble collections in the settings, and you can manually add EGS etc [giveaways from the Specials page](https://isthereanydeal.com/specials/#/filter:&giveaway).

Then in the Augmented Steam settings - Store - IsThereAnyDeal you connect to your ITAD account, check Periodically import: Library. Below you can also select highlight and tag colors for the ITAD-collected games. Then you can go to Steam and check the sync state (blue logo on top of the page). After the sync any games added to the collection on ITAD will have a big owned bar indicator similar to the native Steam one. 

P.S. If your store is not listed on the ITAD collection form, you can select Other and add a tag or a note to the entry. Sadly there's no way to view those tags or notes directly on Steam yet, but there is a feature request: https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1551

**Comment by ZachFett** [comment]
I was able to trim down all of my notes by quite a bit after exporting it, but I'll have to try doing the add to collection thing on ITAD soon since that's probably far more convenient.
Thanks for all the info!
