### ISSUE TITLE
[FEATURE REQUEST] Implement offset for Humble Choice discount

### ISSUE THREAD

**Issue by Jademalo** [IsThereAnyDeal/AugmentedSteam#1592]
### Current Behavior (if any)
At present, there is no way to factor in the flat 20% discount that is always available in the Humble Store for people with Humble choice

### Desired Behavior
Ideally an offset or modifier that lets you set a blanket discount for a certain store

### Motivation / Use Case for Changing the Behavior
It's hard to figure out exactly which store is cheapest, since if you've got a high choice discount then you need to factor that in. It would be great to have this built in, so it's easy to see at a glance.

**Comment by candela97** [comment]
Related: #854

**Comment by MxtOUT** [comment]
The linked issue includes this one, so I'm closing
