### ISSUE TITLE
[BUG] Invalid "View on IsThereAnyDeal" link from Severed Steel steam page

### ISSUE THREAD

**Issue by tinoue** [IsThereAnyDeal/AugmentedSteam#1593]
### Expected Behavior
Pressing "View on IsThereAnyDeal" from Servered Steel steam page (https://store.steampowered.com/app/1227690/Severed_Steel/) jumps to correct ITAD page (https://isthereanydeal.com/game/severedsteel/info/)

### Actual Behavior
Incorrect ITAD page (https://isthereanydeal.com/game/impact/info/) is shown.

### Steps to Reproduce the Problem

  1. Open steam page of  Servered Steel (https://store.steampowered.com/app/1227690/Severed_Steel/
  2. Press "View on IsThereAnyDeal"
  3. Incorrect ITAD page (https://isthereanydeal.com/game/impact/info/) is shown instead of https://isthereanydeal.com/game/severedsteel/info/

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Google Chrome Version 110.0.5481.78 (Official Build) (64-bit) for Windows 10 64bit

**Comment by candela97** [comment]
This has been fixed. Nice find!
