### ISSUE TITLE
[BUG] Lowest market price stops loading on my listed stuff

### ISSUE THREAD

**Issue by djbnando** [IsThereAnyDeal/AugmentedSteam#1594]
### Expected Behavior
When I open my steam market to see cards and stuff that I have listed, it shows the price that I have listed, and right in front of it, it will load the lowest market value for that item. In green if I have the lowest, in red if there's a lower than mine.

### Actual Behavior
It happens that after 2 or 3 pages it stops loading the lowest market price value, and just show "loading", therefore I can't see if I'll have to relist or not, unless I open each item individually.

### Steps to Reproduce the Problem

  1. Open steam market
  2. Let the 10 itens from first page load and then move to the 2nd and maybe 3rd page
  3. It will stop loading the market lowest price

### Specifications

  - Augmented Steam Version: 
  - Browser Version: 
I use augmented steam on chrome.

Maybe increasing the loading time a little bit will solve this.

**Comment by candela97** [comment]
You may have been timed-out. We put a 30 second delay in that case and try up to 2 times before giving up. Can you open the browser console (F12) and see if there're any HTTP 429 errors?

**Comment by djbnando** [comment]
Hi,
Thank you for your reply.

Yes, there are 429 errors:

Failed to load resource: the server responded with a status of 429 (Too Many Requests)

GET https://steamcommunity.com/market/priceoverview/?country=AR&currency=34&appid=753&market_hash_name=437020-Amp%20-%20Sonic%20Poison 429 (Too Many Requests)


I got those 2 errors with a 429 code.

**Comment by candela97** [comment]
Yeah, Steam started putting more restrictions on market requests a few months ago, and there's not much we can do. 

Does it only happen after page 2 or 3? How about if you reload page 1 after getting timed-out?

**Comment by djbnando** [comment]
It usually loads at least one full page, and then on the second or third page it will start to stop. Doesn't need to be necessarily on page number 2 or 3, it's the second or third page to load.
If I reload after being timed out, it will still be timed out, and it's worse because it will have to reload the pages that were previously loaded and it will be more information. It's just better to wait and see if it starts loading back, because sometimes it will, but sometimes don't, and then there's nothing to do.

Steam economy enhancer used to have this same problem while loading the inventory price for our items after some steam updates. I believe they have increased the time between each item to load it's price. Now the prices don't pop up almost all once, now it shows the price for the first item, after a short time it shows the prices for the second, a little more time and the third, and then it keeps going like this until it finishes the 1st page of the inventory. When you move to the inventoy's 2nd page, it happens the same.. 1st item, some delay, 2 item, delay, 3rd item and so on.
I believe they added a small delay between each one of the itens loaded to make it work. I remember getting timed out there too when steam started the changes.

**Comment by djbnando** [comment]
I don't 5 think it will be needed to go up to all those 5 seconds..
Maybe 2 to 3 seconds should be enough.
