### ISSUE TITLE
[FEATURE REQUEST] If no HowLongToBeat entry is found for a game, display info box that links to their submission page

### ISSUE THREAD

**Issue by conradsrc** [IsThereAnyDeal/AugmentedSteam#1600]
### Current Behavior (if any)
If the extension can't find a HowLongToBeat page for a given game, the info box just doesn't appear at all.

### Desired Behavior
Show the info box in its normal location with a message saying something to the effect of:
> We didn't find an entry for \<Game Title\> on HowLongToBeat.com, which means you get to be the first to [submit it to their website!](https://howlongtobeat.com/submit) Or maybe you [searched on their website](https://howlongtobeat.com/?q=Example) and found an entry for it that we didn't, in which case you can [submit a bug to our GitHub page!](https://github.com/IsThereAnyDeal/AugmentedSteam/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D)

### Motivation / Use Case for Changing the Behavior
* Encourages users to submit helpful information to one of the sites this extension is relying on and referencing.
* The absence of a HowLongToBeat page may be a bug (I've personally ran into this a few times) due to searching/matching issues with non-alphanumeric characters or diacritics. The presence of this notice on an even somewhat popular game may prompt a user to use the "HowLongToBeat search" link, find that the game *does* have an entry that AugmentedSteam failed to find, and then submit valuable feedback via the "GitHub Bug Report" link.
* Keeps store page layout more consistent.

**Comment by candela97** [comment]
> The absence of a HowLongToBeat page may be a bug (I've personally ran into this a few times) due to searching/matching issues with non-alphanumeric characters or diacritics. The presence of this notice on an even somewhat popular game may prompt a user to use the "HowLongToBeat search" link, find that the game does have an entry that AugmentedSteam failed to find, and then submit valuable feedback via the "GitHub Bug Report" link.

Do you remember which games have this issue? The way we map store pages to HLTB entries should be much more reliable now, so we'd definitely want to fix these.

**Comment by IDUnavailable** [comment]
> Do you remember which games have this issue? The way we map store pages to HLTB entries should be much more reliable now, so we'd definitely want to fix these.

Unfortunately I do not. If I come across one again in the future I'll write a specific issue on it.

**Comment by MxtOUT** [comment]
As long as we can't even find a good amount of games that are not mapped to an HLTB entry, I don't see a need for this.
Closing, but please reopen or comment if you do find some games with these problems.
