### ISSUE TITLE
Netflix as a subscription service

### ISSUE THREAD

**Issue by DarkAcreJack** [IsThereAnyDeal/AugmentedSteam#1603]
Hello! Feature request for adding "[Netflix Games](https://help.netflix.com/en/node/121442)" to the subscription service option. This morning I saw [Terra Nil](https://store.steampowered.com/app/1593030/Terra_Nil/) in my Steam Discovery Queue and I knew that it was available to any tier of Netflix subscriber (not a bad deal, we have the 5-dollar ad-supported tier and we get the full library of games).

Cheers!

**Comment by candela97** [comment]
Linking to #782.

I think the problem is ITAD specializes at recording price history for games, so this info might need to be outsourced from a reliable 3rd party, if there is one.

**Comment by zhouzi** [comment]
For Xbox Game Pass, Ubisoft+ and EA Play there's: https://aligueler.com/SubscriptionInfo/

Maybe they'd be open to add Netflix, here's the repository: https://github.com/alike03/SubscriptionInfo/

**Comment by MxtOUT** [comment]
We're tracking this in the linked issue
