### ISSUE TITLE
[BUG] Incorrect excluded from Family Sharing notice.

### ISSUE THREAD

**Issue by Starscre4M** [IsThereAnyDeal/AugmentedSteam#1604]
When a previously excluded from family sharing game removes this restriction the extension doesn't update this information, for example, Hogwarts Legacy, The Last of Us, Spider-Man Remastered and Spider-Man: Miles Morales, all of them shows the notice "This game is excluded from Steam's Family Sharing service.", which is outdated/incorrect information. 

### Expected Behavior
Not show the excluded from family sharing notice for games that doesn't have this restriction anymore.

### Actual Behavior
Shows the notice "This game is excluded from Steam's Family Sharing service.", which is incorrect/outdated information.

### Steps to Reproduce the Problem

Visit a steam game page that previously was excluded from family sharing, but not anymore, a few examples:
https://store.steampowered.com/app/990080/Hogwarts_Legacy/
https://store.steampowered.com/app/1888930/The_Last_of_Us_Part_I/
https://store.steampowered.com/app/1817070/Marvels_SpiderMan_Remastered/
https://store.steampowered.com/app/1817190/Marvels_SpiderMan_Miles_Morales/

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 112.0.1

**Comment by candela97** [comment]
There was an issue with the server and has been fixed. Games are checked once a month so let us know if there're others with the same problem after that, thanks!
