### ISSUE TITLE
[Bug] Large Steam wishlist hangs Chrome tab

### ISSUE THREAD

**Issue by PXAbstraction** [IsThereAnyDeal/AugmentedSteam#1608]
I cover indie games on YouTube and thus, have a large Steam wishlist (over 300 titles, I don't have a problem, you have a problem!) and when I open the wishlist in Chrome for more than 30 seconds or so, the tab will hang and I have to force close it. If I disable Augmented Steam or open the wishlist in an incognito window, the problem doesn't manifest. This has been happening for quite some time now. I'm not sure if anyone's reported this or if there's something I could do to otherwise mitigate it, but I wanted to report the issue. Thanks.

**Comment by candela97** [comment]
Can you try with only Augmented Steam enabled and nothing else? There have been similar reports but they're all about the wishlist not loading, not hanging the tab. For context, I've tested features on wishlists with over 3000 items before without issues, and my own wishlist has close to 500 items which I view almost daily.

**Comment by BloodShed-Oni** [comment]
I'm having something similar.

My wishlist (2107) loads reasonably fast (about 2-10 seconds).

But weird things will start to happen 8-27 seconds after the page is done loading, which can end with the tab hanging for a short time.

Things such as:
- Some entries appearing multiple times in the list
- As you scroll down the entries just stop (you only see the background color).
- Scrolling back to the top causes the page to be blank (you only see the background color), you can sometimes see only your avatar frame.

The list can reappear again at random (seem most consistent by leaving the tab alone for 3-10 minutes) and then works fine until the page is reloaded.

I've tested with other Edge extensions disabled, the bug(s?) still happen.

**Comment by candela97** [comment]
Hmm, this is starting to sound like #1115. I'll try playing around with the profiler to see what's going on.

**Comment by candela97** [comment]
@BloodShed-Oni Do you have "Show wishlist stats" enabled? Does disabling that option help?

**Comment by BloodShed-Oni** [comment]
> @BloodShed-Oni Do you have "Notes > On Wishlist" enabled? Does disabling that option help?

Looks like "Notes on Wishlist" was the cause.
I can scroll up and down (top to bottom) like crazy without the bugs appearing.
