### ISSUE TITLE
[BUG] Sub ID being used as app ID when checking for lowest price

### ISSUE THREAD

**Issue by FlaminSarge** [IsThereAnyDeal/AugmentedSteam#1609]
### Expected Behavior
ITAD ext should fetch lowest price for a sub ID rather than using the ID in the addToCart button as an app ID.

### Actual Behavior
ITAD ext finds the ID for the sub, treats it as an app ID, and fetches the wrong price info/links.

### Steps to Reproduce the Problem

  1. Go to https://store.steampowered.com/app/1603640/The_House_of_Da_Vinci_3/ and observe the steam app ID is 1603640, with the first purchase option having sub ID 568380 (as in the Add to Cart button source).
  2. Note the price displayed by the ITAD extension section is $0.00.
  3. Click on 'at Steam' in the ITAD extension section, which navigates to https://store.steampowered.com/app/568380/ (the wrong app).

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Chrome 113.0.5672.24 (Official Build) beta (arm64)

**Comment by candela97** [comment]
Yeah, this problem has been raised here https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/3271. You can file ITAD related issues like this in that repository in the future, thanks!
