### ISSUE TITLE
[FEATURE REQUEST] Disable Current Best and Historic Low Price

### ISSUE THREAD

**Issue by ShiroYasha139** [IsThereAnyDeal/AugmentedSteam#1610]
### Current Behavior (if any)
Price is converted from USD
### Desired Behavior
Ability to disable show price or convert it
### Motivation / Use Case for Changing the Behavior
The feature is essentially useless for me because it converts from USD and its usually higher than my regional currency on any of the stores.

**Comment by candela97** [comment]
I suppose if you have no use of this feature, you can disable it altogether; or just look past it if you're only looking for bundle info. I'm in the same boat as well and I use SteamDB's extension alongside for easy comparison.

If you _really_ want to you can use a userstyle manager like Stylus to hide it. The price history element has fixed class names.

**Comment by ShiroYasha139** [comment]
Thanks I solved it by

```
@-moz-document domain("steampowered.com") {
  .itad-pricing{
    display: none !important;
  }
}
```

**Comment by ShiroYasha139** [comment]
Sorry I misunderstood your first reply, I feel stupid now that I just needed to go to extension's settings and change it.
