### ISSUE TITLE
Добавьте функцию

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [IsThereAnyDeal/AugmentedSteam#1629]
добавьте чтобы когда заходишь в разработчика чтобы галочка автоматом была только игры, очень будет удобно . чтобы не видеть DLC и всякое другое
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/73518754/6143ca21-88a4-438b-adf3-cff6c2abcb7b)

**Comment by candela97** [comment]
You mean auto selecting "games" on search pages? Yeah that's quite useful but too specific for an option. A possible feature is to save and apply your last selection, see #808.

**Comment by candela97** [comment]
Closing as a duplicate for now. Feel free to provide more info if otherwise!
