### ISSUE TITLE
[REQUEST] Add country names to translation file

### ISSUE THREAD

**Issue by Blueberryy** [IsThereAnyDeal/AugmentedSteam#1631]
This might be most biggest things to add but yeah
https://github.com/IsThereAnyDeal/AugmentedSteam/blob/74d27ce4c27f7158d3270fb55a6f1836efe740ba/src/js/Options/Modules/Data/CountryList.js

**Comment by MxtOUT** [comment]
I don't get what you mean with that.
What would we use those translations for?

**Comment by Blueberryy** [comment]
> I don't get what you mean with that.
> What would we use those translations for?

These names used in options menu. For country prices

**Comment by Blueberryy** [comment]
![opera_Eshund6Vc0](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/36592509/4fe9722d-2fc1-46ce-adff-9b3e5e13d927)
here's screenshot of it
