### ISSUE TITLE
[BUG] Setting -"Install Steam" button- to -Replace with "View in Client"- completely blocks the extension from working

### ISSUE THREAD

**Issue by bubibubibub** [IsThereAnyDeal/AugmentedSteam#1654]
### Expected Behavior

The "Install Steam" button on Steam app pages should be replaced with "View in Client" and the rest of the extension should still work as intended.

### Actual Behavior

The extension loads infinitely on Steam app pages, Community page and the Wishlist and probably everywhere else and completely stops working until you change the setting again.

### Steps to Reproduce the Problem

  1. Set -"Install Steam" button- to -Replace with "View in Client"-
  2. Open any Steam app page or the Community page or the Wishlist or probably any other Steam page where the extension does anything
  3. Extension keeps loading and nothing from the extension is working/showing

### Specifications

  - Augmented Steam Version:  2.4.1
  - Browser Version:  Firefox 114.0.2 (64-Bit)

I am pretty sure this started happening today since I think I would have noticed it happening at once and I definitely opened a few Steam app pages yesterday as well. At first I didn't know if there was a general problem with Steam or similar but the store and the steamcommunity worked fine otherwise. 

I cleared the cache, deactivated all other extensions and I reinstalled the extension, nothing helped until I reset the settings to default. Then I started setting them to my preferred options again one by one and refreshed a Steam app page every time until I found the culprit.

**Comment by candela97** [comment]
Thanks for detailed report! Unfortunately we never anticipated this could fail...

**Comment by DrakeTrevlig** [comment]
Interesting. This is the problem that I came to the "issues" area to solve, and this was the solution needed. I changed from replacing with "view in client", to "hide", and without making any other changes the extension immediately worked normally.

**Comment by AndreyAleshin** [comment]
Can confirm this bug in Chrome. Noticed it yesterday. I reset my settings and the extension started loading. Then I found out by exception that the "Install Steam" setting causes the extension to load indefinitely. Changing this setting to "Show" or "Hide" helps.

**Comment by sahus22** [comment]
Can confirm this bug. Came here to report it myself, but instead found this "temporary fix"

**Comment by Ryzhehvost** [comment]
I also suffer from this bug, thanks finding what causes it.

**Comment by zouhair** [comment]
Oh my god thank you, I was going insane

**Comment by NatParable** [comment]
I second zouhair. Was really pulling my hair out confused as to why it wasn't working.

**Comment by BO7AMMOOD** [comment]
Nothing I've tried helped me solve this issue. Not changing the ("Install Steam" button) to show or hide, not resetting the settings, not clearing the cache, not uninstalling and reinstalling, and not even disabling every other extension I have in Firefox. Any idea what might be causing this?

**Comment by BO7AMMOOD** [comment]
Oh I see so that's why the fix mentioned here didn't work, because it was already fixed XD

Thanks! And thanks to Mandydeth for figuring the solution to the current issue out!
