### ISSUE TITLE
[FEATURE REQUEST] Hide all comments in activity feed

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1661]
### Current Behavior (if any)

In the Friend Activity, several comments are displayed after each news, which slows down reading the news.

### Desired Behavior

Comments are hidden by default. If the user is interested in comments on a particular news, he can go to the news page. Or expand the collapsed spoiler with comments that are displayed on the site by default.

### Motivation / Use Case for Changing the Behavior

I subscribe to updates from developers and publishers regarding specific products. I am interested in the official statements of companies, not the opinions of those whom I did not subscribe to, and whose opinions I am not interested in in most cases.

I have "Friend Activity Feed" / "Hide comments under all group announcements by default" checked, but this setting seems to be about something else because the comments are on https://steamcommunity.com/id/%username%/home/ are still displayed.

**Comment by candela97** [comment]
With that option enabled, comments under **group announcements** should be hidden by default. If not, please share a screenshot. I don't think it makes sense to hide comments under friend activities, since that was not the original request, and if you don't want to see a particular type of activity, you can disable it in Friend Activity Settings.

**Comment by candela97** [comment]
Judging by your comment in the other issue, I guess you are running into #1654. Let me know if that's not the case.

**Comment by Korb** [comment]
> please share a screenshot.

![2023-06-27_08-19-31](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/3509797/e17a7da9-5d90-4ee7-a22e-60da1a9996ee)

![2023-06-27_08-22-08](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/3509797/6ae50c63-32dd-4e17-9757-3540a43adff4)

**Comment by candela97** [comment]
See the linked issue above and check if the extension is actually working.
