### ISSUE TITLE
[FEATURE REQUEST] Multiple Steam Gifts Send to Mail at Once

### ISSUE THREAD

**Issue by SpeedXGG** [IsThereAnyDeal/AugmentedSteam#1674]
Sending a batch of multiple Steam Gifts at once to one email. Steam doesn't allow sending many gifts to one email unless adding a "." in between mail name (e.g. test@gmail.com --> te.st@gmail.com or test+XX@gmail.com(XX being random number) --> test+543@gmail.com

**Comment by candela97** [comment]
We've had a long standing policy to not run any scripts on checkout-related pages, so this is likely a wontfix for us.
