### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BeansOnButter** [IsThereAnyDeal/AugmentedSteam#1675]
### Expected Behavior
Quick-sell: Automatically put an item up for sale
Instant-Sell: Automatically sell the item to the highest asking price

### Actual Behavior
Neither button appearing

### Steps to Reproduce the Problem

  1. Go to your inventory
  2. Click on anything marketable (Might only be affecting trading cards)

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Opera GX - LVL 5 (core: 99.0.4788.86)

**Comment by candela97** [comment]
Can you check the browser console and see if you're getting timed-out (429 Too Many Requests) ?

**Comment by BeansOnButter** [comment]
> Can you check the browser console and see if you're getting timed-out (429 Too Many Requests) ?

I'm not seeing that message, but I am seeing this:

caught (in promise) TypeError: Cannot set properties (AugmentedSteam.js:162:17) of null (setting 'textContent')
    at O._handleInstallSteamButton (AugmentedSteam.js:162:17)
    at O.init (AugmentedSteam.js:296:24)
    at run.constructor.run (Page.js:97:24)

It's all in red text, with every "AugmentedSteam.js:162:17" being underlined

I don't know what any of that means, but I hope it helps

**Comment by candela97** [comment]
Then you're running into #1654, please see that issue for details.

**Comment by BeansOnButter** [comment]
> Then you're running into #1654, please see that issue for details.

But there's still the bug I'm running into

**Comment by BeansOnButter** [comment]
Ignore that completed, that was an accident

**Comment by candela97** [comment]
Which bug?

**Comment by BeansOnButter** [comment]
> Which bug?

The one I talked about, the Quick-Sell and Instant-Sell buttons aren't showing up

**Comment by candela97** [comment]
Are you sure the extension is loading? There should be a "Feature loading complete" message in the browser console.

**Comment by BeansOnButter** [comment]
> Are you sure the extension is loading? There should be a "Feature loading complete" message in the browser console.

I'm not seeing it

**Comment by candela97** [comment]
Then see #1654 😅

**Comment by candela97** [comment]
Just to clarify, the error is gone but the feature is still not working?

**Comment by BeansOnButter** [comment]
> Just to clarify, the error is gone but the feature is still not working?

Sorry, forgot to get back to you, I switched the "Install Steam Button" to off and that fixed it, should probably still fix that bug regardless

**Comment by candela97** [comment]
It'll be fixed in the next version (see the linked PR in that issue).
