### ISSUE TITLE
[BUG] Market Transactions component unavailable in Firefox

### ISSUE THREAD

**Issue by nootey** [IsThereAnyDeal/AugmentedSteam#1680]
### Expected Behavior

When opening community market tab, a "Market Transactions" component should be present on the right side of popular items component. It is present in a chromium browser, but not on Firefox.

### Actual Behavior

Market Transactions component is not present.

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 114.0.2

**Comment by candela97** [comment]
Check if you're running into #1654 first to make sure the extension is working on FF.

**Comment by nootey** [comment]
Setting the option to hide did seem to resolve the issue, but the extension worked everywhere else. Anyway, thanks for the quick solution.

**Comment by candela97** [comment]
"hide" doesn't do anything at the moment. You can revert it to the default until it's fixed in the next version.
