### ISSUE TITLE
[FEATURE REQUEST] Option To Filter Out Items Without Buyers

### ISSUE THREAD

**Issue by BeansOnButter** [IsThereAnyDeal/AugmentedSteam#1695]
### Current Behavior (if any)
All marketable items visible
### Desired Behavior
An option to filter out any items that don't have any buyers, could locate the filter button to be beside the rest
### Motivation / Use Case for Changing the Behavior
Mountains of Payday 2 skins that nobody's buying for

**Comment by candela97** [comment]
Do you mean in your inventory? Unfortunately, this will amount to a lot of requests and is therefore not feasible. Plus market endpoints are now heavily rate-limited, you'll run into timeouts in no time.
