### ISSUE TITLE
[FEATURE REQUEST] Add app' URL var to custom link syntax

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1696]
### Current Behavior (if any)
Currently, the user can only use the [ID] and [NAME] variables when filling in the "URL" field in the "Options for information from 3rd-party sites" section of the Augmented Steam add-on settings.

### Desired Behavior
I want to be able to add links to web archive sites. But for this, I must be able to add variables with values like https://store.steampowered.com/app/1700.

### Motivation / Use Case for Changing the Behavior
Offer Purpose: To be able to view previous revisions of game pages and view descriptions of games blocked for sale in my account region.

![Screenshot 2023-07-09 at 11-19-32 Site Error](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/3509797/81fa2953-9c22-4587-89cd-cb86366c1f5f)

**Comment by candela97** [comment]
Since only the appid part is dynamic, you can do something like this:
![螢幕擷取畫面 2023-07-09 185622](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/54083835/c5a60bec-44cc-4c84-b465-a18d568b6394)
