### ISSUE TITLE
[BUG] Too many strings got deleted from the Polish language file, even those that are still used and have translations

### ISSUE THREAD

**Issue by przemo20** [IsThereAnyDeal/AugmentedSteam#1697]
### Expected Behavior
The strings that have already been translated should be displayed in Polish.

### Actual Behavior
The text is displayed in English.

The list of strings that got cut (it may be incomplete / have errors):
```
addtocart_dialog: desc and checkout
apppage_eabanner
empty_wishlist: confirm
external_funds
leave_admin_confirm: currently_admin
in_cart
inverse
steam-itad
on_wishlist
hideannouncementcomments
confirmdeletecomment
profile_pinned_bg
user_notes: synced_storage
maintainers
with_help_of
contributors
user_note: not_enough_space_desc, close_on_storage_desc, storage_warning_desc and save_synced_storage
custom_amount_text
youtube_gameplay
```
Commit: https://github.com/IsThereAnyDeal/AugmentedSteam/commit/5e88f40b1525a56ccb1ab4ed5df0ff4ef

### Steps to Reproduce the Problem

  1. 
  2. 
  3. 

### Specifications

  - Augmented Steam Version: 2.4.1 (Firefox) / 2.5.0 (Chrome)
  - Browser Version: Firefox 115.0.1 (64-bit) | Chrome 114.0.5735.199 (64-bit)

**Comment by MxtOUT** [comment]
This is intentional.
The strings were modified in the reference English localization file so they are marked as fuzzy on POEditor.
When importing the strings for the other languages, we exclude these fuzzy strings because the meanings of the strings may have changed.

**Comment by candela97** [comment]
Hmm... some of these strings haven't changed in years, so there must be something else that's causing them to be discarded. In any case, you can paste them back and they should get picked up again during the next pull.

**Comment by candela97** [comment]
I see the "fuzzy" state can be toggled on/off by translators, make sure that toggle is OFF after translating!
