### ISSUE TITLE
[FEATURE REQUEST] user note not saved until you refresh the page

### ISSUE THREAD

**Issue by Marblebishop** [IsThereAnyDeal/AugmentedSteam#1702]
### Current Behavior (if any)
In the store page you click add note, write your note, click save button, but the note is not really saved. You have to refresh the page or the note is gone when you close the page.
### Desired Behavior
add a refresh/update behavior on the 'save' button

**Comment by candela97** [comment]
Is this meant to be a bug report? If so I can't reproduce. After you hit save, the note should appear under the queue buttons, which also means the note has been saved.

Please open a new issue using the bug template if you're still having issues, and provide more info about your environment and the steps to reproduce.
