### ISSUE TITLE
[BUG] Stuck at "loading data"

### ISSUE THREAD

**Issue by maxens-wlfr** [IsThereAnyDeal/AugmentedSteam#1703]
### Expected Behavior

The green dot at the top of the page goes to the right and things work

### Actual Behavior

the dot is stuck on the left, hovering with the mouse shows 'Augmented Steam loading data" and nothing is active

### Steps to Reproduce the Problem

  1. Install the extension
  2. Open Steam

### Specifications

Here's the browser console if it helps
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/86591276/fbe81847-6806-4341-aefe-1a67a5206def)

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 115.0.1 (64-bit)

**Comment by candela97** [comment]
Duplicate of https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1654. The new version has been submitted and is pending review on AMO.
