### ISSUE TITLE
[BUG] Badges page doesn't show all the badges with card drops remaining when sorted by alphabet.

### ISSUE THREAD

**Issue by Necronomicron** [IsThereAnyDeal/AugmentedSteam#1710]
### Steps to Reproduce the Problem

  1. Show «Badges With Card Drops Remaining».
  2. Ctrl + F, type «Play». (In my case 271 found.)
  3. Sort by alphabet.
  4. F3. (Now only 246 found.)

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Firefox 115.0.2 x64

**Comment by candela97** [comment]
This is expected, because showing "Badges With Card Drops Remaining" will filter out badges that don't have any drops, e.g. sales badges and all those special event badges.

**Comment by Necronomicron** [comment]
> This is expected, because showing "Badges With Card Drops Remaining" will filter out badges that don't have any drops, e.g. sales badges and all those special event badges.

You didn't understand. If there is «Play» button, the game has undropped cards.

**Comment by candela97** [comment]
Oh, then you need to sort by alphabet first because it loads a new page.

**Comment by Necronomicron** [comment]
> Oh, then you need to sort by alphabet first because it loads a new page.

Same result.
