### ISSUE TITLE
[BUG] Unable to add new notes or edit old ones

### ISSUE THREAD

**Issue by FidRay16** [IsThereAnyDeal/AugmentedSteam#1718]
### Expected Behavior
 1. I click "Add note"
 2. A window pop up
 3. I type some text
 4. I click "Save"
 5. A window closes and the text i wrote appears under the wishlist\subscribe\hide buttons

### Actual Behavior
1-4. The same
5. Nothing happens and after reloading the page (F5), the note is empty

### Steps to Reproduce the Problem
Idk, may be its 'cause I add the notes often. But I can't add any notes for about four days
### Specifications
Sory for the bad Eng 

  - Augmented Steam Version: 2.5.0
  - Browser Version: Google Chrome Version 115.0.5790.102 (Official Build) (64-bit)

**Comment by candela97** [comment]
I think you've reached storage limits, but there're a bug right now that prevents the dialog that explains this from showing. Try switching storage methods from the options page and see if that helps.

**Comment by FidRay16** [comment]
> I think you've reached storage limits, but there're a bug right now that prevents the dialog that explains this from showing. Try switching storage methods from the options page and see if that helps.

How to switch storage methods? Where and how? In browser? Or extension options or windows? I didn't find anything at extension options

**Comment by candela97** [comment]
Extension options. Click on Store > Notes from the sidebar to scroll to that section.
