### ISSUE TITLE
[BUG] Game "Firework" is linked to a wrong title

### ISSUE THREAD

**Issue by zhangyuesai** [IsThereAnyDeal/AugmentedSteam#1721]
### Expected Behavior
The "Current best" and "Historical low" links above the purchase button of the game "Firework" (SteamID=[1288310](https://store.steampowered.com/app/1288310/)) should take me to the correct IsThereAnyDeal [page](https://isthereanydeal.com/game/yanhuofirework/info/) .

### Actual Behavior
Instead, they take me to a wrong game "Stormworm+" (SteamID=[449240](https://store.steampowered.com/app/449240/)) [page](https://isthereanydeal.com/game/stormwormplus/info/) .

### Steps to Reproduce the Problem

  1. Just click on the misleading links.

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Firefox 116.0 on Windows.

**Comment by candela97** [comment]
I've filed https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/3425. You can post ITAD-related issues in that repository in the future, thanks!
