### ISSUE TITLE
[BUG] Incompatability with mullvad browser?

### ISSUE THREAD

**Issue by catgaming49** [IsThereAnyDeal/AugmentedSteam#1727]
### Expected Behavior

Pricing information displays properly on page

### Actual Behavior

Augmented steam fails to initialize with:
Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

### Steps to Reproduce the Problem

  1. Install augmented steam on mullvad browser
  2. Got to to any steam store game page

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Mullvad browser 12.5.2 (64 bit)

### Additional info

The console did produce a message indicating that I should set webextensions.storage.sync.enabled to true in about:config although this did not fix the issue.

**Comment by candela97** [comment]
My guess is you need to enable IndexedDB as well.

**Comment by catgaming49** [comment]
> My guess is you need to enable IndexedDB as well.

Yeah that was it. Sorry for creating an issue kind of unrelated to the extension itself but thanks for the help!
