### ISSUE TITLE
[BUG] Discount percent filter not working

### ISSUE THREAD

**Issue by evil-pechenka** [IsThereAnyDeal/AugmentedSteam#1730]
### Expected Behavior

Entering the minimum discount value - results with higher discounts are displayed.

### Actual Behavior

Entering the minimum discount value - search results disappear.

### Steps to Reproduce the Problem

  1. I enter Steam search.
  2. I input the minimum discount value.
  3. Search results disappear.

See attached video

https://github.com/IsThereAnyDeal/AugmentedSteam/assets/109512933/b999ee9b-42be-42ca-a8ab-ea0aec502c22

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Google Chrome 116.0.5845.110

**Comment by candela97** [comment]
Yeah, Steam broke this right after it was released. Linked PR will fix this.
