### ISSUE TITLE
[BUG] Wrong currecy symbol for GBP=>BRL in current best price

### ISSUE THREAD

**Issue by rcapile** [IsThereAnyDeal/AugmentedSteam#1734]
### Expected Behavior
Show current best price in Brazilian real

### Actual Behavior
Show the current best value in pounds with an R$ (for Brazilian reals)

### Steps to Reproduce the Problem
Access the Starfield page in Steam store in Brazil 

https://store.steampowered.com/app/1716740/Starfield/

The actual price in GamesPlanetUK (with the coupon) is £51.29, which would be ~R$ 319.37

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/189857/56ce3126-6732-4390-aed7-7802d202b420)

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Version 116.0.5845.140 (Official Build) (64-bit)

**Comment by candela97** [comment]
I vaguely remember there was a similar issue like this but I can't find it right now.

It might have something to do with failing to load currency conversion rates.

**Comment by MxtOUT** [comment]
I investigated this and it's a problem with the response of the AS API server

**Comment by MxtOUT** [comment]
Should be fixed now!
