### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iFatihUcar** [IsThereAnyDeal/AugmentedSteam#1735]
### Steps to Reproduce the Problem

  1. If the number has four digits or more, it mistakes the thousand separator for a decimal point, displaying the values incorrectly. 
  2. To give an example, while the price of RDR2 is 1,012.00 ₺ on the GameBillet website, the extension shows it as 1.01 ₺.

**Comment by candela97** [comment]
https://isthereanydeal.com/game/reddeadredemptionii/info/?country=TR

This is an ITAD issue, but I think it's just this game, unless you have others?

**Comment by iFatihUcar** [comment]
I don't have any other suggestions, thank you. Also, it's not just related to the game; if both a comma and a dot are found in the price at the same time, it causes a problem.

**Comment by candela97** [comment]
This should be fixed.
