### ISSUE TITLE
[BUG] Spelldrifter is not showing up in collection

### ISSUE THREAD

**Issue by Kallan007** [IsThereAnyDeal/AugmentedSteam#1743]
### Expected Behavior
Spelldrifter should appear on Steam in the collection for Epic

### Actual Behavior
Spelldrifter is not showing up in the collection

### Steps to Reproduce the Problem

  1. Open https://store.steampowered.com/app/1766750/Spelldrifter/
  2. The extension should show that the game is in the collection for Epic
  3. 

### Specifications

  - Augmented Steam Version: Version: 2.5.0
  - Browser Version: Microsoft Edge Version 116.0.1938.76 (Official Build) (64-bit)

**Comment by MxtOUT** [comment]
Sadly this is an ITAD issue that won't be fixed until new ITAD is live.
You can see on the game page (https://isthereanydeal.com/game/spelldrifter/info/) that the "Reviews" section with a link to the Steam reviews is missing.
This is how it should normally look like: 
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/14999077/712a7e18-8df2-4b98-9c82-134a2f0a714e)
