### ISSUE TITLE
[BUG] Games synced to waitlist do not inherit default settings in some cases

### ISSUE THREAD

**Issue by Bobogoobo** [IsThereAnyDeal/AugmentedSteam#1745]
### Expected Behavior

All games synced from my Steam wishlist to my ITAD waitlist, that were not already on the latter, should use the default settings that I set on ITAD.

### Actual Behavior

Some games do not use my default settings, and instead notify me on every discount.

### Steps to Reproduce the Problem

  1. Set default price cut notification on ITAD to something other than 0.
  2. Add game to Steam wishlist - often this issue seems to occur when the game was not yet available on Steam at the time of wishlisting, so try wishlisting an upcoming game, but that doesn't seem to account for every case.
  3. Check ITAD - game is added to waitlist with price cut notification set to 0%. Not sure if this happens upon the game being synced or upon the game being released, or some other event.

### Specifications

  - Augmented Steam Version: any - currently on 2.5.0
  - Browser Version: any - currently on Chrome 116.0.5845.187

Note: this has been happening for more than two years, so it must be a long-standing bug. Potentially related to #820 but this seems to be an issue with importing specifically. I'm really sick of having to change so many games, please fix soon. Today I got an email with 100 items and most of them have this issue, and there aren't even that many sales right now.

**Comment by candela97** [comment]
Please file a new issue if there're still problems with the new ITAD, thanks!
