### ISSUE TITLE
[BUG] Augmented Steam Stuck Loading

### ISSUE THREAD

**Issue by forealdo25** [IsThereAnyDeal/AugmentedSteam#1746]
### Expected Behavior
When a page on Steam loads, Augmented Steam is supposed to load along with it

### Actual Behavior
Starting today, I noticed that Augmented Steam gets stuck loading when I load a page on Steam. This happens on my main PC and my Surface tablet. I tried to clear the cache to see if that fixed it but to no avail.

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Google Chrome 117.0.5938.63
![chrome_htrCecRkyX](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/47656512/b7ac0d90-1730-4937-a38a-faada2ab5d32)
![chrome_OvuphIxESo](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/47656512/0b93019c-86f4-4544-8af7-4f92369a6c0b)

**Comment by forealdo25** [comment]
I found another bug report, #1748 , that seemed to be having the same issue as me. I disabled "Replace account name with community name" as they mentioned, ad Augmented Steam loaded again.

**Comment by MxtOUT** [comment]
We'll track this in #1748
