### ISSUE TITLE
[BUG] Enabling "Replace account name with community name" while logged in causes Augmented Steam to not load

### ISSUE THREAD

**Issue by Mandydeth** [IsThereAnyDeal/AugmentedSteam#1748]
### Expected Behavior
Augmented Steam loads as usual when visiting website

### Actual Behavior
Augmented Steam fails to load when visiting website 

### Steps to Reproduce the Problem

  1. Log in to Steam website
  2. Ensure "Replace account name with community name" option is toggled
  3. Augmented Steam will fail to load

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Mozilla Firefox 117.0.1 (64-bit)
  
### Solution
Initially I thought it might be an add-on causing the issue, so I turned them all off and suffered from the same issue. I then went to a Private tab and attempted again; this time Augmented Steam loaded successfully. I tried going back to a regular tab and logging out and Augmented Steam started functioning again. Upon logging in, once again AS would not load. I attempted to clear cookies/cache and log-in once more, AS would not load. After playing around with the settings and disabling "Replace account name with community name", AS loaded properly.

**Comment by Limboso** [comment]
Exactly same problem for me on Chrome. I disabled the option you mentioned and it worked again.

**Comment by MxtOUT** [comment]
Yes, like @Mandydeth already found out, temporarily disabling the "Replace account name with community name" option will make AS work again.

Luckily we've been working on a new release anyway, so I hope that in this evening we can submit the new version to the respective web stores.

**Comment by BO7AMMOOD** [comment]
Thanks Mandydeth! That worked for me!

**Comment by markwr** [comment]
Thanks!

**Comment by JACKIEXIA** [comment]
@Mandydeth Thx for your solution dude :)
