### ISSUE TITLE
[BUG] Augmented Steam Plugin seem to have stopped working as of september 13 2029

### ISSUE THREAD

**Issue by Archont1978** [IsThereAnyDeal/AugmentedSteam#1751]
### Expected Behavior
Pluign should load/be active

### Actual Behavior
Plugin not loading at all

### Steps to Reproduce the Problem

  1. Simply browsing steampowered.com
  2. 
  3. 

### Specifications
Sorry for not submitting much information. Submitting a few screenshots I think can better explain the behaviour.

![console](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/121167238/dffd465e-2fd4-42bc-a0fc-53f744f49184)
![extensions](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/121167238/bc59cf46-9da1-48aa-af1c-9aa1650e4947)

  - Augmented Steam Version: 2.5.0
  - Browser Version: Librewolf 117.0-1

**Comment by Timekiller** [comment]
Plugin not loading at all

**Comment by Sansming** [comment]
#1748
