### ISSUE TITLE
[BUG] Doesn't load data in Firefox

### ISSUE THREAD

**Issue by waffletacos** [IsThereAnyDeal/AugmentedSteam#1754]
### Expected Behavior
It should load data for the Steam site

### Actual Behavior
It doesn't load the data if you are logged into the Steam website..  The green progress icon stays to the left instead of sliding to the right to show it loaded.  Hovering over it shows loading data.  If you are not logged into Steam webite it works fine.  Going into options and unchecking Replace account name with community name fixes it.  

### Steps to Reproduce the Problem

  1. Just open Firefox and go the Steam page.
  2. Log into Steam website.

### Specifications

  - Augmented Steam Version:  2.5
  - Browser Version:  Firefox 117.0.1 (64-bit)

**Comment by candela97** [comment]
Please see the pinned issue. Workaround here: https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1748#issuecomment-1717021702
