### ISSUE TITLE
[BUG] Store price comparison not showing up 

### ISSUE THREAD

**Issue by probablypedro** [IsThereAnyDeal/AugmentedSteam#1755]
### Expected Behavior
Prices from other stores showing up above the current Steam store price, like in Chrome, in "Best deal right now at this website" and  "Historical low price" format.

### Actual Behavior
A link to a cheaper previously approved website is nowhere to be found.

### Steps to Reproduce the Problem

  1. Clicked multiple games, none of them had the information.
  2. Looked up specific games already owned on Steam and not owned in different stores (Nuuvem, Green Man Gaming) that had previously appeared where they should, yet the Steam store does not show those games as being on sales anywhere else.
  3. Installed the extension on Firefox, tried both with the regular settings and importing the settings from a Chrome profile that has showed the prices correctly in the past. 

### Specifications
 *Looked up specific games already owned on Steam and not owned in different stores (Nuuvem, Green Man Gaming) that had previously appeared where they should, yet the Steam store does not show those games as being on sales anywhere else.
  *Installed the extension on Firefox, tried both with the regular settings and importing the settings from a Chrome profile that has showed the prices correctly in the past. 
  *Chrome version also seems to not show the price where it should after testing.
  *SteamDB still works and shows "Previously lower price" on any game page. 
 * This issue was found when setting up Firefox. I do not know how long it has been happening on Chrome, but this is the first time I see it. I know it was working fine last week, and have not added any new extensions nor messed with any Steam settings since. IsThereADeal and SteamDB are properly logged in.  
  - Augmented Steam Version: 2.5.0
  - Browser Version: 117.0.1 (64-bits) (firefox), Versão 116.0.5845.182 (64 bits) (Chrome) 
 
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/144948828/c27a05d5-260d-4cf9-88f9-742864a24a65)

Please reply with any requests for information, or if it looks like there's something wrong on my end.

**Comment by candela97** [comment]
Please see the pinned issue. Workaround here https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1748#issuecomment-1717021702.
