### ISSUE TITLE
[BUG] _replaceAccountName TypeError

### ISSUE THREAD

**Issue by JeBuSBrian** [IsThereAnyDeal/AugmentedSteam#1757]
### Expected Behavior
accountName should handle if logoutMode returns null

### Actual Behavior
TypeError on AgumentedSteam.js line 200

### Steps to Reproduce the Problem

  1. Login to steampowered.net
  2. View console errors

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Chrome 116.0.5845.188

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/1660837/eb8bce72-2aca-4fa8-9cf6-3c6fc0aab378)

**Comment by MxtOUT** [comment]
#1748
