### ISSUE TITLE
[BUG] Augmented Steam Fails to Load - Error on Account Name

### ISSUE THREAD

**Issue by Alamei** [IsThereAnyDeal/AugmentedSteam#1759]
### Expected Behavior
Augmented Steam loads and performs its normal extension functionality.

### Actual Behavior
Augmented Steam gets stuck in its loading phase and throws an error in the console trying to get the account name on line 200 of AugmentedSteam.js (Firefox):
const accountName = logoutNode.textContent.trim();

Or this line in app.js in Chrome:
const e = document.querySelector("#account_dropdown .persona.online")
                  , t = e.textContent.trim()
                  , s = document.querySelector("#account_pulldown").textContent.trim();

### Steps to Reproduce the Problem

  1. Open any page on the Steam store website. 

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Firefox Developer Edition 118.0b8 (64-bit) / Chrome 117.0.5938.62 (Official Build) beta (64-bit)

**Comment by MxtOUT** [comment]
#1748
