### ISSUE TITLE
[BUG] Store Filters Don't Appear / Null Pointer Error

### ISSUE THREAD

**Issue by SentientScythe** [IsThereAnyDeal/AugmentedSteam#1761]
### Expected Behavior
Store filters will appear

### Actual Behavior
The store filters do not appear. There's a null pointer error in the browser console.
Line 200 of AugmentedSteam.js is throwing the error. I believe an update to the Steam website UI removed the document node that was previously used.

### Steps to Reproduce the Problem

  1. Open the steam store search (https://store.steampowered.com/search)

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Firefox 117.0.1

**Comment by SentientScythe** [comment]
I can workaround the error temporarily by disabling the "Replace account name" option in the extension's settings.

**Comment by MxtOUT** [comment]
#1748
