### ISSUE TITLE
[ERROR] Uncaught TypeError

### ISSUE THREAD

**Issue by iFatihUcar** [IsThereAnyDeal/AugmentedSteam#1762]
### Steps to Reproduce the Problem

I have got this error from console screen. "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at G._replaceAccountName (app.js:1:46204)
    at G.init (app.js:1:48076)
    at run.constructor.run (app.js:1:70361)"

### Specifications

  - Augmented Steam Version: Augmented Steam v2.5.0
  - Browser Version: chrome 116.0.5845.188

**Comment by Jordy3D** [comment]
Additional information/temporary way around it
Disable "replace account name with community name" in the settings.

**Comment by MxtOUT** [comment]
#1748
