### ISSUE TITLE
[BUG] Note function doesn't appear anymore in store page.

### ISSUE THREAD

**Issue by HaikenEdge** [IsThereAnyDeal/AugmentedSteam#1765]
### Expected Behavior
There's a button to add notes to games on the store page.

### Actual Behavior
The button no longer exists.

### Steps to Reproduce the Problem

  1. Open store page for a game.

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Google Chrome 116.0.5845.188 (Official Build) (64-bit)

**Comment by Gensokyo1995** [comment]
update to Vrsion: 2.6.0

**Comment by HaikenEdge** [comment]
> update to Vrsion: 2.6.0

How do I force an update? I wanted to try that first, but I couldn't find any such option in the settings.

**Comment by Gensokyo1995** [comment]
> > update to Vrsion: 2.6.0
> 
> How do I force an update? I wanted to try that first, but I couldn't find any such option in the settings.
you can update in chrome store

**Comment by HaikenEdge** [comment]
> > > update to Vrsion: 2.6.0
> > 
> > 
> > How do I force an update? I wanted to try that first, but I couldn't find any such option in the settings.
> 
> you can update in chrome store

Tried that, wasn't there either.

Ultimately, I had to force an update to my browser and reboot it.
