### ISSUE TITLE
[BUG] Fullscreen videos shake / move repeatedly to the right and back to the center.

### ISSUE THREAD

**Issue by BuryTomorrow12** [IsThereAnyDeal/AugmentedSteam#1769]
### Expected Behavior

Play a web video on full screen mode without it moving as if it was "shaking", like moving to the side and back to original position repeatedly, in rapid successions. 

It's a bit hard of explaining without seeing it happen, but the video playback displaces to the right and crops a portion of it, then comes back to center position. This happens many times a second. 

### Actual Behavior

When playing a web video on full screen mode, said video "shakes", constantly tilting between centered position and moving to the right. 

### Steps to Reproduce the Problem

  1. Head to any steam store product page
  2. Play any game's video trailer on fullscreen
  3. Wait a couple seconds until the video controls disappear from the bottom part
  4. At this point, the issue will most likely come up.

### Specifications

  - Augmented Steam Version: 2.6.0 (2.5.0 as well)
  - Browser Version: Opera GX 101.0.4843.85 (happens on any 101 as well, but didn't happen on versions 100 or older). 102 has just been released, will test and edit.

### Additional info

  1. Disabled every other addon I have, and narrowed the issue down to Augmented Steam. No other extension causes this. **Tried disabling all and every of AS's options**, even the ones that could affect video instances, nothing had any effect, issue still happens.
  2. **This also happens with some Youtube videos** - for some reason, AS is conflicting with videos being played on fullscreen mode, even outside of steam, in Opera GX.
  3. If I **disable Opera GX's hardware acceleration, the issue goes away.** This has been my temporary workaround until now.
  4. **If I move the mouse cursor to have the video controls come back up, the issue goes away**, until the controls hide back. Then, it reappears.
  5. If needed, I'll try to record the issue and upload a video.
  6. I'm using an ultrawide, 3440x1440 100hz gsync monitor, with gsync enabled both on fullscreen and windowed mode. I don't know it that can be helpful in any way.
  7.  The addon's being installed through an embed extension in Opera / Opera GX that allows users to install Chrome extensions (and works perfectly with any other Chrome extension like SteamDB, for example).
  8. Older versions of Opera GX can be found here if testing is needed: https://get.opera.com/ftp/pub/opera_gx/
  9. I'm fully aware Opera GX isn't officially supported, but I beg you to at least take a look at this, it's driving me nuts.

![21958604 055000003_image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/40051760/6cf2cd50-01ab-47b1-b52a-a49d49507010)

**Comment by candela97** [comment]
If it also happens on YouTube, I can't see a relation to AS. Extensions can only run scripts on url patterns specified in the manifest, and AS doesn't even have host permissions for youtube.com. Hardware acceleration could play a part, since iirc Chrome had similar issues a few years ago, so it's likely an issue with Opera.

**Comment by candela97** [comment]
Sadly, I tried but couldn't reproduce. I suggest testing on a new browser profile.
