### ISSUE TITLE
[FEATURE REQUEST] Auto-redirect to the user-set language

### ISSUE THREAD

**Issue by TsukiZero** [IsThereAnyDeal/AugmentedSteam#1771]
### Current Behavior (if any)
When opening a link with the language parameter in the URL, it creates a rather annoying moment where you have to manually either trim the language parameter from the url or click to go to the  Steam page that matched my language

### Desired Behavior
It could have the ability to go beyond displaying the warning "You are viewing Steam in X language", and redirected to the proper page without the language parameter.

### Motivation / Use Case for Changing the Behavior
Some people share links poorly on Twitter, forums, or even Google may provide the result with a language parameter attached to the URL. This helps deal with that.

**Comment by candela97** [comment]
Content blockers widely support the `removeparam` filter syntax to achieve this. A filter like this would do:
`||store.steampowered.com^$removeparam=l`

**Comment by TsukiZero** [comment]
> Content blockers widely support the `removeparam` filter syntax to achieve this. A filter like this would do: `||store.steampowered.com^$removeparam=l`

Really, that's a thing? Didn't know, thanks for this info. But still would be a good thing to implement to prevent people going through the hell that is searching for a solution elsewhere.

**Comment by candela97** [comment]
If we add it here, it'll only work on Steam domains because that's where AS has host permissions. A content blocker is the superior tool for such funtionality IMO, since it can easily be tweaked if something breaks and works everywhere.

**Comment by TsukiZero** [comment]
Alright then... Suppose we should close this or keep it open for...?

**Comment by candela97** [comment]
If that filter works as expected, it's not likely we're going to duplicate the effort here. Feel free to comment if you have further questions!
