### ISSUE TITLE
[BUG] The Edge extension version is outdated and cannot load

### ISSUE THREAD

**Issue by LeonardoTArtist** [IsThereAnyDeal/AugmentedSteam#1772]
### Expected Behavior
The extension load

### Actual Behavior
The Edge extension version is outdated and cannot load

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Edge
  
### Solution
I had to install the version from the Chrome Web Store, what is in the Edge store is the old version

**Comment by MxtOUT** [comment]
That's entirely Microsoft's responsibility to accept and verify our update, so the best you can do is wait
