### ISSUE TITLE
[TASK] Update Edge version

### ISSUE THREAD

**Issue by SiTWulf** [IsThereAnyDeal/AugmentedSteam#1775]
### Task Description
Simply update the Egde version in Microsoft Store

### Motivation
The 2.5.0 version NOT work in Edge

**Comment by SiTWulf** [comment]
I can't understand why.
Edge version have 66.9K users and get the Old version
Firefox version have only 46K users and get the New version

**Comment by MxtOUT** [comment]
That is entirely Microsoft's fault, we submitted all versions at the same time
