### ISSUE TITLE
Edge Version won't work anymore [BUG]

### ISSUE THREAD

**Issue by da3m0nz** [IsThereAnyDeal/AugmentedSteam#1776]
### Expected Behavior
Load completely and run.

### Actual Behavior
Stuck at: Augmented Steam loading data... and won't work.

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Last version

**Comment by Ptilopsis01** [comment]
I've met this too

**Comment by BigPlaya** [comment]
same with mine. hasn't worked in a while. it's stuck at loading. i think it's been more than 1 month.

**Comment by candela97** [comment]
See #1748 for a workaround for the time being, or download AS from the Chrome store instead. The update on the Edge store is still pending review for some reason...
