### ISSUE TITLE
сделай категорий плиз

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [IsThereAnyDeal/AugmentedSteam#1777]
когда заходишь разрабу, чтобы автоматом были только игры , остальное не нужно, постоянно надо нажимать онли игры 
![sshot-005](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/73518754/2a2b1df2-8e7c-45db-aaaf-d1567a4b647b)

![sshot-006](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/73518754/cb62ab1c-4f4d-48f5-83e2-7570e0e2ab54)

**Comment by candela97** [comment]
Sounds like a duplicate of #1120.
