### ISSUE TITLE
[BUG] Steam Sale does not load properly

### ISSUE THREAD

**Issue by probablypedro** [IsThereAnyDeal/AugmentedSteam#1778]
### Expected Behavior
Steam Sale boxes will show up properly both in their regular state and when the user hovers over them.

### Actual Behavior
Some portions of Steam Sale-specific pages crash, giving the user the option to refresh that specific line.

### Steps to Reproduce the Problem

  1. Go to any Sale-specific page (for my example, https://store.steampowered.com/sale/gdocexpo , but it has happened in others)
  2. Scroll through the page
  3. Randomly, one or many lines of games will crash according to the image, and the users will have the option to refresh. 
  
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/144948828/c545f062-db9b-424f-991a-0cd81754c0d9)

  5. Transcript of the error message (acquired in another sale page, https://store.steampowered.com/sale/publishersale2023:)
Error Reference: Store_8361311_317ca6f72f86d8e6

Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

 

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: Firefox 117.0.1 (64 Bits)

**Comment by candela97** [comment]
I couldn't reproduce this during any of the recent sales/events, and a React error sounds like a Steam issue. Please open a new issue if you can reproduce this in a brand new browser profile with **only** AS enabled.
