### ISSUE TITLE
[BUG] Show "System Requirements" as setting item

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1781]
### Expected Behavior
I would like to see the “System Requirements” item in the “Hide” block of the add-on settings.

### Actual Behavior
When you enable the add-on, the "System Requirements" block for games on Steam disappears. When you disable the add-on, it starts to appear again. The add-on settings do not contain the words "system" and "requirements". Therefore, I can assume that either this item is called differently from the name of the corresponding block in Steam, or it is hidden by some other rule that is not related to System Requirements.

### Specifications
  - Augmented Steam Version: 2.6.0 (September 16, 2023)
  - Browser Version: Mozilla Firefox 119.0b3 (64-bit)
  - Microsoft Windows 10.0.19045.3516

**Comment by candela97** [comment]
You must have unchecked "System Requirements" from here
![螢幕擷取畫面 2023-10-04 195947](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/54083835/9f75ab66-d61c-4846-b94e-de7dfdd3b030)
