### ISSUE TITLE
[BUG] Wrong deal prices for JoyBuggy (correct on IsThereAnyDeal.com)

### ISSUE THREAD

**Issue by MMaster** [IsThereAnyDeal/AugmentedSteam#1787]
### Expected Behavior
Show actual lowest price without coupon applied if the seller offers lower price without coupon.

### Actual Behavior
Currently multiple games show JoyBuggy as having lowest price because they apply coupon on top of lowered price JoyBuggy offers without coupon, but when coupon is applied in JoyBuggy the deal price is disregarded and the coupon is applied to original full price many times being higher than the lowered price without coupon. 

eg:
 https://store.steampowered.com/app/1597310/Airship_Kingdoms_Adrift/ 
shows current best price as:
[Current best:](https://isthereanydeal.com/game/airshipkingdomsadrift/info/)
17.71€
[-41% with voucher FP15OFF at JoyBuggy (steam)](https://www.joybuggy.com/en/airship-kingdoms-adrift?ref=224)

In reality the price without coupon is 20.84€ while price with coupon is 25.49€ because it is applied to full price 29.99€.

### Steps to Reproduce the Problem

  1. Open https://store.steampowered.com/app/1597310/Airship_Kingdoms_Adrift/
  2. See the lowest price as 17.71€ (with 15% coupon applied to already lowered price of 20.84€)
  3. Go to: https://www.joybuggy.com/en/airship-kingdoms-adrift?ref=224
  4. Put it to cart and apply suggested coupon FP15OFF
  5. See the price is 25.49€

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: Firefox 118.0.2

**Comment by candela97** [comment]
Unfortunately this is how ITAD works at the moment -- coupons are assumed to be always applicable with no strings attached. The new site will improve how coupons are handled, but for now, you'll have to keep an eye on coupon rules for each store, and you can also disable coupon discounts in options if it bothers you.

See https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1489 regarding improvements to how the extension handles coupons.
