### ISSUE TITLE
[BUG] Links on Steamcommunity get replaced with broken links

### ISSUE THREAD

**Issue by Kissaki** [IsThereAnyDeal/AugmentedSteam#1790]
### Expected Behavior

When I open an external link on Steamcommunity discussions I either get the Steam leaving steam warning page or navigate to the target directly.

### Actual Behavior

A default page or first page of the discussion is shown.

### Steps to Reproduce the Problem

1. Log in to steamcommunify.com
2. Open a steam discussion with an external link
3. Compare original/intended link target vs actual link target

During loading you can on-hover verify the link target is the correct URL before AugmentedSteam replaces it.\
After loading finished, on-hover shows the link target has been replaced, seemingly to (part of) current page URL with `/null` suffix.

With Augmented Steam disabled the link remains the correct link.

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: Firefox 119

~Potentially Relevant:~

* ~Changelog https://github.com/IsThereAnyDeal/AugmentedSteam/blob/c5f4cd5396bdb92230a9ecda5902f7716fc1e7a2/changelog.yml#L10 Fix not skipping community content warnings~
* ~Looking into recent commits, I assume it refers to https://github.com/IsThereAnyDeal/AugmentedSteam/pull/1715~

**Comment by Kissaki** [comment]
Apparently only occurs while logged in, not when logged out.

**Comment by Kissaki** [comment]
Example:

* https://steamcommunity.com/groups/OnwardMarch/discussions/1/3960413951792928987/
* Original link `https://www.humblebundle.com/games/weplay-expo-discover-china-indies`
* steamcommunity link href `https://steamcommunity.com/linkfilter/?u=https%3A%2F%2Fwww.humblebundle.com%2Fgames%2Fweplay-expo-discover-china-indies`
* augmented steam replaced broken link href `https://steamcommunity.com/groups/OnwardMarch/discussions/1/3960413951792928987/null`

**Comment by candela97** [comment]
Steam randomly changed the query string used to handle link filters 🙄. This isn't related to the issue you linked (that's for age gates).

You'll have to disable the `Disable confirmation when accessing external sites` option for now.

**Comment by nc7s** [comment]
Despite Steam changing them on their own, the extension can have a defensive check that if result is `null` stops replacing the links.

**Comment by tfedor** [comment]
Fixed in next release
