### ISSUE TITLE
[BUG] Linking to wrong game

### ISSUE THREAD

**Issue by SirNorek** [IsThereAnyDeal/AugmentedSteam#1795]
### Expected Behavior
Link to a bundle called Journey, containing Eternal Edge +

### Actual Behavior
Links to a game called Journey, unrelated

### Steps to Reproduce the Problem

  1. https://store.steampowered.com/app/896440/Eternal_Edge/
  2. Click on the bundle
  3. History/current links to https://isthereanydeal.com/game/journey/info/
  4. Clicking the actual store links to https://pencilifed-studios.itch.io/the-journey

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: Chrome Version 119.0.6045.124

**Comment by candela97** [comment]
This is an ITAD issue, therefore invalid for this issue tracker, but I want to keep note of this particular instance where the bundle name conflicts with actual app names.

**Comment by candela97** [comment]
Looks like the new ITAD still trips up on cases like this, ah well. I've filed a new issue with ITAD.
