### ISSUE TITLE
[BUG]Game names are not highlighted on the home page and in activities

### ISSUE THREAD

**Issue by MakiseSora** [IsThereAnyDeal/AugmentedSteam#1796]
### Expected Behavior
The game name (or item) is highlighted in the color as set in the highlighting

### Actual Behavior
Game names are not highlighted.

### Steps to Reproduce the Problem

  1. Open the top page or an activity

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: Brave Version: 1.60.114, Chromium: 119.0.6045.124（Official Build） （64 bit）

**Comment by MakiseSora** [comment]
This problem did not occur 10 hours ago.

**Comment by MakiseSora** [comment]
When I looked at the activity again, it was highlighted (restarting the browser was normal).

I have already cleared the cache many times, so this is a mystery.

**Comment by candela97** [comment]
Probably a Steam hiccup. Leave a comment if it happens again and doesn't fix itself!
