### ISSUE TITLE
[BUG] Augmented Steam - achievements sorting is failing to work

### ISSUE THREAD

**Issue by rgrekoff** [IsThereAnyDeal/AugmentedSteam#1798]
### Expected Behavior
"Sort by: Date unlocked" on achievements page of any game sorts achievements by date

### Actual Behavior
doesn't work for me.

### Steps to Reproduce the Problem
try to use this option

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: last ver of chrome, edge and yandex

**Comment by hectorevil** [comment]
get this bug too

**Comment by candela97** [comment]
Yeah, unfortunately Steam broke it. I don't know of any API that returns achievement unlock timestamps, so we might have to resort to parsing HTML 😥

**Comment by candela97** [comment]
`https://api.steampowered.com/IPlayerService/GetGameAchievements/v1/?access_token=${accessToken}&appid=${appid}&language=${language}`

**Comment by hectorevil** [comment]
its fixed?

**Comment by candela97** [comment]
Not yet. I've linked possible APIs that we can use, but `ISteamUserStats/GetPlayerAchievements` requires you to register a web api key, and I'm not sure if we want to add such a dependency.

**Comment by Kazserah** [comment]
Same

**Comment by rgrekoff** [comment]
So. Augmented Steam was updated this morning to the 3.0 version, but unfortunately the problem has not gone away. Sorting achievements by time still does not work(

**Comment by tfedor** [comment]
Should be (partially) fixed in next release - right now I've added only for sorting English and Czech locales
