### ISSUE TITLE
[BUG] Augmented Steam for browsers lead to a wrong game page from the UI element hyperlinks on the game's steam page when the game has non-existent page on ITAD

### ISSUE THREAD

**Issue by nmatanski** [IsThereAnyDeal/AugmentedSteam#1799]
### Expected Behavior
The extension should lead to the actual game page on ITAD or should fall back to another state when ITAD has no game page yet.

### Actual Behavior
The extension leads to a wrong game page on ITAD

### Steps to Reproduce the Problem

  1. Open the steam page for Pile up: https://store.steampowered.com/app/2094910/Pile_Up/
  2. Click on Historical low or Current best from Augmented Steam's UI element above the Steam's price and buy button:
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/32290850/8179057b-bbe9-4d64-97ad-18faa19317f2)

  3. It leads to the wrong ITAD page for a wrong game with similar name: https://isthereanydeal.com/game/pileup/info/

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: Chrome 119.0.6045.160

P.S.: I even bought the wrong game because of this bug, it's actually hilarious, but can hurt others a lot (especially for more expensive games) since the used codes are non-refundable.

**Comment by candela97** [comment]
That's an app name conflict, and the fact that some 3rd-party stores use the name "pile up" in the URL path is not helping. This is unfortunately an issue with ITAD though, and is being tracked at https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/3353. Please file these kind of issues in that repository in the future, thanks!

**Comment by nmatanski** [comment]
@candela97 The Pile Up I mentioned is yet another 3rd game and not the 2 existing ones on ITAD. So it should be ignored by Augmented Steam when the game does not exist on ITAD or be handled in another way

**Comment by candela97** [comment]
I just followed the steps you mentioned in Steps to Reproduce the Problem 😅

If it's about anthoer game can you please link it here?

**Comment by nmatanski** [comment]
The one I linked from Steam does not exist on ITAD. It's neither of these 3: 
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/32290850/9b096984-551e-4e25-a688-cdd9c9a607c9)

**Comment by candela97** [comment]
Oh, it _is_ on ITAD, it's just tracking the wrong game since it got mixed up. Check my comment in the linked issue above.

A new ITAD site is in the works and will hopefully avoid headaches like this!
