### ISSUE TITLE
[FEATURE REQUEST] T

### ISSUE THREAD

**Issue by PandaGround0** [IsThereAnyDeal/AugmentedSteam#1802]
as u know Steam cancelled the Turkish Lira from the market and we are paying with dolar in steam market. Can you add a feature to the application that shows the Turkish lira price? (For SteamAUGMENTED)

**Comment by gkucar** [comment]
Most needed feature is this. You can check hourly or daily dollar/turkish lira exchange rate, and show estimated lira price near to real dollar price.

**Comment by candela97** [comment]
I was informed that ITAD prices are converted, but yeah, we can probably do the same for Steam prices.

**Comment by candela97** [comment]
Duplicate of #1817 (since that one has a better title)
