### ISSUE TITLE
[FEATURE REQUEST] Notes manager

### ISSUE THREAD

**Issue by pakoito** [IsThereAnyDeal/AugmentedSteam#1805]
### Current Behavior (if any)
My notes are at near capacity and I know I have some I'd like to delete from games I've already purchased.

### Desired Behavior
I'd like to review all my notes in a single place and clear only some of them of my choice.

### Motivation / Use Case for Changing the Behavior
Clear storage so I can continue adding more synchronized notes.

**Comment by candela97** [comment]
Duplicate of #429. It's being worked on for sure!
