### ISSUE TITLE
[FEATURE REQUEST] Customizable user-defined tags.

### ISSUE THREAD

**Issue by seumas** [IsThereAnyDeal/AugmentedSteam#1811]
###Request for Enhancement:###
Allow users to add and customize their own defined tags.

### Motivation / Use Case for Changing the Behavior
I'd like to have RPGMAKER games tagged. Some might like to have games tagged based on whether they're ADULT or NSFW. Some may want to have a special tag for VR. This additional and customizable information makes going through search results, the home page, and special event or publisher/developer pages much faster as you don't have to visit each individual store page and then skim through the details that you care about.

What would truly be desirable is to pivot how tags are used overall. 

For example, let a user define custom tags (or other triggers, such as game length, category tags, etc) and then choose what a match on that tag should cause to happen. The choices for what should happen should be: tag (normally, as is done now), filter-out, highlight on store page (and then on the store page, the tags that matched should be highlighted and called-out distinctly), or displayed as a banner (under the trailer somewhere in the main section).

This would give the added benefit of having a tag be a "warning", too (like the existing "not your language" or "vr only" or "adult only" warning callouts.

**Comment by candela97** [comment]
I believe you can already add your own tags via a popup dialog by clicking on the plus sign in the tags list on store pages.

We won't be able to influence what tags Steam decides to add to their "official" supported list though.
