### ISSUE TITLE
[FEATURE REQUEST] Button to the game's mod page.

### ISSUE THREAD

**Issue by DogancanYr** [IsThereAnyDeal/AugmentedSteam#1821]
Button that will take you to this page https://store.steampowered.com/app/620/Portal_2/ to this page https://store.steampowered.com/mods/620/

**Comment by candela97** [comment]
There's a link under system requirements. You need to scroll for a bit, but that should suffice?

**Comment by DogancanYr** [comment]
> There's a link under system requirements. You need to scroll for a bit, but that should suffice?

It might be nicer if the button is added next to the name.

**Comment by candela97** [comment]
There aren't a lot of mods hosted on Steam, so I don't think a dedicated button is worth it. You can add it as a custom 3rd-party link if you want, see https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1263#issuecomment-948123330 as an example.
