### ISSUE TITLE
[FEATURE REQUEST] Add MobyGames to 3rd-party links on game pages

### ISSUE THREAD

**Issue by kazerniel** [IsThereAnyDeal/AugmentedSteam#1825]

**Comment by candela97** [comment]
Can you add more info on why we should add this site? Also see https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1263#issuecomment-948123330 as an example for adding your own custom links.

**Comment by kazerniel** [comment]
Thanks, I somehow forgot about that custom link feature despite having used it before 🤦‍♂️ 

(As for the why - it saves me some clicking when cross-checking Steam and MobyGame release details of games.)
