### ISSUE TITLE
[BUG] No price comparison on store pages

### ISSUE THREAD

**Issue by stunlocked94** [IsThereAnyDeal/AugmentedSteam#1829]
For a few days now i noticed that i no longer see price comparisons on mouse hover or howlongtobeat-stats on game pages. Tested in Edge, Chrome and Firefox. I attached a console log.

### Expected Behavior
Example store page: https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/

Upon hovering over the "Buy Red Dead Redemption 2" part of the page a comparison showing the cheapest current price in other stores should show up.

### Actual Behavior
![Screenshot 2024-02-10 163047](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/73516723/a21d3890-f097-4f50-bf5a-be6edb01c7b8)

Nothing shows up and there is a red exclamation mark at the top of the page noting console errors.
![grafik](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/73516723/35dd3ec9-41e8-4e7d-bd24-0d4b1bed0133)

I already disabled all other addons, used a fresh profile in Firefox and also uninstalled and reinstalled Augmented Steam.
[console-export-2024-2-10_16-27-19.txt](https://github.com/IsThereAnyDeal/AugmentedSteam/files/14229685/console-export-2024-2-10_16-27-19.txt)

### Steps to Reproduce the Problem

  1. Open store page
  2. hover over "Buy" section
  3. Notice the red exclamation mark

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: Firefox 122.0.1 (64-Bit)

**Comment by candela97** [comment]
ITAD is currently down, see the front page https://isthereanydeal.com/ or hop into our Discord for more info.

Features like price history, integrated info from 3rd-party sites etc. will also stop working on 2.x versions of AS. Please update to 3.0 when it's available in a few days.

**Comment by stunlocked94** [comment]
Welp, sorry about that. Close this please.
