### ISSUE TITLE
[BUG] Displaying the regional price in the wishlist

### ISSUE THREAD

**Issue by AsFaltKost** [IsThereAnyDeal/AugmentedSteam#1833]
### Expected Behavior
Displaying a tooltip with regional prices when hovering the mouse over the price tag

### Actual Behavior
nothing happens when you hover your mouse over the price tag.

An error is displayed in the browser console and repeated many times when hovering over the price tag:
`browser-polyfill.js:1 Uncaught (in promise) Error: TypeError: Failed to fetch
    at x (browser-polyfill.js:1:8876)`

### Steps to Reproduce the Problem

  1. Go to wishlist
  2. Hover your mouse over the price tag

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Google Chrome 121.0.6167.161

**Comment by TsukiZero** [comment]
WebConsole info 
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/78157224/d05680c1-75cd-4f4c-88aa-43cc16fa2f6a)

**Comment by candela97** [comment]
Regional pricing is not supported on wishlists, I think you mean ITAD price history? This should be fixed now the new ITAD has stablized, though there're some ongoing throttling issues that _should_ resolve by itself if you reload the page a few times. Let us know if it doesn't!

**Comment by TsukiZero** [comment]
Oh, I thought it was about the bug of dropdown not displaying AT ALL, because back when I posted that it was not displaying the price dropdown in product pages.
