### ISSUE TITLE
[BUG] coupons still show up in price comparison when "Include coupon codes in price comparison" is unticked

### ISSUE THREAD

**Issue by firebird5555** [IsThereAnyDeal/AugmentedSteam#1836]
### Expected Behavior
when i untick "Include coupon codes in price comparison" it should make coupons not show up in price comparison on a store page

### Actual Behavior
the coupon shows on the store page price comparison 

### Steps to Reproduce the Problem

  1. go to a store page that has greenmangaming as the lowest price with the couspon ( i noticed dave the diver and forspoken have the issue
  2. untick "Include coupon codes in price comparison"
  3. notice the coupons are still showing up

### Specifications

  - Augmented Steam Version: 1.3.0
  - Browser Version: firefox 122.0.1

i've noticed it happens on chrome a s well same version 1.3.0
chrome version: 121.0.6167.185

**Comment by candela97** [comment]
The new API returns price cuts with vouchers included by default, so this option won't work at the moment. This might change in the future, so I'm labling this as a feature request.

**Comment by tfedor** [comment]
Fixed. It was a server issue, so it should start behaving properly with the current live version of AS.
