### ISSUE TITLE
[BUG] Augemented Steam duplicates the “Bundles/Packages that include this game” header on store pages

### ISSUE THREAD

**Issue by przemo20** [IsThereAnyDeal/AugmentedSteam#1837]
### Expected Behavior
The “Bundles that include this game” should only appear once.

### Actual Behavior
There are two “Bundles that include this game” headers – one says “Packages that include this game” and the second one “Bundles that include this game” (added by AugmentedSteam) lists nothing (the section is empty).

Screenshot:
![obraz](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/22180480/f683df72-baf3-4ce0-8b33-51585172e26f)

### Steps to Reproduce the Problem

  1. Visit https://store.steampowered.com/app/6220/FlatOut/
  2. Scroll down the page to the list of available packages

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Firefox 122.0.1 (64-bit)

**Comment by candela97** [comment]
"Bundles that include this game" is meant to show ongoing bundles. This is a likely a network error that should be fixed now the new ITAD has stablized. Let us know if it's still an issue!

**Comment by przemo20** [comment]
Yeah, it is still happening.

(no “Packages that include this game”, but still the “Bundles that include this game” section is empty)
![Screenshot 2024-03-06 200510](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/22180480/9511b655-8869-40c1-bd13-c640bc307a76)

![Screenshot 2024-03-06 200934](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/22180480/3553f299-a81b-4a80-8c34-d517d0c53616)

![store steampowered com_app_582010_Monster_Hunter_World_](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/22180480/e77b02a2-2163-43df-bacb-d59660ff27dd)

**Comment by candela97** [comment]
Yeah, scatch out my last comment. The API is returning expired bundle info for some reason.

**Comment by candela97** [comment]
The API returns all bundles now, so we need to add a check for live bundles.
