### ISSUE TITLE
[BUG] ASTLIBRA Revision doesn't do the dropdown price thing in the steam wishlist page

### ISSUE THREAD

**Issue by Prometheus0000** [IsThereAnyDeal/AugmentedSteam#1840]
### Expected Behavior
Show current best and historical low

### Actual Behavior
Does nothing. It does show the data on the store page, so I dunno why it wouldn't work. It didn't work before the update either. I recall some other games with the same problem, but none of the other games in my wishlist right now do this.

### Steps to Reproduce the Problem

  1. Have game in wishlist
  2. Hover over it

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Firefox 122.0.1 (64-bit)

**Comment by candela97** [comment]
Duplicate of #1833
