### ISSUE TITLE
[BUG] Error while applying feature Me

### ISSUE THREAD

**Issue by muhasturk** [IsThereAnyDeal/AugmentedSteam#1841]
### Expected Behavior
There should be no error message on console.

### Actual Behavior
Console prints following error on frontpage.js
```
frontpage.js:1  Error while applying feature Me
```

### Steps to Reproduce the Problem

  1.  Navigate steam storefront [https://store.steampowered.com/](url)
  2. Open console

### Specifications

  - Augmented Steam Version: 2.6.0
  - Browser Version: Microsoft Edge Version 121.0.2277.112 (Official build) (64-bit)

**Comment by candela97** [comment]
This might have been a network error that should be fixed already since the new ITAD has stablized. Let us know if it's still an issue!
