### ISSUE TITLE
[BUG] Doesn't show previous bundle count on store pages anymore

### ISSUE THREAD

**Issue by Californ1a** [IsThereAnyDeal/AugmentedSteam#1844]
I see it's been commented out in the new version:

https://github.com/IsThereAnyDeal/AugmentedSteam/blob/develop/src/js/Content/Modules/Prices/PriceOverview.svelte#L78-L83

I used it to easily see if a game had been in a bundle before without going to the ITAD page. Just seeing the "In bundle" line on a store page, for me, signaled that the game is prone to be included in bundles so I should hold off buying it directly/individually and wait for it to be in another bundle, whereas if there is no "In bundle" line then I'm more likely to have to buy it individually.

As for the exact count of bundles itself, it's not incredibly important, though it is nice to be able to quickly see if the game frequently goes into bundles or has only been in a few (determine how long you may need to wait for it to be in a future bundle, which can help when deciding between waiting for a bundle or buying it directly).

**Comment by jiut** [comment]
Same. Buying keys from a bundle is usually cheaper.

**Comment by mitzaM** [comment]
+1 this was my most used feature

**Comment by Slippy2k** [comment]
I also miss the function

**Comment by MostlyOffline** [comment]
This was basically THE reason to use this extension and you keep deprecating old versions so that we can't use this feature anymore. Well, one less extension to worry about I suppose, until -maybe- you re-enable it. It's been a fun ride..

**Comment by candela97** [comment]
Sorry for the late reply. The new API doesn't provide this info at the moment as part of the transition, but it'll likely be added back in the future, so I'll be labling this as a feature request.

Please leave a thumbs up if you'd like to see this happen!

**Comment by tfedor** [comment]
Fixed in next release
