### ISSUE TITLE
[BUG] Highlighting/tagging games from ITAD collection not working since the website redesign

### ISSUE THREAD

**Issue by Pietruszek** [IsThereAnyDeal/AugmentedSteam#1847]
### Old Behavior

Before the ITAD website redesign I used Augmented Steam to sync my ITAD collection and Highlight/Tag those games on the Steam storefront.

### Current Behavior

After the website redesign Highlighting/Tagging games from ITAD collection stopped working suggesting some kind of sync issue. I have (in order):
- updated Augmented Steam to 3.0.0
- reconnected my ITAD account
- used "Clear cached data" function
- run another sync with ITAD which does NOT throw an error

Still the games from my ITAD collection are not getting Highlighted/Tagged like they used to.

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Firefox 123.0

**Comment by refatK** [comment]
Just want to add some info here but tested both on Firefox and Chrome and got the same results. For Chrome it was even a fresh install.

The most interesting part is that there are a couple of games that do seem to work for some reason. I'll an image here comparing 2 games, Sable (not working), and Dying light (working). Chop Goblins is another example of a game that seems to work.

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/31963426/936876c0-1dd4-4863-a99f-c9b63a1497f8)

It's specific games that seem to work for some reason and doesn't seem that changing things in the ITAD collection helps (adding a game copy, marking redeemed)

The other thing to add is now the copies information is missing too, just saying the game is "on another store":
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/31963426/57597c7c-596e-4ce7-a9cd-6dc11850c403)

**Comment by refatK** [comment]
Just wanted to add another example, this being a set of games I added all at once in the old ITAD version (using the add selected games from bundle feature)

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/31963426/c5b89b68-3a1d-49de-84a8-ddd0f25f4cea)

**Comment by tfedor** [comment]
Should be fixed in next release
