### ISSUE TITLE
[BUG] repeated "Error: port is undefined" on Steam page

### ISSUE THREAD

**Issue by shaver** [IsThereAnyDeal/AugmentedSteam#1848]
### Expected Behavior

Not sure what is functionally broken from this, but the red (!) told me to look for errors.

### Steps to Reproduce the Problem

  1. https://store.steampowered.com/app/979110/Space_Haven/
  2. Open browser console
  3. 

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Firefox 123.0 (64-bit) on Windows 11

**Comment by candela97** [comment]
See https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1841#issuecomment-1981546671 and let us know if it doesn't resolve by itself even after reloading the page.
