### ISSUE TITLE
cant remove the custom theme that i set long time ago

### ISSUE THREAD

**Issue by Lordiod** [IsThereAnyDeal/AugmentedSteam#1849]
### Expected Behavior
in the edit profile background section should be a place to set your custom theme

### Actual Behavior
custom theme section doesnt appear

### Steps to Reproduce the Problem

  1. profile
  2. edit profile
  3. profile background

### Specifications

  - Augmented Steam Version: 
  - Browser Version:

**Comment by FlaminSarge** [comment]
It seems that with another update to the "Edit Profile" UI, this issue has recurred and the Custom Themes section no longer appears.
