### ISSUE TITLE
[BUG]The ABOUT THIS GAME and SYSTEM REQUIREMENTS items are not displayed

### ISSUE THREAD

**Issue by MakiseSora** [IsThereAnyDeal/AugmentedSteam#1852]
### Expected Behavior
The ABOUT THIS GAME and SYSTEM REQUIREMENTS on the store page are not displayed.

The SYSTEM REQUIREMENTS item has not been displayed for quite some time, but in the last few days, the ABOUT THIS GAME item is also not displayed.

NOTE: It is possible that I am missing some settings.

### Actual Behavior
The ABOUT THIS GAME and SYSTEM REQUIREMENTS sections will appear.

### Steps to Reproduce the Problem

  1.Open the store page.

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Brave(Windows)1.63.169 Chromium: 122.0.6261.111(Official Build) (64 bit)

**Comment by MakiseSora** [comment]
Sorley, I was wrong...

Before I knew it, the ABOUT THIS GAME and SYSTEM REQUIREMENTS checkbox was unchecked in the customization of the store page.
By turning these ON, they are now displayed again!

**Comment by candela97** [comment]
Seems like you found the culprit!
