### ISSUE TITLE
[BUG]Sort by time not work in player profile achievement page

### ISSUE THREAD

**Issue by ZhuSunDev** [IsThereAnyDeal/AugmentedSteam#1864]
### Expected Behavior

in achievement page,select sort option ore click ↑ or ↓ can sort achievement by time

### Actual Behavior

not work after click or select option.

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Chrome latest version

**Comment by candela97** [comment]
Duplicate of #1798
