### ISSUE TITLE
Can't add items to Cart in Steam since new Pop Up window [BUG]

### ISSUE THREAD

**Issue by IshanDeston** [IsThereAnyDeal/AugmentedSteam#1868]
### Expected Behavior
Pop up window shows up to allow me to select if i want to add an item to cart as Private game or not.

### Actual Behavior
Page refreshes, no pop up, nothing added to the cart.

### Steps to Reproduce the Problem

  1. Enable Augumented Steam
  2. Add item to Cart from Webpage
  3. Wonder why the Page refreshed and nothing is added to the cart

### Specifications

  - Augmented Steam Version:  3.0.0 (Update from 15 February 2024)
  - Browser Version: Firefox 123.0.1 (64-bit)

**Comment by rgooler** [comment]
Can confirm this is also happening on 

Browser: Version 123.0.6312.58 (Official Build) (64-bit)

**Comment by candela97** [comment]
See https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1851#issuecomment-1981451650
