### ISSUE TITLE
[BUG] Missing shopping cart

### ISSUE THREAD

**Issue by mcaphasia** [IsThereAnyDeal/AugmentedSteam#1870]
### Expected Behavior
Click add game to cart, buy game

### Actual Behavior
Nothing happens, cart is completely missing. Clicking add to cart does nothing. Works as expected with AugmentedSteam disabled

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: linux Firefox 124

**Comment by candela97** [comment]
See https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1851#issuecomment-1981451650 while the new version awaits AMO review.
