### ISSUE TITLE
[BUG] Is this the intended location for the price info on v3.1.0?

### ISSUE THREAD

**Issue by subZEROx265** [IsThereAnyDeal/AugmentedSteam#1871]
### Expected Behavior
Price on hover usually located under game title box

### Actual Behavior
Price on hover located on the game title

### Steps to Reproduce the Problem

  1. Open wishlist
  2. Hover on game title
  3. 

### Specifications

  - Augmented Steam Version: 3.1.0
  - Browser Version: Edge v. 122.0.2365.92 
![gr4yw4rd3n's wishlist and 7 more pages - Personal - Microsoft​ Edge_2024-03-23_11-27-35](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/145109298/244f51e7-e0e1-4000-a80e-3ea3135dcd3a)

**Comment by neyel8r** [comment]
same issue for me in Chrome Version 121.0.6167.85 (Official Build) (64-bit)

**Comment by Prometheus0000** [comment]
This happens on the just released version on firefox 124.0.1, so it's not fixed. This didn't happen to me before the update though.

**Comment by candela97** [comment]
Not yet I'm afraid 😅
