### ISSUE TITLE
[FEATURE REQUEST] Acknowledge games that are present in a family library

### ISSUE THREAD

**Issue by AriannaStory** [IsThereAnyDeal/AugmentedSteam#1907]
### Current Behavior (if any)
Augmented Steam shows me games that I own, and doesn't take family-shared games into account.

### Desired Behavior
Just as games that I own are highlighted blue, I'd like games that someone in my family owns to be highlighted with another color. 

### Motivation / Use Case for Changing the Behavior
I'd rather not buy a game that I already have access to through my Family Library!

Steam has an undocumented endpoint at https://api.steampowered.com/IFamilyGroupsService/GetSharedLibraryApps/v1/ ([XPaw Docs](https://steamapi.xpaw.me/#IFamilyGroupsService)) that can give you that list. Presumably parsing through it and just checking for games where I'm not included in the $data['response']['apps'][i]['owner_steamids'] array would be sufficient.

```json
{
   "response": {
      "apps": [
         {
            "appid": 10,
            "owner_steamids": [
               "76561197996825041"
            ],
            "name": "Counter-Strike",
            "img_icon_hash": "6b0312cda02f5f777efa2f3318c307ff9acafbb5",
            "exclude_reason": 0,
            "rt_time_acquired": 1498357027,
            "rt_last_played": 0,
            "rt_playtime": 0,
            "app_type": 1
         },
```

That endpoint takes care of things like excluding games that I own myself, games that are excluded from Family Sharing, and etc.

**Comment by candela97** [comment]
Doable, but we should wait until this feature is out of beta.

We'll also need `https://api.steampowered.com/IFamilyGroupsService/GetFamilyGroupForUser/v1/?access_token=` to get the family groupid since it si required.

**Comment by Lifeismana** [comment]
this week's maintenance of steam added ui for this 
although it only shows up if the package that's owned by someone in your family is still sold on the store (eg: if the package is for keys only / is a preorder package)
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/15911822/b0d14803-7e56-44e5-801a-83a2e6043216)

Augmented Steam might need a fix to make it look a bit better (add a separator between as's ui and the family bit)

**Comment by candela97** [comment]
Since the new Steam Families officially released, I guess that resolves this then!
