### ISSUE TITLE
[FEATURE REQUEST] Lowest price in history in WISHLIST tab

### ISSUE THREAD

**Issue by sirrreen** [IsThereAnyDeal/AugmentedSteam#1915]
### Current Behavior (if any)
I dont see history lowest price in wishlist tab below actual lowest price.

### Desired Behavior
I want to se lowest price in history just below actual lowest price.
And if I mean lowest then I mean lowest price excluding when game was free.

### Motivation / Use Case for Changing the Behavior
I see how low actual price is but I dont see how much low with comparison with history it is. I can search it in history tab somewhere else but it is very nonsense make it for each wishlisted game. Also I cannot remember it.

I tried to search and turn on this function many times in settings but didnt find it. I would expect that this is something what will be included in default. And it is not there at all?

This is one big annoing problem for me with this service. Everything else is good or not worth to mention.
Thank you in advance and if not thank you anyway ;)

**Comment by candela97** [comment]
Is this still an issue? If so, what games?

**Comment by sirrreen** [comment]
Yes, it is still an issue. For every game when I on in wishlist section of isthereanydeal.com web page. I can see normal price, I can see actual lowest price, but I dont see history lowest price.
And becau se I dont se history lowest price so I dont know  HOW LOW ACTUAL LOWEST PRICE REALY IS.
OK, I can click on game and click on history tab and search lowest history price there but I have 300 games in wishlist ..

**Comment by candela97** [comment]
Sorry, I thought you meant the Steam wishlist. This tracker is for issues related to the browser extension. Please file suggestions for the ITAD site in the #feedback channel of the Discord server (link in menu dropdown).
