### ISSUE TITLE
[BUG] Price History Information settings do not apply to historical low

### ISSUE THREAD

**Issue by BlepBlep** [IsThereAnyDeal/AugmentedSteam#1916]
### Expected Behavior
When viewing historical low on games, it should ignore un-checked stores.

### Actual Behavior
When viewing historical low on games, it shows un-checked stores.

### Steps to Reproduce the Problem

  1. Open store page
  2. Check historical low price

### Specifications

  - Augmented Steam Version: 3.1.1
  - Browser Version: Firefox 125.0.3

**Comment by candela97** [comment]
Duplicate of #1906
