### ISSUE TITLE
[BUG] Current best/Historical low can get the wrong data for bundles with the same name

### ISSUE THREAD

**Issue by RamonJardim** [IsThereAnyDeal/AugmentedSteam#1918]
### Expected Behavior
Current best/historical low should show the prices for the current bundle I'm looking at.

### Actual Behavior
It's showing the prices for a different bundle with the same name

### Steps to Reproduce the Problem

  1. Go to [this game page](https://store.steampowered.com/app/1284190/The_Planet_Crafter/) and search for the "Survival Bundle".
  2. Prices shown for Current/Best historical low are not compatible with the actual price of the bundle
  3. Click on "at steam" button to be redirected to the current best price
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/29959431/b1cde55e-6a48-4110-a9a2-29909c8a1be1)
you'll see the bundle is not the same.
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/29959431/6b07fdbc-f231-42f9-aea1-26497a226bce)

### Specifications

  - Augmented Steam Version: 3.1.1
  - Browser Version: Chrome 123.0.6312.105

**Comment by candela97** [comment]
This is an ITAD issue and I've raised it in the #feedback channel.
