### ISSUE TITLE
[FEATURE REQUEST] Append nicknames to friends' names (same as Steam client option)

### ISSUE THREAD

**Issue by bottleblue** [IsThereAnyDeal/AugmentedSteam#1919]
### Current Behavior (if any)
Nicknames take the place of actual names which can be confusing 

### Desired Behavior
To have the same option "Append nickname to friends' names" from the Steam client

### Motivation / Use Case for Changing the Behavior
The friends list in Steam's website doesn't have the option of appending nicknames to friends' names like the Steam client so it lists all your friends by the nickname which can be confusing and unhelpful if you don't use a unique nickname for everyone. I use descriptions of games we play together or games we traded, as nicknames. For example I may give them the nickname of "L4D2" if we play that game together so I know which friend plays that and can possibly invite next time.

I like using nicknames but don't want to view the friends list that way. That's probably why Steam gave us this option in the client. I don't know why they didn't do the same thing for the website. Can this be implemented in Augmented Steam?  

![friendslist](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/3678136/5c0acf07-5afc-4746-8c3d-c6a38d9d8449)

**Comment by candela97** [comment]
This is doable, but in practice the only way to get the user's original name AFAICT is to fetch the miniprofile hover, which may amount to a lot of requests.

`https://steamapi.xpaw.me/#IPlayerService/GetNicknameList` only returns `accountid`s too, unfortunately.

**Comment by bottleblue** [comment]
So not likely?

**Comment by candela97** [comment]
Experimental for now. but feel free to side-load a build for your browser and give it a try: https://github.com/IsThereAnyDeal/AugmentedSteam/actions/runs/10085966694

**Comment by bottleblue** [comment]
I don't know how to sideload lol

**Comment by candela97** [comment]
On Firefox, open `about://debugging`, should be fairly straightforward.
On Chrome you'll need to enable developer mode from the extension management page, then load unpacked. It's best if you test on a separate browser profile, or backup your settings first.

**Comment by bottleblue** [comment]
It was actually about:debugging.  Where do I get the extension file from?

**Comment by bottleblue** [comment]
Hey it worked nice!  Thanks for adding it.  I didn't see an option in the settings to enable/disable it though.

**Comment by candela97** [comment]
> It'd be cool if we moused over the nickname part it shows the entire nickname. A lot of it gets cutoff even in the miniprofile.

I tried that but it didn't work. I guess it's being intercepted by the miniprofile hover. Best keep nicknames short I suppose, since there's not enough space to put it on a newline either.

**Comment by bottleblue** [comment]
Got it. Firefox only lets me install this temporarily. Everytime I restart browser I have to install it again. I can't figure out an easy way to make it permanent so I'll just wait till the official release with this feature. 

Thanks again for adding it.

**Comment by bottleblue** [comment]
Something I noticed, if you go to a friend's friendslist and look at the Friends in Common section it still shows their names as nicknames.

![1](https://github.com/user-attachments/assets/215f999f-a045-42ad-b51c-3a0039dfab2a)

**Comment by candela97** [comment]
That's because I made it so it only works on your own profile. But yeah it should work on common friends as well, thanks for testing!

**Comment by bottleblue** [comment]
And Blocked users lol

**Comment by candela97** [comment]
We only load features on friends and groups tabs, other tabs are not supported. It's a little tricky to handle navigating between these tabs, so I think it's best to keep it simple for now.

**Comment by bottleblue** [comment]
I understand, just wanted to let you know. Thx!
