### ISSUE TITLE
[FEATURE REQUEST] Add an option for Custom Backgrounds/Colours back

### ISSUE THREAD

**Issue by MrComNguoi** [IsThereAnyDeal/AugmentedSteam#1936]
I can't seem to find the button to set up new custom backgrounds on my profile anymore, was it removed with the new updated?

**Comment by fantasygone** [comment]
@MrComNguoi 
Do you mean this?

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/104144029/acd61998-3626-472c-a02a-8e4881ad0427)

**Comment by candela97** [comment]
> @MrComNguoi Do you mean this?

No, this feature is on the profile edit page
