### ISSUE TITLE
[BUG] Extension is incorrectly flagging game as "Notice: This game is excluded from Steam's Family Sharing service."

### ISSUE THREAD

**Issue by fantasygone** [IsThereAnyDeal/AugmentedSteam#1937]
### Expected Behavior
The extension before the recent update (I received a pop-up that let me know) would be displaying a warning message under games that do not have Family Sharing enabled. That was working well and should be the expected behaviour.

### Actual Behavior
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/104144029/e7b325b7-2ddc-4240-b209-cb0b51c8588b)
Horizon Zero Dawn, which has the option to be shared in family, is being described the opposite way for some reason.

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/104144029/2107f528-d6a9-499f-8d56-345d0187574d)
I'm able to play it here.

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/104144029/0b52c82e-82bf-4766-be9d-2d523b77e887)

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/104144029/87460809-8a99-435c-b0bc-0259db687c4f)
Same goes for Baldur's Gates and I think every Steam page now.

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/104144029/7230bc7f-eb82-433c-9bbb-8786de9d1774)

### Steps to Reproduce the Problem

  1. Open any Steam page
  2. Read below the button Wishlist
  3. Find the Warning about Family Sharing being inactive, also for games who DO have it active.

### Specifications

  - Augmented Steam Version: 4.0.0
  - Browser Version: Opera One(version: 111.0.5168.25)

**Comment by spiderbala** [comment]
+1
I encountered the same issue. Games that are confirmed to support Family Sharing show a warning message stating they are not supported, while games that do not support the Family Sharing service do not display this message.

**Comment by fantasygone** [comment]
Thank you for the extra info, I just checked and it rings true. Diablo is not available for family sharing but there is no such warning for this title.
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/104144029/f4376172-7627-4730-aa30-7f5593c221d5)

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/104144029/2aeb3e66-05bf-4d55-812b-14a2bc6d0604)

**Comment by candela97** [comment]
Yeah, we got it backwards, thanks for the report!

**Comment by fantasygone** [comment]
got me worried for a sec that so many games had pulled out from the family sharing
