### ISSUE TITLE
[BUG] IndieGala Store Price inaccurate

### ISSUE THREAD

**Issue by gfcwfzkm** [IsThereAnyDeal/AugmentedSteam#1947]
### Expected Behavior
The price from the Indie Gala Store to be accurately detected and used, thus properly suggesting the lowest price on a steam product.

### Actual Behavior
While the plugin and the website show IndieGala Store as the lowest price, opening said store in the browser shows a far higher price than the plugin or website suggest, higher than Steam.

### Steps to Reproduce the Problem

  1. https://store.steampowered.com/app/1345890/Deliver_Us_Mars/
  2. Check the lowest price from the plugin compared to the steam price.
  3. Open the IndieGalaStore link and compare that price with the one suggested by the plugin.

### Specifications

  - Augmented Steam Version: 3.1.1
  - Browser Version: Firefox 127.0.2 64-Bit
  - Configured Currency & Country of Origin: CHF / Switzerland

**Comment by candela97** [comment]
It shows -75% for me and prices look normal, not sure if it's currency specific but I can't check. In any case, this isn't an issue with AS. You can discuss store related issues in the ITAD discord for faster feedback.
