### ISSUE TITLE
[FEATURE REQUEST] Option to disable gallery resize

### ISSUE THREAD

**Issue by tuglaw** [IsThereAnyDeal/AugmentedSteam#1951]
### Current Behavior (if any)
Viewing any game page will cause the gallery to resize, moving page contents.

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/71947356/671cb73a-9fcc-4db2-a1bb-660eeceecadc)

### Desired Behavior
An option to keep the default behavior.

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/71947356/b92ef2b7-1823-430a-aefc-600e34a6a072)

### Motivation / Use Case for Changing the Behavior
Current behavior fills too much of the page, must scroll to view buttons and info.

**Comment by candela97** [comment]
You hit the expand slider that appeared on the top right corner of screenshots or trailers once you hover over them:
![77156319-1f5fac80-6ada-11ea-95d6-7faca639504f](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/54083835/92b6d3ee-ad63-481b-8e9e-6f45b2d6b238)

**Comment by tuglaw** [comment]
Weird, don't remember activating that at all. It was just enabled all of a sudden, so I didn't really know where to look for to disable it.
Thanks for the help.
