### ISSUE TITLE
[BUG] Clear wishlist not working

### ISSUE THREAD

**Issue by RobertLeeMich** [IsThereAnyDeal/AugmentedSteam#1952]
### Expected Behavior
Wishlist gets cleared to nothing.

### Actual Behavior

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/13278272/99686b70-8ade-4c1b-8b4c-9df40d6f34df)

Just "loads" infinitely. I left that alone all day today and it didn't do anything. I tried removing 200 games by hand thinking it might have been a quantity issue but I don't think it is.
### Steps to Reproduce the Problem

  1. Try to clear wishlist
  2. That's it
  3. 

### Specifications

  - Augmented Steam Version: 4.0.1
  - Browser Version:  Version 126.0.6478.127 (Official Build) (64-bit) (CHROME)

**Comment by CTOUT** [comment]
Although I have an issue with seeing my wishlist in the browser, the Empty wishlist option did work for me.

Instead, my issue is I see: -

OOPS, YOU CAN'T VIEW THIS WISHLIST
You don't have permission to view this user's wishlist.

I'm logged in as myself (obviously), I've tried changing my privacy settings to public, and I also now get it in the Steam app after the wishlisted items had been removed.

**Comment by RobertLeeMich** [comment]
> Although I have an issue with seeing my wishlist in the browser, the Empty wishlist option did work for me.
> 
> Instead, my issue is I see: -
> 
> OOPS, YOU CAN'T VIEW THIS WISHLIST You don't have permission to view this user's wishlist.
> 
> I'm logged in as myself (obviously), I've tried changing my privacy settings to public, and I also now get it in the Steam app after the wishlisted items had been removed.

Should probably make a new issue for that.

**Comment by FoxyToxic-002** [comment]
I'm having the exact same issue it just loads infinitely without removing a single item

**Comment by candela97** [comment]
Fixed in 5b9cfcbb567fb393856ed28d6952e8a6bbfa6802
