### ISSUE TITLE
[BUG] ES Regional Container Display Bug

### ISSUE THREAD

**Issue by Trsnaqe** [IsThereAnyDeal/AugmentedSteam#1969]
### Expected Behavior
This is expected behaviour example given from another page
![](https://i.imgur.com/p6Vxbzw.png)
### Actual Behavior
Specifically happens in cod mw2019. Couldn't find another game that causes this.
![](https://i.imgur.com/4zyfJIe.png)
### Steps to Reproduce the Problem

  1. Go to [Cod MW 2019 page](https://store.steampowered.com/app/2000950/Call_of_Duty_Modern_Warfare/)

Maybe overlapping with 
`<div class="game_area_purchase_game_wrapper game_purchase_sub_dropdown"> <div/>
`
causes the bug?
### Specifications

  - Augmented Steam Version: 4.0.1
  - Browser Version: Chrome 126.0.6478.126 (Official Build) (64-bit) & Edge 126.0.2592.102 (Official build) (64-bit)

**Comment by Trsnaqe** [comment]
It is reproducable on games which has regional containers that overlap with purchase options with dropdown. Removing z-index 500 style from them fixes the issue. [HOI IV](https://store.steampowered.com/app/394360/Hearts_of_Iron_IV/)

**Comment by candela97** [comment]
Yeah I don't understand why Steam set that 🙄

In case there's a reason for it, the change that needs to be made is here: https://github.com/IsThereAnyDeal/AugmentedSteam/blob/819495c5d2856540201d12edd4bc73864ba3b790/src/css/augmentedsteam.css#L1273-L1279

Maybe we can set it to 501.

**Comment by Trsnaqe** [comment]
You are right, reverted removing that z-index 500 and set container index to 501.
