### ISSUE TITLE
[FEATURE REQUEST] Add link to Pricempire inventory

### ISSUE THREAD

**Issue by Nockkk** [IsThereAnyDeal/AugmentedSteam#2012]
### Current Behavior (if any)
Right now, the extension doesn't have a direct link to Pricempire.
https://pricempire.com/

### Desired Behavior
Have a new direct link to the Pricempire inventory page.
Something like this: https://pricempire.com/inventory/76561198282902922
I made a small test, and I was able to make the integration using this custom link: "https://pricempire.com/inventory/[ID]".

### Motivation / Use Case for Changing the Behavior
A lot of people use Pricempire to check how much a skin is worth, or how much their inventory is worth. So having a direct link to Pricempire is a good thing to do.

**Comment by candela97** [comment]
I don't think we'll be adding anymore built-in ones since  there're quite a few already covering a wide range of services, and as you found out, you can make custom links yourself. Let us know if the functionality is lacking in any way though!
