### ISSUE TITLE
[BUG] Third-party cookies...

### ISSUE THREAD

**Issue by beweress** [IsThereAnyDeal/AugmentedSteam#2014]
### Expected Behavior

Today my Augmented Steam stops working. I'm using Opera last version. 

### Actual Behavior

This is what happened in a console:
CurrencyManager.ts:103 Failed to initialize Currency
(anonymous) @ CurrencyManager.ts:103
CurrencyManager.ts:104 Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
    at Y (browser-polyfill.js:1154:18)
(anonymous) @ CurrencyManager.ts:104
Page.ts:64  Augmented Steam v4.0.1  https://augmentedsteam.com
DOMHelper.ts:38 Uncaught Error: Extension context invalidated.
    at oe.insertScript (DOMHelper.ts:38:33)
    at te.dispatchEvent (Messenger.ts:10:19)
    at te.call (Messenger.ts:16:14)
    at _e.showMenu (SteamFacade.ts:57:19)
    at HTMLSpanElement.t (AugmentedSteamMenu.svelte:26:21)
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.

### Specifications

  - Augmented Steam Version: Last ver.
  - Browser Version: Opera last ver.
P.S. I'm using RUB currency and a Russian language. I tried to change language to English, and my Steam inventory just look different and that's all, I still can't quick sell items.

**Comment by 0x0054** [comment]
https://isthereanydeal.com is down so that is probably why it's not working, nothing to do with the cookie message.

**Comment by candela97** [comment]
Yep, this should be fixed by now. Let us know if it's still an issue.
