### ISSUE TITLE
[BUG] Listed games get hidden in the wishlist

### ISSUE THREAD

**Issue by Katzenwerfer** [IsThereAnyDeal/AugmentedSteam#2042]
### Expected Behavior

Games that haven't been removed/unlisted should show up normally in the wishlist

### Actual Behavior

Random games will be identified as hidden/unlisted and will not be shown in the wishlist.

In the image, both games are listed in the Steam store, so they shouldn't be identified as hidden/unlisted.

![image](https://github.com/user-attachments/assets/8365f7d9-fd31-4615-8812-5af63584c083)

### Steps to Reproduce the Problem

  1. Open one's own wishlist
  2. Check the hidden games in the stats menu

### Specifications

- Augmented Steam Version: 3.3.1
- Browser Version: LibreWolf 129.0.2-1

**Comment by candela97** [comment]
If the games indeed don't show up, that's a Steam issue.

**Comment by candela97** [comment]
Closing for now due to the comment above.
