### ISSUE TITLE
[BUG] Augmented Steam Is-Error Undefined

### ISSUE THREAD

**Issue by alkaris2** [IsThereAnyDeal/AugmentedSteam#2049]
![image](https://github.com/user-attachments/assets/e0ea40a3-d75e-4631-8704-2ca37209363e)
Upon loading Steam, Augmented Steam just shows an error failing a fetch request

![image](https://github.com/user-attachments/assets/ec5fe13c-9bad-4703-9875-298c9ccac797)
with Augmented Steam enabled it introduces undefined error with `h1-check.js` script, and then adds another undefined error that basically has no description because it's just `Error: Error` these errors do indeed go away after disabling the extension.

### Specifications

  - Augmented Steam Version: 4.1.1
  - Browser Version: Firefox 130

**Comment by candela97** [comment]
I think this error might be coming from other extensions. Please test in a brand new browser profile with *only* AS enabled.

**Comment by candela97** [comment]
Closing due to no actionable info.
