### ISSUE TITLE
[BUG] Historical low prices still displayed when other store comparison is disabled

### ISSUE THREAD

**Issue by cbconne** [IsThereAnyDeal/AugmentedSteam#2055]
### Expected Behavior
When the "Compare with all stores" option is disabled and specific stores are manually selected for comparison, the Steam store shouldn't display historical low prices from other stores.

### Actual Behavior
![image](https://github.com/user-attachments/assets/fac06222-4b26-45aa-90b7-1bb575037d48)
![image](https://github.com/user-attachments/assets/e417e7ce-67ce-49c2-a314-59c843a1b1f2)

### Steps to Reproduce the Problem

  1. Set the price comparison as shown in the screenshot above;
  2. Open the store page for ROCKMAN EXE(https://store.steampowered.com/app/1798010/ROCKMAN_EXE_1/).

### Specifications

  - Augmented Steam Version: 4.1.2
  - Browser Version: Edge 128.0.2739.79

**Comment by tfedor** [comment]
This is an ITAD side bug and will be fixed in next ITAD update.
