### ISSUE TITLE
[BUG] Enter key reverted to not saving.

### ISSUE THREAD

**Issue by markwr** [IsThereAnyDeal/AugmentedSteam#2057]
### Expected Behavior
During "Update note", the [Enter] key saves the new/edited note and exits the update.

### Actual Behavior
During "Update note", the [Enter] key exits the update without saving the new/edited note.

### Steps to Reproduce the Problem

  1. Go to store.steampowered.com for a specific game.
  2.  Click [Update note].
  3.  Edit the note.
  4. Press the [Enter} key on keyboard.
  5. Observe that it exits from the edit box, and the note reverts back to whatever it had been before trying to edit it.

### Specifications

  - Augmented Steam Version: 4.1.2
  - Browser Version: Firefox 130.0.1 (32-bit)

NOTE: See https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1288 which ended up with you implementing the ability I describe above under "Expected Behavior" (around Nov 1, 2021). That ability recently became corrupted, likely during an update.

**Comment by candela97** [comment]
Seems like a browser difference because it works on Chrome.

**Comment by markwr** [comment]
I wanted to test the fix, but Augmented Steam Version: 4.1.2 is still the newest published version at the moment. I'll need to wait for the next version before I can test the fix.

**Comment by candela97** [comment]
You can download a build for the linked PR here https://github.com/IsThereAnyDeal/AugmentedSteam/actions/runs/11032651093

**Comment by markwr** [comment]
I'm a bit embarrassed to admit that I don't know how to install via that link (Build Augmented Steam (firefox) / Build firefox), ie how/where to run any of those commands. Perhaps I just need to wait for an official release. Thanks anyway.

**Comment by candela97** [comment]
No need to run any commands, just download a build from the Artifacts section below. To sideload on FF, enter `about:debugging` in the address bar and select this firefox > load temporary addon.

**Comment by markwr** [comment]
Thanks! I downloaded Firefox.zip to an external USB hard drive (assigned X:) and decompressed it there to:
  DIR X:\firefox\css\
  DIR X:\firefox\html\
  DIR X:\firefox\img\
  DIR X:\firefox\js\
  DIR X:\firefox\localization\
  DIR X:\firefox\scriptlets\
33883 X:\firefox\changelog.json
35185 X:\firefox\LICENSE
29249 X:\firefox\manifest.json

At the "about:debugging#/runtime/this-firefox" page I click [Load Temporary Add-on...] and it wants me to pick either a file or directory (folder). I'm hesitant to do so without one more hint from you since I don't want to screw up FF. My guess would have been to select the folder X:\firefox\ but I'll wait for your response (if you have time). Thanks.

ps - The about:debugging page also shows my installed extensions, including "Augmented Steam". Would I first disable that official Augmented Steam version before I "sideload" (whatever that means) the beta version? And, later (when the new release version comes out, would I just uninstall the beta version and Enable the official version (and tell it to update)?

**Comment by candela97** [comment]
> At the "about:debugging#/runtime/this-firefox" page I click [Load Temporary Add-on...] and it wants me to pick either a file or directory (folder). I'm hesitant to do so without one more hint from you since I don't want to screw up FF. My guess would have been to select the folder X:\firefox\ (or else one of the three files in the parent folder), but I'll wait for your response (if you have time). Thanks.

Selecting any file will do.

> ps - The about:debugging page also shows my installed extensions, including "Augmented Steam". Would I first disable that official Augmented Steam version before I "sideload" (whatever that means) the beta version? And, later (when the new release version comes out, would I just uninstall the beta version and Enable the official version (and tell it to update)?

The offical one will also be disabled when you sideload a temporary one, and it will also be removed automatically after you restart FF.

**Comment by markwr** [comment]
Thank you. At the FF about:addons page, I first "Disabled" my release version of the FF Augmented Steam extension (maybe an unnecessary step) . Then I "sideloaded" the beta version. I notice that about:addons now shows Augmented Steam under "Enabled" and nothing under "Disabled" (so I assume it just "replaced" it?). I wonder if all my settings were preserved (on 9/13/24 I did make a backup of my option settings in a file I named "ffe Saved Options AugmentedSteam_v4.1.1.json" which I assume I could restore if needed). I tested the fix and it does work for me (THANKS). When the update is released will it automatically replace the installed beta?

**Comment by candela97** [comment]
Settings should persist. Temporary addons are removed when you restart FF and will also not update.

**Comment by markwr** [comment]
"Temporary addons are removed" ... will my release version come back at that point or will I have to reinstall it? Thanks.

**Comment by candela97** [comment]
Temporary addons are just temporary and don't affect the installed one, other than some limitations such as shared storage.

**Comment by markwr** [comment]
I'm pulling my hair out waiting for the next update so I can start using this wonderful crucial fix (I keep forgetting and hit enter and thus have to retype my notes again). One other thing I would love to go back to is the ability to press the Escape key to exit from the message edit box (vs having to click [Cancel], could that be added in a similar fashion that you used to activate the Enter key action? Or, do I need to create a new request (and it so would it be a BUG or a FEATURE/Suggestion request)? Thanks.

**Comment by candela97** [comment]
That might be a side effect of preventing clicking outside of the dialog from closing the dialog and losing the note by accident. I'll see if it can be restored without too much trouble.

**Comment by markwr** [comment]
Thank you, that would be great if you can.
