### ISSUE TITLE
[BUG] Augmented Steam Failing To Load in Game Pages

### ISSUE THREAD

**Issue by lucasricci** [IsThereAnyDeal/AugmentedSteam#2059]
### Expected Behavior
Augmented Steam loads correctly and displays the green mark in the top of the page

### Actual Behavior
The extension fails to load and displays a red mark and say it failed to load

![25_09_2024_12_17_971_firefox](https://github.com/user-attachments/assets/301fae9b-7123-4941-861c-15038b5bc16f)

### Steps to Reproduce the Problem

  1. Open [https://store.steampowered.com/](https://store.steampowered.com/);
  2. Click on any game;
  3. The issue happens;

### Specifications

  - Augmented Steam Version: 4.1.2
  - Browser Version: Firefox 131.0

### More
The interesting thing is that when I log out from my steam account the issue doesn't happen anymore. I may be doing something wrong.

**Comment by lucasricci** [comment]
Never mind, I fixed the issue by just clicking in `Community`. I think the extension did not know that I was logged in `https://steamcommunity.com/`?

**Comment by candela97** [comment]
The only features that can cause this iirc are ones that fetch your inventory, e.g. show applicable coupon and highlight games with available coupons/gifts. This only affects those features and nothing else, so you can disable them if you don't want to see this error, or just navigate to any community page and it'll go away.
