### ISSUE TITLE
[BUG] Price filters on Wishlist page are broken

### ISSUE THREAD

**Issue by Eiion** [IsThereAnyDeal/AugmentedSteam#2070]
### Expected Behavior
Select one of the Price filters on the Wishlist page and only see titles which are less than the selected filter states.

### Actual Behavior
"Less than 5" as well "Less than 10" filter something, but certainly not everything that should be filtered.
Only the Less than Steam Wallet filter appears to be working correctly (though that might just be happenstance.

### Steps to Reproduce the Problem

  1. Visit Wishlist page
  2. Select Filter
  3. See that it's not working as expected

### Specifications

  - Augmented Steam Version: 4.1.2
  - Browser Version: Chrome Version 129.0.6668.101 (Official Build) (64-Bit)

**Comment by candela97** [comment]
Can you try with AS disabled? I believe this is a bug with Steam.

**Comment by Eiion** [comment]
That is correct - it appears to be a Steam bug, not one with the extension.
