### ISSUE TITLE
[BUG] Price History Information when hovering over wishlist items doesn't show

### ISSUE THREAD

**Issue by lashatatu** [IsThereAnyDeal/AugmentedSteam#2084]
### Expected Behavior
When hovering over wishlist items IsThereAnyDeal was showing up week ago 

### Actual Behavior
When hovering over the wishlist it has a default behavior

### Steps to Reproduce the Problem

  1.  go to wishlist
  2.  hover over wishlist item
 

### Specifications

  - Augmented Steam Version: 4.1.2
  - Browser Version: Brave Browser Version 1.73.91,  Chrome Version 131.0.6778.86

**Comment by k3kin** [comment]
same

**Comment by candela97** [comment]
The underlying cause is the same as #2080, so marking as a duplicate of that umbrella issue. We're working on it!
