### ISSUE TITLE
[BUG] App Page Custom Links make the app page side bar disappear

### ISSUE THREAD

**Issue by bxko** [IsThereAnyDeal/AugmentedSteam#2092]
### Expected Behavior
I've got custom links that should appear on app pages in the side bar but after the latest update they no longer appear.  It used to be only links that included an & symbol were broken (which I had a tampermonkey script fix for) but now none show when you have custom links enabled.

### Actual Behavior
No links in the sidebar.

### Steps to Reproduce the Problem

  1. If I have any custom links enabled then no links will appear in the sidebar, not even the included 3rd-party site ones.
  2. If I have no custom links enabled then the included 3rd-party site ones will appear just fine.
  3. 

### Specifications

  - Augmented Steam Version: 
  - Browser Version:

**Comment by candela97** [comment]
Custom links related issues should be fixed on v4.2.1, which will be available once it clears store review. As a workaround, you can add a protocol `https://` or `http://` to all of your links.
