### ISSUE TITLE
Move the player count on the store pages

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/AugmentedSteam#214]
The player count is displayed where system requirements are by default and requires far too much scrolling in my opinion. The number of players is an extremely important metric for online games and deserves more prominent position. I also recommend moving this data to the right-hand column to avoid wasting space, like the [Steam Database addon](https://steamdb.info/extension/) does:

![2019-04-06 21_24_08-Save 70% on Borderlands_ The Pre-Sequel on Steam](https://user-images.githubusercontent.com/14923168/55673592-8e84c680-58b2-11e9-90f4-c489ab3c0e07.png)

**Comment by MxtOUT** [comment]
Since these pieces of information are only really relevant for online games, I'd implement this by somehow determining whether the game is a multiplayer game (e.g. by checking the tags) and then placing it accordingly

**Comment by 07416** [comment]
> 
> 
> Since these pieces of information are only really relevant for online games, I'd implement this by somehow determining whether the game is a multiplayer game (e.g. by checking the tags) and then placing it accordingly

I don't entirely agree since the playercounts can be vaguely used to estimate especially launch sales, personally I check this information always when visiting a game's store page.

**Comment by tfedor** [comment]
And it would be better to have it consistently on one place

**Comment by Revadike** [comment]
You could disable certain panels to make player count start higher up the page:
![image](https://user-images.githubusercontent.com/4411977/64481620-e9af4200-d1df-11e9-9952-ee6aedbcc10c.png)

Personally, I kinda like how it looks now. So, instead I suggest to make it optional to either have it as main section or in the sidebar.
But why stop there? It would be cool if you could personalize the structure of the app store page. Think of choosing what panels you want to show, in what order and what place (sidebar or main).
