### ISSUE TITLE
No quicksell buttons on Firefox

### ISSUE THREAD

**Issue by wojnarw** [IsThereAnyDeal/AugmentedSteam#272]
No quicksell buttons in inventory.
![image](https://user-images.githubusercontent.com/50807860/57987205-9ffaea00-7a7e-11e9-84e2-173542a58e7c.png)

Other functions seem to be working, but I didn't check them all. Changing Steam language to English doesn't help.

Firefox 66.0.5 (64bit) newest.
Only uBlock Origin is installed, but turning it off doesn't help.
Aug Steam 0.97.
Clearing cache or restarting browser and addon didn't help.

**Comment by MxtOUT** [comment]
Does this only not work for CS:GO keys or for all items?
Also, do you see a red exclamation mark inside a circle or a green circle in the top right corner?

**Comment by USERNAME-ALREADY-TAKENN** [comment]
For all games. There is green dot in top right.

**Comment by MxtOUT** [comment]
Seems like items in other inventories than the "Steam" inventory won't get a quick sell button https://github.com/tfedor/AugmentedSteam/blob/0577061e6615a90ddb879fd294ce3af54c93e511/js/content/community.js#L1536

**Comment by candela97** [comment]
Quick Sale buttons should be available on both Steam and non-Steam items now. Please open a new issue if you notice an item that's missing this feature, thanks!
