### ISSUE TITLE
[Feature Request] Split all games page into multiple pages

### ISSUE THREAD

**Issue by vgezer** [IsThereAnyDeal/AugmentedSteam#307]
You can see all games you own on: https://steamcommunity.com/my/games/?tab=all, but having thousands of game slows down the page.

It would be nice to limit the results to 50 or 100 per page and have new pages for the rest of the games.

**Comment by Revadike** [comment]
At some point that page is just broken if you have too many games (like me). So, perhaps it's better to build an entirely new page (maybe https://steamcommunity.com/my/games/?tab=es_all) from DynamicStore data, which will also include DLC and non-public/removed apps. However, that only includes owned appids and no game information. For that, we need to find another solution.

**Comment by candela97** [comment]
See also #622.

**Comment by MxtOUT** [comment]
If we can find a proper solution to this, but I assume that by this time Steam has implemented this already

**Comment by Revadike** [comment]
> If we can find a proper solution to this, but I assume that by this time Steam has implemented this already

I think it depends on how many more years you want to wait

**Comment by MxtOUT** [comment]
Closing this as #622 is also closed and there doesn't seem to be a solution that is reasonably complex
