### ISSUE TITLE
[Suggestion] Multiple item quick sell...

### ISSUE THREAD

**Issue by kriki200** [IsThereAnyDeal/AugmentedSteam#333]

**Comment by Revadike** [comment]
It would be awesome if https://github.com/Nuklon/Steam-Economy-Enhancer/ can be merged with Augmented Steam @Nuklon

**Comment by phrostb** [comment]
yes please

**Comment by scowalt** [comment]
[Steam Inventory Helper (Chrome extension)](https://chrome.google.com/webstore/detail/steam-inventory-helper/cmeakgjggjdlcpncigglobpjbkabhmjl?hl=en) supports this feature nicely as well.

**Comment by MxtOUT** [comment]
Yeah, it does it's job, but I heard it's shady af (SIH)
