### ISSUE TITLE
Steam market helper

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#390]
Implement the features of the excellent https://github.com/Nuklon/Steam-Economy-Enhancer/ by @Nuklon.

**Comment by Revadike** [comment]
https://github.com/tfedor/AugmentedSteam/issues/333

**Comment by phrostb** [comment]
great idea!

**Comment by phrostb** [comment]
@Nuklon would you be interested?

**Comment by MxtOUT** [comment]
I also thought about adding some nice inventory functions, but I don't know the linked userscript

**Comment by Revadike** [comment]
> I also thought about adding some nice inventory functions, but I don't know the linked userscript

It's a popular one. You should try it.

**Comment by MxtOUT** [comment]
Now tracked in #1686
