### ISSUE TITLE
Fix disabled gift recipients 

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#406]
Allows you to send Steam gifts to friends even if they already own it.

```js
var radioButtons = document.getElementsByName("friend_radio");

	for (var i = 0, l = radioButtons.length; i < l; i++) {
		radioButtons[i].disabled = false;
	}
```

**Comment by tfedor** [comment]
But, why?

**Comment by Revadike** [comment]
Why? So you can send gifts to friends, no matter if they own it already. For collecting or trading, for example. This check is only implemented in UI.

**Comment by Revadike** [comment]
Since this issue hasn't been closed yet, perhaps you can give it another chance?

**Comment by candela97** [comment]
The PRs have also been closed, so I guess this is a wontfix for now. Also https://github.com/IsThereAnyDeal/AugmentedSteam/pull/409#issuecomment-522276805
