### ISSUE TITLE
Show hidden steam wishlist entries

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#407]
Removed and non-public steam apps don't get showed in your steam wishlist. Show these hidden steam wishlist entries.
So, implement the features from https://greasyfork.org/scripts/38714 by @Revadike.
Userdata actually doesn't need to be aquired, as all appid's are already present in the `g_rgWishlistData` variable. The problem is that `g_rgAppInfo` doesn't include these apps, so we're missing app info. My userscript solves this problem by getting this info from steam-tracker, but this could also be provided by AS's backend API.

**Comment by Revadike** [comment]
So, for this to be implemented to I need to be able to request some game data from AS's server.

**Comment by MxtOUT** [comment]
Why would you want removed and non-public apps in your wishlist if you can't buy them?

**Comment by Revadike** [comment]
> Why would you want removed and non-public apps in your wishlist if you can't buy them?

You can often still buy them, elsewhere. For example: https://steam-tracker.com/
Many sites allow you to import steam wishlist, where you want also these non-public apps included.
This feature is useful, as it allows you to manage these non-public apps (change order, remove, etc).

**Comment by candela97** [comment]
Steam themselves even have a TODO in wishlist.js to inject a placeholder app for missing items 😄. The other thing I want to see is to have the number of hidden apps displayed in our Stats section.
