### ISSUE TITLE
Show date of releases

### ISSUE THREAD

**Issue by MxtOUT** [IsThereAnyDeal/AugmentedSteam#454]
In the options page under "News": Show for every version when it got released.
Also this page could look a bit better ;)

**Comment by Revadike** [comment]
How about using GitHub API?

```js
await fetch("https://api.github.com/repos/tfedor/AugmentedSteam/releases", { credentials: "omit" }).then(res => res.json());
```

This way, patch nodes could be organized into 1 place. Improves maintainability.
The API supports pagination, which we can also implement.
If this is OK with you, you could assign me to this.

**Comment by MxtOUT** [comment]
Hm, with GitHub we wouldn't be able to have custom behavior like being able to click on a button in the changelog (we had that in the past).
Also the formatting of the GitHub releases isn't very pretty (e.g. instead of HTML lists we're using simple dashes).

With these restrictions it would only be viable in the options page, but I don't see a reason why you would want that.
History is history and should not be mutated afterwards anyway, we don't need it to be maintainable.

**Comment by Revadike** [comment]
> click on a button in the changelog (we had that in the past)

What was the reason for such a button?

> Also the formatting of the GitHub releases isn't very pretty (e.g. instead of HTML lists we're using simple dashes).

I wouldn't call dashes prettier than bullet points, but that's just an opinion. You can do either anyway (see below). GitHub has full markdown support, and even some basic HTML support. So you can do a lot to make it pretty. 

 * Bullet point

 \- Dash point
 
 > With these restrictions it would only be viable in the options page, but I don't see a reason why you would want that.
 
I don't really understand this sentence. You can use the API to only get the latest version changelog (limit=1) for showing new features after update. In options, you can implement pagination and dynamically load changelog at the user's convenience. 

> History is history and should not be mutated afterwards anyway, we don't need it to be maintainable.

As long as update notes match, no history is altered. I see no reason to deny maintainability improvements.

**Comment by MxtOUT** [comment]
> What was the reason for such a button?

You could directly connect your AS instance to your ITAD account from the changelog

> I don't really understand this sentence. You can use the API to only get the latest version changelog (limit=1) for showing new features after update. In options, you can implement pagination and dynamically load changelog at the user's convenience.

I was referring to the two points I've given before, i.e. the limited styling and scripting possibilities.

> As long as update notes match, no history is altered. I see no reason to deny maintainability improvements.

We're creating more external dependencies here. But I see that it could be easier to maintain.

Maybe we could attach the HTML file as an asset to the corresponding release on GitHub and then download it.
This could maybe work...

**Comment by Revadike** [comment]
Or maybe... 🤔
![image](https://user-images.githubusercontent.com/4411977/124030644-aea28200-d9f6-11eb-955d-07c0deed77ba.png)
![image](https://user-images.githubusercontent.com/4411977/124030672-b4986300-d9f6-11eb-80e5-883fe8278b66.png)

**Comment by MxtOUT** [comment]
But how do we want to access extension modules from this file? This will be hardly doable with webpack

**Comment by Revadike** [comment]
> But how do we want to access extension modules from this file? This will be hardly doable with webpack

What do you mean exactly?

**Comment by MxtOUT** [comment]
We would want to call some function like ITAD.authorize() for example from the release notes HTML.
But this is not so easy when using webpack

**Comment by Revadike** [comment]
> We would want to call some function like ITAD.authorize() for example from the release notes HTML.
> But this is not so easy when using webpack

How are you doing it now?

**Comment by candela97** [comment]
The problem is store review time varies, so displaying the release date from Github is not very useful. We also link to this repo in the update dialog, so those interested can check it out themselves, or even better, join our Discord to get notifications.

I forgot how the page looked back in 2019, but it should be better now 😆
