### ISSUE TITLE
Activity page highlighting

### ISSUE THREAD

**Issue by MxtOUT** [IsThereAnyDeal/AugmentedSteam#456]
On the activity page it makes no sense to highlight items that you wishlisted or bought as such (only in the row where it says that you wishlisted or bought it).

Also, for single app blocks (like reviews or screenshot uploads) you could color the whole background instead of just the app name

**Comment by Revadike** [comment]
> On the activity page it makes no sense to highlight items that you wishlisted or bought as such (only in the row where it says that you wishlisted or bought it).

Why would this matter, though? Why does it make more sense to disable highlighting? Sure, it's really trivial, but that's the sense of university. 

> Also, for single app blocks (like reviews or screenshot uploads) you could color the whole background instead of just the app name

Good idea.

**Comment by MxtOUT** [comment]
> Why would this matter, though?

You might be only looking for these highlights to see if other friends played a game on your wishlist or in your library.
Then it's distracting to see this redundant information.

**Comment by candela97** [comment]
> On the activity page it makes no sense to highlight items that you wishlisted or bought as such (only in the row where it says that you wishlisted or bought it).

So, disable highlighting on rows that say you unlocked achievements for some game, followed some game, played some game for the first time, .etc?
I'm not sure how we can distinguish those rows from each other, apart from parsing the text, which is localised.

> Also, for single app blocks (like reviews or screenshot uploads) you could color the whole background instead of just the app name

For both friends and curator reviews, an excerpt of the review is displayed, and I think the text is more readable with Steam's original background.

**Comment by candela97** [comment]
I think highlighting should also be disabled on user-provided links, i.e. links in announcements, comments, etc. These don't come up often, since in posts the first 10 or so links are displayed as widgets, but highlighting random links in comments doesn't seem helpful either.

**Comment by MxtOUT** [comment]
> I'm not sure how we can distinguish those rows from each other, apart from parsing the text, which is localised.

Can't you compare the player that this row "belongs to" with the logged in user?

> For both friends and curator reviews, an excerpt of the review is displayed, and I think the text is more readable with Steam's original background.

Yeah, hm, doesn't look that good if I try it too

> I think highlighting should also be disabled on user-provided links, i.e. links in announcements, comments, etc. These don't come up often, since in posts the first 10 or so links are displayed as widgets, but highlighting random links in comments doesn't seem helpful either.

I mean, why are those links random?
They must be pointing to an app / community page of some sort

**Comment by Revadike** [comment]
I know you want to avoid options, but I think this is a good case to turn into an option, so it follows user preference.

**Comment by candela97** [comment]
> Can't you compare the player that this row "belongs to" with the logged in user?

I thought you wanted to only highlight items that you wishlisted or bought in the row which says you wishlisted or bought it?

> > I think highlighting should also be disabled on user-provided links, i.e. links in announcements, comments, etc. These don't come up often, since in posts the first 10 or so links are displayed as widgets, but highlighting random links in comments doesn't seem helpful either.
> 
> I mean, why are those links random?
> They must be pointing to an app / community page of some sort

Without proper markup tags it just looks like a random highlighted link. On activity logs it highlights the name of the game which is much more recognisable.

**Comment by MxtOUT** [comment]
Skipping highlighting for activities attributed to yourself doesn't seem worth it after all, closing
