### ISSUE TITLE
How long to Beat section - "Wrong game?" link not working

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/AugmentedSteam#473]
![註解 2019-08-20 015059](https://user-images.githubusercontent.com/54083835/63300890-dcebac80-c30b-11e9-9d8a-2fb047174b5f.jpg)

links to
https://es.isthereanydeal.com/gamedata/hltb_link_suggest.php

on a side note, "More Information" links should be updated to use `https://howlongtobeat.com/game.php?id=`

**Comment by Revadike** [comment]
I'm not sure where the "Wrong game?"-link is supposed to link to @tfedor

**Comment by NLZ** [comment]
After the functionality is re-added, please make sure it works with games which it cannot find results, like https://store.steampowered.com/app/463270/Ghost_10/ (btw its it in HLTB: https://howlongtobeat.com/game.php?id=37834)

**Comment by candela97** [comment]
Link has been removed in faeddc88ba10a78e0401b557fa419dbe7cc7099b
