### ISSUE TITLE
Cookies/Tracking control

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#477]
This idea came to me, when the steam store kept giving http status 500, caused by some broken cookie, and I've noticed that are a lot of unnecessary tracking cookies enabled by steam.
It would be nice to have an option to disable them, by expiring the non-vital cookies every time you load a page. 
I believe these are the one vital ones for steam store:
![image](https://user-images.githubusercontent.com/4411977/63355348-47c9d180-c366-11e9-94af-6c4aa8f7649b.png)

**Comment by MxtOUT** [comment]
But should this be managed by AS?

**Comment by Revadike** [comment]
> But should this be managed by AS?

Why not? I doubt Steam would implement this.

**Comment by MxtOUT** [comment]
That's similar to the safe-from-phishing message, it's just not AS' area of responsibility

**Comment by candela97** [comment]
https://store.steampowered.com/account/cookiepreferences

I guess this is the best we can get out of Steam. I agree this isn't something that should be managed by AS. Content blockers like uBlock Origin are are much better equipped to handle tracking cookies.

**Comment by Revadike** [comment]
Maybe a clear cookies function? Present it (as a troubleshoot step) when AS has some issues or detects something weird.

**Comment by MxtOUT** [comment]
This is not a task that should be done by AS
