### ISSUE TITLE
Option to exclude VR Only games in search

### ISSUE THREAD

**Issue by kirara** [IsThereAnyDeal/AugmentedSteam#527]
Steam natively supports including only VR Supported and/or VR Only games but nothing to filter them out. With AS I can exclude VR tag, but it's not the same.

**Comment by candela97** [comment]
Dunno when this was added, but Steam supports this option now
![螢幕擷取畫面 2022-05-19 231238](https://user-images.githubusercontent.com/54083835/169331173-8d7d4ae7-4cb6-453f-84a1-87fda65714e6.jpg)
