### ISSUE TITLE
[Feature Request] Add Tag filter to My Games list

### ISSUE THREAD

**Issue by BuddhaBuddy1** [IsThereAnyDeal/AugmentedSteam#558]
Having a box on the right that lets you select from all the tags on your game list to include and/or exclude would finally make that list useful.

**Comment by candela97** [comment]
Tags metadata is not available on Games page, and fetching it for each game would amount to a lot of requests. Not sure if this is doable.

**Comment by candela97** [comment]
Alas we still can't search by tags on the new Games list, but now the page uses React this is even more infeasible than before :(
On the bright side it's supported in the client.
