### ISSUE TITLE
Search results labeled "not-interested" when games are marked as owned elsewhere.

### ISSUE THREAD

**Issue by BlacRyu** [IsThereAnyDeal/AugmentedSteam#567]
Currently in search results all ignored games at treated the same way. The result is greyed out and labeled as "not-interested". 

![image](https://user-images.githubusercontent.com/10762433/66290363-e4ebb580-e893-11e9-862c-f57d06aa3318.png)

However, Steam now supports labeling ignored games as "owned/played elsewhere" instead of "not interested". It would be nice if Augmented Steam would recognize this and label the game as such in search results. Perhaps make the result dark green instead of grey to indicate that the game is owned but not on Steam.

**Comment by MxtOUT** [comment]
There are some upcoming changes to highlighting with the ITAD integration, where we planned to highlight games in your ITAD collection in yellow.

But I don't know whether we should have the same color for games marked as owned on another platform.
I mean, technically, a game that is owned elsewhere, should also be in your collection, but maybe we still need to distinct between that?

**Comment by candela97** [comment]
Looks like Steam doesn't distinguish between these two kinds of "ignore" either, at least according to available search filters, so this might be difficult to achieve using Steam alone.

**Comment by candela97** [comment]
Scratch out my last comment. We can check the value assigned to the appid in `rgIgnoredApps` dynamicstore object. `0` is the default ignore, `2` is ignored as "owned/played elsewhere".

**Comment by r6d2** [comment]
Thanks a lot!
