### ISSUE TITLE
No Add To Cart Redirect

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#689]
Original idea came from [here](https://www.reddit.com/r/Steam/comments/e8hsjs/just_let_me_unwish_directly_from_the_storepage/fadd8md?utm_source=share&utm_medium=web2x).
Instead of automatically redirecting to cart after pressing "add to cart", it could show a dialog with an option to go to cart, to have an animation play and scroll to top.

**Comment by candela97** [comment]
I think having an option to enable/disable redirecting should suffice.
Also I think the page will need to be reloaded for Steam to update the page, so scroll to top can be added by default, or as a separate option.

**Comment by brian6932** [comment]
This would be extremely useful, the steam cart redirect is super annoying

**Comment by SonOfDiablo** [comment]
I have never done bulk purchasing on Steam before, but I wanted to pickup some cheap games on my wishlist... the redirect thing is a real bother and there seem to be no fix out there yet...

So if AS can do something about the problem that would be amazing!
