### ISSUE TITLE
Update Price History with page info

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#698]
![image](https://user-images.githubusercontent.com/4411977/71046011-47d0b700-2137-11ea-97f0-637a95a979b5.png)

I know it's impossible to request updated price information on demand, but one way to avoid the above from happening is by comparing the current steam price with the data you have and update accordingly (client-side). This makes it less confusing.

**Comment by Revadike** [comment]
Here's another example:
![image](https://user-images.githubusercontent.com/4411977/76347611-35fe4a80-6307-11ea-9dbe-d807d61339ce.png)

from https://store.steampowered.com/app/397540/Borderlands_3/

**Comment by candela97** [comment]
This should be handled better after years of work on ITAD.
