### ISSUE TITLE
[Bug] YouTube Reviews on store page showing incorrect game review

### ISSUE THREAD

**Issue by Whoareyouagain** [IsThereAnyDeal/AugmentedSteam#707]
One game store page is showing the wrong game review on the game. The game is [Uncharted Ocean](https://store.steampowered.com/app/1158690/Uncharted_Ocean/) and the review in the store page is showing Oceanhorn: Monster of Uncharted Seas. I can see why it is using that review since the reviewer of the video didn't combine Ocean & Horn together. It made sense for AE to chose this review.

I wonder if there a way to search strictly for the game. If the title of YouTube is not using the correct title, can it exclude it? I don't think this suggestion would work since it will have weird issue down the line.

**Comment by Revadike** [comment]
Hmm, maybe using quotation marks around the game title in the search would get more accurate results.

**Comment by Whoareyouagain** [comment]
I believe it use the quotation marks for search query. I clicked the YouTube review and it show quotation marks in the URL which lead me to believe that it uses quotation marks. 

What is weird for me is that I cannot find the video of that particular review when I tried to search it in YouTube. I tried different search operators and change the keywords around. I just can't find that review via searching. I wonder how the heck Augmented Steam managed to find that review.

**Comment by RobsonMoon** [comment]
Another example is for the game [New Cities](https://store.steampowered.com/app/1067860/New_Cities/) which is showing a review for [Cities XXL](https://store.steampowered.com/app/313010/Cities_XXL/).

**Comment by Kissaki** [comment]
LineWay shows two hardware cable tutorial videos or something https://store.steampowered.com/app/661430/LineWay/

**Comment by Revadike** [comment]
Hmm, I have an idea. How about we search the app community videos instead? Those should definitely be reverent to the app, right?

**Comment by MxtOUT** [comment]
Not a lot of videos land on the community page I think, which would hurt overall quality.
Imo the current query gets very good results, ofc unpopular apps are in most cases not getting the intended results

**Comment by Kissaki** [comment]
It’s not really about unpopular apps though. Whether or not they are popular does not change whether incorrect results appear or not.

I don’t know how the query is constructed, but it includes other stuff for one reason or another. For LineWay it seems to be an ambiguous, generic name that is used in a different context as well.

**Comment by MxtOUT** [comment]
For Lineway the query is `intitle:"LineWay Review" "PC"`.

And I didn't mean that the query changes with popularity, I meant that more popular titles are more likely to have better search results

**Comment by Kissaki** [comment]
If those are the keywords, it seems pretty obvious where wrong listings are to be expected.

From the top of my mind I remembered a Steam game by the name of Circuits, checked out the [Steam store page](https://store.steampowered.com/app/282760/Circuits/), and sure enough it lists two YouTube videos for a completely different Commodore game.

Was there any analysis into balancing how restrictive the query should be? Is this documented somewhere? With all these false positives it is obvious it is not restrictive enough to prevent them. Is there a good reason to accept these false positives? For example to include a considerable amount of reviews that would otherwise not show up?

**Comment by Revadike** [comment]
> Not a lot of videos land on the community page I think, which would hurt overall quality.
> Imo the current query gets very good results, ofc unpopular apps are in most cases not getting the intended results

How about first search community page and if no results, search youtube afterwards?

**Comment by Kissaki** [comment]
@Revadike It should not be a one or the other. Either the community page reasonably gives (all) relevant videos, or it does not. Either it should be included every time, or not. Either those not on it should be included all the time, or not.

If for example IGN does not post on the community page, it would be a big miss not listing them when in fact they do have a review video available.

**Comment by MxtOUT** [comment]
> If those are the keywords, it seems pretty obvious where wrong listings are to be expected.
> 
> From the top of my mind I remembered a Steam game by the name of Circuits, checked out the [Steam store page](https://store.steampowered.com/app/282760/Circuits/), and sure enough it lists two YouTube videos for a completely different Commodore game.
> 
> Was there any analysis into balancing how restrictive the query should be? Is this documented somewhere? With all these false positives it is obvious it is not restrictive enough to prevent them. Is there a good reason to accept these false positives? For example to include a considerable amount of reviews that would otherwise not show up?

We've been experiencing with the query, we also tried adding `"Game"` to it, but it got too restrictive iirc

**Comment by candela97** [comment]
Sadly this feature is no more and all we have now are 2 links to search directly on YouTube using pre-defined keywords. See #892 regarding support for custom keywords.
