### ISSUE TITLE
Can I close the login warn about "steamcommunity.com" ?

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/AugmentedSteam#724]
![](https://telegra.ph/file/71926c7c59080942bc6fd.png)
But in fact I have logged into the steamcommunity.

I'm not sure what's wrong, but I rejected most cross-origin sharing standard requests.
So...it happened.
Could you add a button to close the warn?

**Comment by MxtOUT** [comment]
Are you logged in with another account?

**Comment by naoko8964** [comment]
> 
> 
> Are you logged in with another account on Community?

No, it's a same account as steampowered.

**Comment by MxtOUT** [comment]
What do you see if you [inspect Augmented Steam's background page](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page)?
Look at the "Network" and "Console" tabs please

**Comment by naoko8964** [comment]
![](https://telegra.ph/file/1ac37cc6745860215a2a6.png)
​![](https://telegra.ph/file/490c6ce739959f99c839f.png)

**Comment by MxtOUT** [comment]
Thanks, could you leave the inspector open, try to reload a Steam page, where you get this error and then post the pictures again please?

**Comment by naoko8964** [comment]
Sorry, i did it wrong last time.
Is it ok now?
![](https://telegra.ph/file/1c936ffa96b23d88c4b20.png)
![](https://telegra.ph/file/bb655a05689e8cec06bd4.png)

**Comment by MxtOUT** [comment]
Yes, thanks!
Could you click on the one request in the "Network" tab and check the details?

**Comment by naoko8964** [comment]
![](https://telegra.ph/file/c477adbbe8ebcd0d57980.png)

**Comment by naoko8964** [comment]
![](https://telegra.ph/file/f98f82447d9ddbf728a4c.png)

**Comment by MxtOUT** [comment]
You should censor the `Set-Cookie` lines too.
How are you rejecting the CORS requests?

**Comment by naoko8964** [comment]
~~I don't know how to use special editing, so i update the `network`.~~
Oh, you deleted the image.
Thanks, and it's Cooke.
![](https://telegra.ph/file/0db0b1a584a4ee3d8e1ad.png)
![](https://telegra.ph/file/9b9f7935ee226fd4de048.png)

I used NoScript and set up a user.js.
I forget what preference i set, but if you need it, i can think of ways to confirm it.
Thanks!

**Comment by MxtOUT** [comment]
Currently there is no way to disable this warning, but I can imagine having a "Dismiss" button and a checkbox "Don't show again" for these kind of warnings.

What you can do now though is (if that's possible with NoScript) whitelist CORS requests for steamcommunity.com.
This would also ensure proper highlighting of coupons, gifts and guest passes, which you can't get if you block these requests.

**Comment by Revadike** [comment]
Why is it blocked in the first place?

**Comment by naoko8964** [comment]
> What you can do now though is (if that's possible with NoScript) whitelist CORS requests for steamcommunity.com.
> This would also ensure proper highlighting of coupons, gifts and guest passes, which you can't get if you block these requests.
Ok, thanks. I will try it.
Waitting your "Don't show again"

> Why is it blocked in the first place? By NoScript?
Maybe I ’m not from an English-speaking country, so I don’t quite understand what you want to express.
If you want to discuss why NoScript blocked the request that looks like ~~appropriate~~, I can't give opinions.
In fact I'm not sure what's the wrong is about even now.

If you want to know why I use the NoScript, I guess that's because it's cool. xd

**Comment by MxtOUT** [comment]
@naoko8964 https://www.ghacks.net/2015/07/09/noscript-tip-check-the-whitelisted-sites-listing/

**Comment by candela97** [comment]
There should be an option for this now if you encounter the warning, let us know if this is not the case.
