### ISSUE TITLE
Search Wishlist by Tags

### ISSUE THREAD

**Issue by wickles** [IsThereAnyDeal/AugmentedSteam#775]
The Steam Wishlist has a search bar that prompts you to "Search by name or tag" but searching by tag has apparently not worked for a few years now. Would be awesome if AS could implement this. 

(I just want to be able to filter for VR titles.. there is an "exclude VR" button but not the opposite lol)

**Comment by candela97** [comment]
Filtering by tags works for me, either by typing the tag or clicking on one of the 5 tags that appear in "expanded" view.

**Comment by MxtOUT** [comment]
Yes, also works for me
