### ISSUE TITLE
Add option: toggle new features by default & toggle all

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#784]
I propose a toggle to disable or enable all features/options. 
Use case 1: I only want 1 or a few select features enabled, so it's easy to first disable everything and then check the one(s) I need.
Use case 2: I want the full experience and all features enabled, so I don't miss out on anything.

I also propose to have an option to enable or disable new features (introduced by an update) by default. This helps enforce the above use cases throughout any updates.

**Comment by candela97** [comment]
We simply need to do better at informing users of new features so they can decide for themselves. Having a toggle to bulk enable/disable a certain group of options might be nice if it makes sense. Best open a new issue with more details if you're still interested.
