### ISSUE TITLE
Feature request: Don't check for lowest price on $0.03 items

### ISSUE THREAD

**Issue by MadonnaC** [IsThereAnyDeal/AugmentedSteam#790]
When checking the prices on the market, the report fails after 23 price checks. If items are on market for $0.03, then they can't go any lower (as steam does not allow a lower price). Skip checking those items, and more of my items can be checked before you get the red exclamation mark (error in console is:
Request URL:https://steamcommunity.com/market/priceoverview/?country=US&currency=1&appid=753&market_hash_name=766370-WELL-TIMED%20PARRY
Request Method:GET
Remote Address:104.112.66.204:443
Status Code:
429 Too Many Requests
Version:HTTP/1.1
)

**Comment by MxtOUT** [comment]
I'm not sure how this works for other currencies

**Comment by candela97** [comment]
I don't think we can do anything about rate limits... excluding some items is not going to help much, how often are you listing items at the minimum price?

Maybe we can do some research on other market-related extensions and see if there's a more efficient way to use the API, but in the mean time, I guess if you get rate-limited you can always navigate to the item's market page to get current lowest price.
