### ISSUE TITLE
[Possible bug] The new Add to Waitlist button doesn't use default price cut settings

### ISSUE THREAD

**Issue by enchained** [IsThereAnyDeal/AugmentedSteam#820]
Games added this way do not use the default settings: I was notified about 0% price cuts a few times.

I inspected the code to see how waitlisting currently works:

https://api.isthereanydeal.com/v01/waitlist/import/?access_token=
{version: "02", data: [{gameid: ["steam", "app/919640"]}]}

The request does not have a price/cut field, and [API docs](https://itad.docs.apiary.io/#reference/waitlist/import-via-form/import-waitlist) say "for omitted fields user's default settings will be used", but that's under the Import via Form, not Direct Import. I wonder if that's a bug or intended API behavior.

Either way, it would be useful to either use ITAD global default, or being able to set another default for the Augmented Steam button specifically.

**Comment by candela97** [comment]
Please file a new issue if there're still problems with the new ITAD, thanks!
