### ISSUE TITLE
Add wishlist checkboxes

### ISSUE THREAD

**Issue by candela97** [IsThereAnyDeal/AugmentedSteam#844]
Similar idea to DLC checkboxes -- let the user select multiple items, and add to cart all at once with a single click.

I have a working draft that looks like:
![123](https://user-images.githubusercontent.com/54083835/78682271-59c1aa00-7920-11ea-944e-d4688b71de01.jpg)

The add to cart element will appear if you have at least one item selected, and will show the number of items and total price.

TODO: 
1. Need some ideas on how to style the cart element.
2. The cart element in its current position overlaps our back-to-top button.
3. Select All/Filter to all selected? Tricky due to Steam detaching rows that are not visible, might need a script based on wishlist.js.

**Comment by Revadike** [comment]
Hmm, this may be compatible with this issue: https://github.com/tfedor/AugmentedSteam/issues/689

**Comment by candela97** [comment]
yeah that's where I got the idea from.
I tried implementing this in a way that doesn't change any default behaviour though, so hopefully it can be enabled by default.

**Comment by candela97** [comment]
This idea was shelved due to adding too much clutter to the wishlist page, and will be implemented as #689.
