### ISSUE TITLE
Is the Performance Survey feature still functional?

### ISSUE THREAD

**Issue by Tenome** [IsThereAnyDeal/AugmentedSteam#859]
I'm guessing this is a leftover feature from Enhanced Steam, where users could fill out surveys that were stored on a server for other users to see. I can still see Performance Survey results on each game's Steam page, but I don't see anywhere to actually fill one out (nor do I see it on AS's site).

If it's still functional, how do I take it?

**Comment by MxtOUT** [comment]
No, it's like you said.
Currently we're only providing legacy data from ES, there's still serverside work to be done

**Comment by Tenome** [comment]
No worries, I was just wondering. Thanks.

**Comment by Korb** [comment]
@tfedor, can I somehow supplement the base, where does "Performance survey" information come from? Using which application, add-on, or manually?

**Comment by tfedor** [comment]
As was already said in, it's the leftover from ES, data were added manually by users.

**Comment by seeeeew** [comment]
At this point the existing performance data is almost three years old, which is an eternity in terms of gaming performance, so I don't feel it has any use even for the games old enough to still have data. I think it would be best to remove this feature completely for now, even if you're planning to bring it back with a new data entry option in the future. In its current form it adds nothing.

**Comment by MxtOUT** [comment]
Currently working on reimplementing the feature!

**Comment by Korb** [comment]
> @tfedor closed this as completed in #1858 12 hours ago

Has this feature been completely removed from the Augmented Steam?

**Comment by candela97** [comment]
Yep, it hasn't worked for years.
