### ISSUE TITLE
Connecting Augmented Steam with IsThereAnyDeal adds two copies of some games

### ISSUE THREAD

**Issue by SpaceClicker** [IsThereAnyDeal/AugmentedSteam#860]
I have connected Augmented Steam with IsThereAnyDeal and it appears to add some new games to my collection twice.

Will Glow the Wisp linked by system in collection at 2020-04-18 03:06 GMT
Will Glow the Wisp added by user in collection at 2020-04-18 00:10 GMT
Will Glow the Wisp added by user in collection at 2020-04-18 00:10 GMT

The "added" log entries seem to be from Augmented Steam, and the "linked" one I believe is the regular sync done by ITAD.  Only one copy of the game is linked, the other is not.

Could this be related to having Augmented Steam installed on more than one computer?
I only have one installation set to "Periodically import".  The timestamps on the two "adds" seems to be the same, so most likely not two separate installations doing it.

**Comment by MxtOUT** [comment]
So you're having three copies now?

**Comment by SpaceClicker** [comment]
No, it said I had to copies on Steam, I manually deleted one of them.  It has happened on about 3 or 4 games recently.
The three log entries above are the two adds (for the two copies) and a link (not sure what that is).

**Comment by SpaceClicker** [comment]
I added the game "Ashes of the Singularity: Escalation" to my Steam account and synced it with ITAD using the "Sync" function on the website.

Then, sometime later, a free DLC for that game was added to the ITAD DB by Augmented Steam.  It logged two "pruned" entries and then two "added" entries.

If you look at this DLC in ITAD, it shows that I own two copies of it on Steam.

I manually deleted one of the copies in the collection to resolve this error.

Here are the log entries:

added by user in collection at 2020-04-20 11:10 GMT
Ashes of the Singularity: Escalation - Co-Op Map Pack

added by user in collection at 2020-04-20 11:10 GMT
Ashes of the Singularity: Escalation - Co-Op Map Pack

pruned by user in collection at 2020-04-20 11:10 GMT
Ashes of the Singularity: Escalation - Co-Op Map Pack

pruned by user in collection at 2020-04-20 11:10 GMT
Ashes of the Singularity: Escalation - Co-Op Map Pack

Is this only a problem I am having or do others also have this issue?
Is there any troubleshooting I can do to figure out why it is happening?

**Comment by SpaceClicker** [comment]
I added a bunch of free OST (soundtracks) to my Steam account and these are the entries in the log (note that the entries are in reverse chronological order):

added by user in collection at 2020-04-24 01:29 GMT
Until You Fall - A Swordwave OST

added by user in collection at 2020-04-24 01:29 GMT
Until You Fall - A Swordwave OST

added by user in collection at 2020-04-24 01:29 GMT
Kingdom Under Fire: The Crusaders Soundtrack

pruned by user in collection at 2020-04-24 01:29 GMT
Until You Fall - A Swordwave OST

pruned by user in collection at 2020-04-24 01:29 GMT
Until You Fall - A Swordwave OST

pruned by user in collection at 2020-04-24 01:29 GMT
Kingdom Under Fire: The Crusaders Soundtrack

You can see that only one OST "Until You Fail - A Swordwave OST" was added twice to ITAD.  The others were added correctly and show that I own only one copy.  It shows that I own two copies of "Until You Fail - A Swordwave OST" on Steam.  As you prorbably know, it is not possible to own the same game/DLC/OST more than once on Steam (at least not in your library).

It does seem that it is a pattern that if I have added multiple items to my Steam account, only the first one added to ITAD is added twice and the others are fine.  Perhaps this is a clue as to what may be happening?

**Comment by MxtOUT** [comment]
I also had the exact same problem some time ago, but I can't reproduce it manually

**Comment by SpaceClicker** [comment]
Yeah, yesterday I added "HITMAN™ 2 – Standard Edition BUNDLE" to my Steam account (using a key) and did the sync on ITAD, then did the sync on AugmentedSteam and it added all the DLC that was included in the bundle (except for one I already had), but it also added one of the 6 remaining DLC twice, "Himmelstien" which is actually a free DLC (not that I think that matters).  

This time the repeated entry was the last DLC to be added to ITAD (according to the log).  It's almost like it is looping one more time than it should, like it starts from 0 instead of 1 or something like that and then just adds the same entry it just added previously.

**Comment by candela97** [comment]
Please file a new issue if there're still problems with the new ITAD, thanks!
