### ISSUE TITLE
Not showing Quick Sale buttons

### ISSUE THREAD

**Issue by lukefer** [IsThereAnyDeal/AugmentedSteam#863]
Title. I have no idea what's causing it, it just doesn't show.

**Comment by MxtOUT** [comment]
On what items do you notice this.
It's supposed to only work on Steam items

**Comment by ZIK999** [comment]
Same here. Quick Sale buttons didn't show up for few weeks on trading cards.

**Comment by MxtOUT** [comment]
Do you see any Augmented Steam related errors or warnings if you open your browser console (F12) on the page where the problem occurs?

**Comment by candela97** [comment]
Quick Sale buttons should be available on both Steam and non-Steam items now. Please open a new issue if you notice an item that's missing this feature, thanks!
