### ISSUE TITLE
Small improvement for new profile comment notification

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#886]
When you get a notification for a new comment on a steam profile, you get linked to the profile, but you still have to manually scroll to the comment section.
I'm proposing we either scroll to the comment section automatically (via hashes), or we visit the `/allcomments` link instead.

**Comment by candela97** [comment]
Notifications are a React component now. Though I'm not sure if profile comments work the same, it'll be much harder to modify and probably not worth it for a "small" improvement.
