### ISSUE TITLE
Thai baht currency conversion is not available.

### ISSUE THREAD

**Issue by ketaro121** [IsThereAnyDeal/AugmentedSteam#908]
It can be used in all currencies except Thai Baht.

![2563-06-18 20_03_22-ประหยัด 10% สำหรับ Detroit_ Become Human บน Steam](https://user-images.githubusercontent.com/67107145/85023450-f0bba580-b19e-11ea-9bdc-e84b1753730e.png)

Settings USD

![2563-06-18 20_02_55-ประหยัด 10% สำหรับ Detroit_ Become Human บน Steam](https://user-images.githubusercontent.com/67107145/85023466-f4e7c300-b19e-11ea-8298-1139a79bc78b.png)

**Comment by supakorn-ras** [comment]
Do you get the same error as https://github.com/tfedor/AugmentedSteam/issues/918#issuecomment-671181974?

**Comment by MxtOUT** [comment]
I can confirm that @ketaro121

**Comment by candela97** [comment]
This might have been a temporary issue where the extension failed to fetch currency conversion rates, and should resolve after a while. Please file a new issue if this is still a problem, thanks!
