### ISSUE TITLE
Can not show the lowest price.

### ISSUE THREAD

**Issue by ODBLK** [IsThereAnyDeal/AugmentedSteam#929]

**Comment by MxtOUT** [comment]
More info would be appreciated

**Comment by ODBLK** [comment]
Here‘s a example
![image](https://user-images.githubusercontent.com/25927859/124913383-a31c1000-e021-11eb-9e73-26472332266f.png)
My account is in Argentina now，the lowest prize is ARS$ 649,50. But the lowest prize in history is ARS$ 2.877,34

**Comment by candela97** [comment]
For currencies unsupported by ITAD, the price history feature can be misleading, see #482.
