### ISSUE TITLE
having an emote in summary disables showing 4th line

### ISSUE THREAD

**Issue by h3oCharles** [IsThereAnyDeal/AugmentedSteam#933]
![unicode](https://user-images.githubusercontent.com/8020330/88552406-57e13b00-d024-11ea-8b76-6f8eee817805.png)
![emote](https://user-images.githubusercontent.com/8020330/88552413-59aafe80-d024-11ea-804f-c9dddd5a3c59.png)
```
█ line1
█ line2
█ line3
█ line4

:orangecube: line1
:orangecube: line2
:orangecube: line3
:orangecube: line4

**Comment by Revadike** [comment]
I think that's a steam thing and not AS's fault. However, we could perhaps have an option to auto-expand all profile descriptions.

**Comment by h3oCharles** [comment]
I think it's worth pointing out that if I don't have emotes in summary, refreshing the page still shows "View more info" but only for a split second

**Comment by MxtOUT** [comment]
> I think that's a steam thing and not AS's fault. However, we could perhaps have an option to auto-expand all profile descriptions.

Yes, maybe not directly in settings though to avoid cluttering.
Perhaps you could prompt the user for enabling this setting for the first time when they expand a profile summary and also when he has the setting enabled and clicks on collapse to disable it.
The first one should have a "Do not show again" checkbox though

**Comment by candela97** [comment]
Apparently the profile summary is used by account hijackers for scams, and it's serious enough for Steam to put a warning in the popup dialog, so I don't think auto-expanding is a good idea...

**Comment by MxtOUT** [comment]
If it's still desired, please open an issue for the auto-expansion of the profile summary.
@candela97 I don't see the warning you mentioned and I can also not imagine how this should be used by scammers.

**Comment by candela97** [comment]
@MxtOUT Just type enough lines into the box on your profile, then you'll see the warning when you click on "View more info" 😄
