### ISSUE TITLE
Please add ability to narrow game list by sale pecentage

### ISSUE THREAD

**Issue by michaldaniel** [IsThereAnyDeal/AugmentedSteam#938]
It would be great to be able to narrow game list by sale percentage. The same way there are currently "Narrow by Price" filters on game list. It would be useful when browsing Steam specials to narrow the search to "50% sale or more", "75% sale or more" etc. to only view biggest discounts.

**Comment by WilliamStone** [comment]
Agree on this.

**Comment by MxtOUT** [comment]
Implemented by #1682
