### ISSUE TITLE
Context Menu options not working

### ISSUE THREAD

**Issue by CrimsonAvenger** [IsThereAnyDeal/AugmentedSteam#944]
I cannot seem to get any of the context menu options to work.  I have uninstalled Enhanced Steam, cleared cache on browser and AS, disabled all extensions, cleared again, restarted - nothing seemed to help.

Chrome 85.0.4183.83 (Official Build) (64-bit)

TIA

**Comment by MxtOUT** [comment]
What do you see if you [inspect Augmented Steam's background page](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page)?

**Comment by fadster** [comment]
I confirm the context menu isn't working properly. When I enable it, it works for a little while then disappears altogether until I toggle it back off and on.

**Comment by CrimsonAvenger** [comment]
Apologies for not replying sooner. Sh*t happens.

As I recall, I installed another unrelated extension, then tried again on a whim. Lo and behold, all was fine. Which one? I'd be lying if I said I knew. Still working perfectly on:

Chrome 86.0.4240.75 (Official Build) (64-bit)

**Comment by MxtOUT** [comment]
So we were doing a bit of an overhaul for the whole permission stuff.
This problem might be fixed on the development version, we'll see that if we deploy to the web stores

**Comment by candela97** [comment]
Let us know if this is still an issue on the latest version of AS.
