### ISSUE TITLE
Steam Augmented Firefox Error

### ISSUE THREAD

**Issue by OgnistyPoland** [IsThereAnyDeal/AugmentedSteam#951]
> Regional pricing store.js:429:33
> Error: Could not establish conversion rate between USD and PLN
>     inCurrency moz-extension://59722207-e426-40fe-a48f-3fc69d25172b/js/content/common.js:978
>     showRegionalPricing moz-extension://59722207-e426-40fe-a48f-3fc69d25172b/js/content/store.js:427
>     AppPageClass moz-extension://59722207-e426-40fe-a48f-3fc69d25172b/js/content/store.js:650
>     <anonymous> moz-extension://59722207-e426-40fe-a48f-3fc69d25172b/js/content/store.js:4112
>     async* moz-extension://59722207-e426-40fe-a48f-3fc69d25172b/js/content/store.js:4164
> store.js:430:33
> Not able to show converted price and relative price differences for country code "US"

currency converter doesn't work

**Comment by candela97** [comment]
Can you check the version of your extension? This should be fixed already, see #580.

**Comment by candela97** [comment]
This is usually a temporary issue with ITAD servers. Let us know if this is still an issue!
